"""Pilot Real-Speech Welle 50 — 50 Basisszenarien (echte Diktat-Muster)."""

from __future__ import annotations


def all_base_scenarios() -> list[dict]:
    return [
        {
            "raw": 'Heute haben wir den Untergrund frei gebaggert dann 5 m³ Schotter null 32 eingebaut danach drei Kubik Split zwei Fünfer eingebaut und dann 40 m² Pflaster eingebaut',
            "acts": ('Graben ausgehoben', 'Baggerarbeiten durchgeführt'),
            "mats": ('Schotter', 'Splitt', 'Pflastersteine'),
            "mach_sug": ('Bagger',),
            "sum_qty": ('5',),
            "strict": True,
            "min_act": 2,
        },
        {
            "raw": 'Heute haben wir den Graben frei gebaggert dann mit 5 m³ Schotter null 32 verdichtet und danach zwei Kubik Split zwei Fünfer verarbeitet und morgen müssen wir dann 30 m² Pflaster legen',
            "acts": ('Graben ausgehoben', 'Baggerarbeiten durchgeführt'),
            "mats": ('Schotter', 'Splitt', 'Pflastersteine'),
            "mach_sug": ('Bagger',),
            "forbid_acts": ('30 m² Pflaster verlegt', 'Morgen müssen'),
            "open_must": ('morgen', 'pflaster', 'offen'),
            "sum_not": ('pflaster verlegt',),
            "open_": True,
            "forbid_future_pflaster": True,
            "strict": True,
            "min_act": 2,
        },
        {
            "raw": 'Heute haben wir den Untergrund frei gebaggert damit 3,5 m³ Schotter null 32 verdichtet dann haben wir drei Kubik Split zwei Fünfer eingebaut leider mussten wir die Arbeiten abrechnen weil es stark angefangen zu regnen dementsprechend verschiebt sich das Pflastern auf morgen',
            "acts": ('Baggerarbeiten durchgeführt',),
            "mats": ('Schotter', 'Splitt'),
            "mach_sug": ('Bagger',),
            "prob_must": ('regen',),
            "open_must": ('morgen', 'pflaster', 'verschoben'),
            "problem": True,
            "open_": True,
            "strict": True,
            "min_act": 1,
        },
        {
            "raw": 'Heute haben wir den Untergrund frei gebaggert dann 5 m³ Schotter null 32 eingebaut danach drei Kubik Split zwei Fünfer eingebaut',
            "act_tokens": ('schotter', 'splitt', 'graben', 'bagger'),
            "mat_tokens": ('schotter', 'splitt'),
            "mach_sug": ('Bagger',),
            "min_act": 1,
        },
        {
            "raw": 'Graben frei gebaggert mit 3,5 m³ Schotter 0/32 verdichtet zwei Kubik Splitt 2/5 eingebaut Bagger war den ganzen Tag da.',
            "act_tokens": ('schotter', 'splitt', 'bagger'),
            "mat_tokens": ('schotter', 'splitt'),
            "mach_sug": ('Bagger',),
            "min_act": 1,
        },
        {
            "raw": 'Heute Untergrund frei gebaggert 5 Kubik Schotter null 32 eingebaut danach 3 Kubik Split zwei Fünfer und 40 Quadratmeter Pflaster eingebaut',
            "act_tokens": ('schotter', 'splitt', 'pflaster', 'bagger'),
            "mat_tokens": ('schotter', 'splitt'),
            "min_act": 1,
        },
        {
            "raw": 'Heute haben wir den Graben ausgehoben dann 5 m³ Schotter eingebaut und Splitt 2/5 mm eingebaut',
            "act_tokens": ('schotter', 'splitt', 'graben'),
            "mat_tokens": ('schotter', 'splitt'),
            "min_act": 1,
        },
        {
            "raw": 'Erdarbeiten heute: Untergrund gebaggert Schotterplanum mit 4 m³ Schotter 0/32 verdichtet Splitt 2/5 eingebaut.',
            "act_tokens": ('schotter', 'splitt', 'bagger'),
            "mat_tokens": ('schotter', 'splitt'),
            "mach_sug": ('Bagger',),
            "min_act": 1,
        },
        {
            "raw": 'morgen müssen wir noch 25 m² Pflaster legen Schmitz Außenanlage',
            "open_must": ('morgen', 'pflaster', 'offen'),
            "open_": True,
            "forbid_future_pflaster": True,
            "min_act": 0,
        },
        {
            "raw": 'Heute Schotter eingebaut und Splitt eingebaut dementsprechend verschiebt sich das Pflastern auf morgen Schmitz Außenanlage',
            "act_tokens": ('schotter', 'splitt'),
            "mat_tokens": ('schotter', 'splitt'),
            "open_must": ('morgen', 'pflaster', 'verschoben'),
            "open_": True,
            "forbid_future_pflaster": True,
            "min_act": 1,
        },
        {
            "raw": 'Graben gemacht 3 m³ Schotter verdichtet und dann Offen Pflasterarbeiten morgen noch fertig machen',
            "act_tokens": ('schotter', 'pflaster', 'graben'),
            "mat_tokens": ('schotter',),
            "open_must": ('morgen', 'offen'),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Heute 2 m³ Splitt eingebaut morgen müssen wir noch 18 m² Pflaster verlegen auf der Schmitz Außenanlage',
            "mat_tokens": ('splitt',),
            "forbid_acts": ('18 m² Pflaster verlegt',),
            "open_must": ('morgen', 'pflaster'),
            "open_": True,
            "forbid_future_pflaster": True,
            "min_act": 0,
        },
        {
            "raw": 'Rest Pflaster morgen legen Schotter und Splitt heute fertig Schmitz Außenanlage',
            "mat_tokens": ('schotter', 'splitt'),
            "open_must": ('morgen', 'pflaster', 'offen'),
            "open_": True,
            "min_act": 0,
        },
        {
            "raw": 'Baggerarbeiten und Graben heute erledigt Schotter eingebaut morgen noch 35 Quadratmeter Pflaster legen',
            "act_tokens": ('bagger', 'schotter', 'graben'),
            "mat_tokens": ('schotter',),
            "mach_sug": ('Bagger',),
            "open_must": ('morgen', 'pflaster'),
            "open_": True,
            "forbid_future_pflaster": True,
            "min_act": 1,
        },
        {
            "raw": 'Schotterplanum hergestellt Splitt eingebaut Pflaster verschiebt sich auf Montag Schmitz Außenanlage',
            "mat_tokens": ('splitt',),
            "open_must": ('montag', 'pflaster', 'verschoben'),
            "open_": True,
            "min_act": 0,
        },
        {
            "raw": 'Heute Graben und Schotter 0/32 verdichtet zwei Kubik Splitt eingebaut und morgen Pflaster legen noch offen',
            "act_tokens": ('schotter', 'splitt', 'graben'),
            "mat_tokens": ('schotter', 'splitt'),
            "open_must": ('morgen', 'pflaster', 'offen'),
            "open_": True,
            "forbid_future_pflaster": True,
            "min_act": 1,
        },
        {
            "raw": 'Untergrund gebaggert Schotter verdichtet leider mussten wir abbrechen weil es angefangen zu regnen Schmitz Außenanlage',
            "act_tokens": ('schotter', 'bagger'),
            "prob_must": ('regen',),
            "problem": True,
            "min_act": 0,
        },
        {
            "raw": '3 m³ Schotter eingebaut leider mussten wir die Arbeiten abrechnen weil es stark angefangen zu regnen',
            "mat_tokens": ('schotter',),
            "prob_must": ('regen',),
            "problem": True,
            "min_act": 0,
        },
        {
            "raw": 'Problem Regen heute keine Arbeit mehr Schotter halb eingebaut Schmitz Außenanlage',
            "mat_tokens": ('schotter',),
            "prob_must": ('regen',),
            "problem": True,
            "min_act": 0,
        },
        {
            "raw": 'Graben ausgehoben Splitt eingebaut mussten wegen Regen stoppen Offen Pflaster morgen',
            "act_tokens": ('graben', 'splitt'),
            "mat_tokens": ('splitt',),
            "prob_must": ('regen',),
            "open_must": ('morgen', 'pflaster'),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Heute Schotter und Splitt eingebaut leider Regen Arbeiten unterbrochen Pflastern morgen Schmitz Außenanlage',
            "mat_tokens": ('schotter', 'splitt'),
            "prob_must": ('regen',),
            "open_must": ('morgen',),
            "problem": True,
            "open_": True,
            "min_act": 0,
        },
        {
            "raw": 'leider mussten wir stoppen weil es geregnet hat Erdarbeiten Schmitz Außenanlage',
            "prob_must": ('regen',),
            "problem": True,
            "min_act": 0,
        },
        {
            "raw": 'Baggerarbeiten Graben Schotter verdichtet Problem Wetter Offen Rest morgen Pflaster',
            "act_tokens": ('bagger', 'schotter'),
            "mach_sug": ('Bagger',),
            "prob_must": ('wetter',),
            "open_must": ('morgen', 'pflaster'),
            "problem": True,
            "open_": True,
            "min_act": 0,
        },
        {
            "raw": '3,5 m³ Schotter null 32 verdichtet drei Kubik Split eingebaut leider mussten wir die Arbeiten abbrechen weil es stark angefangen hat zu regnen',
            "mat_tokens": ('schotter', 'splitt'),
            "prob_must": ('regen',),
            "problem": True,
            "min_act": 0,
        },
        {
            "raw": '5 m³ Schotter 0/32 eingebaut Schmitz Außenanlage',
            "mat_tokens": ('schotter',),
            "min_act": 0,
        },
        {
            "raw": 'drei Kubik Splitt zwei Fünfer eingebaut Schmitz Außenanlage',
            "mat_tokens": ('splitt',),
            "min_act": 0,
        },
        {
            "raw": 'zwei Kubikmeter Schotter null 45 verdichtet Schmitz Außenanlage',
            "mat_tokens": ('schotter',),
            "min_act": 0,
        },
        {
            "raw": '4 Kubik Split 0/8 eingebaut auf der Schmitz Außenanlage',
            "mat_tokens": ('splitt',),
            "min_act": 0,
        },
        {
            "raw": 'Schotter 0/32 6 m³ eingebaut Splitt 2/5 2 m³ Schmitz Außenanlage',
            "mat_tokens": ('schotter', 'splitt'),
            "min_act": 0,
        },
        {
            "raw": 'heute 50 Quadratmeter Pflaster gelegt Schmitz Außenanlage',
            "act_tokens": ('pflaster',),
            "mat_tokens": ('pflaster',),
            "min_act": 1,
        },
        {
            "raw": '40 m² Pflaster verlegt Fugensand nachgezogen Schmitz Außenanlage',
            "act_tokens": ('pflaster',),
            "mat_tokens": ('pflaster',),
            "min_act": 1,
        },
        {
            "raw": 'Planum hergestellt 3 m³ Schotter eingebaut 2 m³ Splitt Schmitz Außenanlage',
            "mat_tokens": ('schotter', 'splitt'),
            "min_act": 0,
        },
        {
            "raw": 'Untergrund frei gebaggert Schmitz Außenanlage',
            "act_tokens": ('graben', 'bagger'),
            "mach_sug": ('Bagger',),
            "min_act": 1,
        },
        {
            "raw": 'Baggerarbeiten durchgeführt Graben ausgehoben Schmitz Außenanlage',
            "act_tokens": ('bagger', 'graben'),
            "mach_sug": ('Bagger',),
            "min_act": 1,
        },
        {
            "raw": 'Schotter eingebaut Splitt eingebaut Schmitz Außenanlage',
            "mat_tokens": ('schotter', 'splitt'),
            "min_act": 0,
        },
        {
            "raw": 'Heute auf der Schmitz Außenanlage Erdarbeiten Schotter Splitt und morgen Pflaster',
            "open_must": ('morgen', 'pflaster'),
            "open_": True,
            "min_act": 0,
        },
        {
            "raw": 'Morgens Graben gebaggert mittags 3 m³ Schotter verdichtet nachmittags Splitt eingebaut Schmitz Außenanlage',
            "act_tokens": ('schotter', 'splitt', 'bagger', 'graben'),
            "mat_tokens": ('schotter', 'splitt'),
            "mach_sug": ('Bagger',),
            "min_act": 1,
        },
        {
            "raw": 'Also heute Schmitz Außenanlage erst Untergrund frei gebaggert dann Schotter null 32 und drei Kubik Split zwei Fünfer und Feierabend',
            "act_tokens": ('schotter', 'splitt', 'graben', 'bagger'),
            "mat_tokens": ('schotter', 'splitt'),
            "min_act": 1,
        },
        {
            "raw": 'hamma graben frei gebaggert und 5 kubik schotter eingebaut Schmitz Außenanlage',
            "act_tokens": ('schotter', 'graben', 'bagger'),
            "mat_tokens": ('schotter',),
            "min_act": 1,
        },
        {
            "raw": 'Heute Schmitz Außenanlage Schotter Splitt eingebaut mit dem Bauherrn kurz gesprochen er ist zufrieden',
            "mat_tokens": ('schotter', 'splitt'),
            "cust_must": ('gesprochen', 'zufrieden'),
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Problem Lieferung Schotter spät Offen Splitt morgen nachliefern Schmitz Außenanlage',
            "prob_must": ('liefer', 'spät'),
            "open_must": ('morgen', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 0,
        },
        {
            "raw": 'Radlader 4 std Bagger 6 std heute Schotterplanum und Splitt auf der Schmitz Außenanlage',
            "act_tokens": ('bagger', 'radlader', 'schotter', 'splitt'),
            "mat_tokens": ('splitt',),
            "min_act": 1,
        },
        {
            "raw": 'Kies 2 m³ eingebaut Schotter 3 m³ Splitt 1 m³ Schmitz Außenanlage',
            "mat_tokens": ('schotter', 'splitt', 'kies'),
            "min_act": 0,
        },
        {
            "raw": 'Terrasse 22 m² Pflaster verlegt Schottertragschicht davor Schmitz Außenanlage',
            "act_tokens": ('pflaster',),
            "mat_tokens": ('schotter', 'pflaster'),
            "min_act": 1,
        },
        {
            "raw": 'Drainage Graben Schotter Splitt Pflastersteinen gesetzt Schmitz Außenanlage',
            "mat_tokens": ('schotter', 'splitt'),
            "min_act": 0,
        },
        {
            "raw": 'Heute Schmitz Außenanlage Untergrund gebaggert 4 m³ Schotter 0/32 verdichtet 3 Kubik Splitt 2/5 ohne Pflaster',
            "act_tokens": ('schotter', 'splitt', 'bagger'),
            "mat_tokens": ('schotter', 'splitt'),
            "mach_sug": ('Bagger',),
            "forbid_future_pflaster": True,
            "min_act": 1,
        },
        {
            "raw": 'Schotter eingebaut Splitt eingebaut Problem Maschine kaputt Offen Rest morgen Schmitz Außenanlage',
            "mat_tokens": ('schotter', 'splitt'),
            "prob_must": ('maschine', 'kaputt'),
            "open_must": ('morgen', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 0,
        },
        {
            "raw": 'Erdplanum erstellt Frostschutz 8 m³ Schotter 0/45 Schmitz Außenanlage',
            "mat_tokens": ('schotter',),
            "min_act": 0,
        },
        {
            "raw": 'Heute Schmitz Außenanlage 6 m³ Schotter null 32 eingebaut und 2 m³ Splitt 2/5 dann Feierabend',
            "mat_tokens": ('schotter', 'splitt'),
            "min_act": 0,
        },
        {
            "raw": 'Untergrund gebaggert Schotter verdichtet Splitt verarbeitet Pflaster morgen Schmitz Außenanlage',
            "mat_tokens": ('schotter', 'splitt'),
            "open_must": ('morgen', 'pflaster'),
            "open_": True,
            "forbid_future_pflaster": True,
            "min_act": 0,
        },
    ]

