"""Szenario-Daten für Pilot-Monster-Welle 21 — 50 Basisszenarien pro Gewerk."""

from __future__ import annotations

TRADE_SCENARIOS: dict[str, list[dict]] = {
    "GaLaBau": [
        {
            "raw": '50 Quadratmeter Pflaster verlegt zwei Kubikmeter Schotter eingebaut Hecke geschnitten Bauherr kurz da Problem Lieferung spät Offen letzte Reihe morgen Mit der Kundin gesprochen sie war sehr zufrieden.',
            "acts": ('50 m² Pflaster verlegt', 'Schotter eingebaut', 'Hecke geschnitten'),
            "mats": ('Pflastersteine', 'Schotter'),
            "forbid_acts": ('Pflastersteine verarbeitet',),
            "problem": True,
            "open_": True,
            "customer": True,
            "cust_not": ('50', 'pflaster', 'schotter', 'm²'),
            "mat_echo": True,
        },
        {
            "raw": 'Heute haben wir 50 qm² pflaster gelegt. Anschließend haben wir uns mit der Kundin unterhalten und die Kundin war sehr zufrieden.',
            "acts": ('50 m² Pflaster verlegt',),
            "mats": ('Pflastersteine',),
            "customer": True,
            "cust_not": ('50', 'pflaster', 'qm'),
        },
        {
            "raw": 'heute 30 quadrat pflaster gelegt und schotter reingemacht und kundin zufrieden problem regen offen rest montag',
            "acts": ('30 m² Pflaster verlegt', 'Schotter eingebaut'),
            "mats": ('Pflastersteine', 'Schotter'),
            "problem": True,
            "open_": True,
            "customer": True,
            "cust_not": ('30', 'schotter'),
        },
        {
            "raw": 'Kundengespräch gehabt Pflastermuster gewählt Problem Drainage Offen Rest nächste Woche.',
            "acts": (),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Wir haben den Rasen gemäht vertikutiert und anschließend gedüngt sowie die Fläche bewässert.',
            "acts": ('Rasen gemäht', 'Rasen vertikutiert', 'Rasen gedüngt', 'Fläche bewässert'),
        },
        {
            "raw": '60 Quadratmeter Pflaster verlegt 25 laufende Meter Rasenkantensteine gesetzt Hecke geschnitten Rindenmulch eingedeckt.',
            "acts": ('60 m² Pflaster verlegt', 'Rasenkantensteine gesetzt', 'Hecke geschnitten', 'Rindenmulch eingedeckt'),
            "mats": ('Pflastersteine', 'Rasenkantensteine'),
        },
        {
            "raw": '3 Stunden mit dem Bagger Erdaushub gemacht danach 40 Quadratmeter Pflaster verlegt zwei Kubikmeter Schotter eingebaut.',
            "acts": ('40 m² Pflaster verlegt', 'Schotter eingebaut'),
            "mats": ('Pflastersteine', 'Schotter'),
        },
        {
            "raw": '30 Quadratmeter Keramikterrasse verlegt Geotextil verlegt Splitt 2/5 mm eingebaut.',
            "acts": ('30 m² Keramikterrasse verlegt', 'Geotextil verlegt', 'Splitt 2/5 mm eingebaut'),
            "mats": ('Keramikplatten', 'Geotextil', 'Splitt'),
        },
        {
            "raw": '2,5 Stunden Radlader Schotter verteilt Untergrund verdichtet 35 Quadratmeter Pflaster verlegt.',
            "acts": ('Schotter eingebaut', 'Untergrund verdichtet', '35 m² Pflaster verlegt'),
            "mats": ('Pflastersteine', 'Schotter'),
        },
        {
            "raw": 'Winterdienst durchgeführt Schnee geräumt Streugut gestreut 12 Quadratmeter WPC Terrasse gebaut.',
            "acts": ('12 m² Holz-/WPC-Terrasse gebaut',),
            "mats": ('WPC-Dielen', 'Streugut'),
            "min_act": 1,
        },
        {
            "raw": '30 Quadratmeter Pflaster verlegt 10 Quadratmeter Gartenmauer gebaut 15 laufende Meter Palisaden gesetzt Hecke geschnitten.',
            "acts": ('30 m² Pflaster verlegt', 'Gartenmauer gebaut', 'Palisaden gesetzt', 'Hecke geschnitten'),
        },
        {
            "raw": 'heute ich hab gemacht 15 meter Palisaden gesetzt und 30 quadrat Rollrasen verlegt.',
            "acts": ('Palisaden gesetzt', '30 m² Rasen verlegt'),
        },
        {
            "raw": 'Mit dem Bagger Fläche vorbereitet 25 Quadratmeter Pflaster verlegt Schotter eingebaut.',
            "acts": ('25 m² Pflaster verlegt', 'Schotter eingebaut'),
            "mats": ('Pflastersteine', 'Schotter'),
        },
        {
            "raw": 'Radlader Mulch verteilt 20 Quadratmeter Pflaster verlegt Hecke geschnitten.',
            "acts": ('20 m² Pflaster verlegt', 'Hecke geschnitten'),
        },
        {
            "raw": 'Vormittags Rasen getrimmt Unkraut gezupft Hecke zurückgeschnitten.',
            "acts": ('Rasen getrimmt', 'Hecke geschnitten'),
            "min_act": 2,
        },
        {
            "raw": '30 Quadratmeter Pflaster gelegt Schotter reingemacht Laub gefegt.',
            "acts": ('30 m² Pflaster verlegt', 'Schotter eingebaut', 'Laub entfernt'),
            "mats": ('Pflastersteine', 'Schotter'),
        },
        {
            "raw": 'Heute den ganzen Garten freigeschnitten Unkraut weg gemacht.',
            "acts": ('Rasen getrimmt', 'Unkraut entfernt'),
        },
        {
            "raw": 'fünfundzwanzig laufende Meter Rasenkantensteine gesetzt.',
            "acts": ('Rasenkantensteine gesetzt',),
            "mats": ('Rasenkantensteine',),
            "min_act": 1,
        },
        {
            "raw": 'Drei Pflanzkübel mit Erde befüllt Beet angelegt Pflanzen gesetzt.',
            "acts": ('Pflanzkübel', 'Pflanzen gesetzt'),
            "min_act": 1,
        },
        {
            "raw": '30 Quadratmeter Rollrasen verlegt Untergrund verdichtet.',
            "acts": ('30 m² Rasen verlegt', 'Untergrund verdichtet'),
        },
        {
            "raw": 'heute ich machen 50 quadrat Pflaster Hecke schneiden Unkraut weg machen.',
            "acts": ('Hecke geschnitten',),
            "min_act": 1,
        },
        {
            "raw": 'heute auf baustell ich hab gearbeitet 30 quadrat Pflaster.',
            "acts": ('30 m² Pflaster verlegt',),
            "min_act": 1,
        },
        {
            "raw": '55 Quadratmeter Pflaster verlegt 20 laufende Meter Rasenkantensteine gesetzt Hecke geschnitten Bauherr zufrieden Problem Regen Offen letzte Fläche Montag.',
            "acts": ('55 m² Pflaster verlegt', 'Rasenkantensteine gesetzt', 'Hecke geschnitten'),
            "mats": ('Pflastersteine',),
            "problem": True,
            "open_": True,
            "customer": True,
        },
        {
            "raw": '40 Quadratmeter Pflaster verlegt zwei Kubikmeter Schotter eingebaut Hecke geschnitten Mulch eingedeckt.',
            "acts": ('40 m² Pflaster verlegt', 'Schotter eingebaut', 'Hecke geschnitten'),
            "mats": ('Pflastersteine', 'Schotter'),
        },
        {
            "raw": '50 qm Pflaster gelegt zwei Kubik Schotter rein zwei fünfer Split eingebaut.',
            "acts": ('50 m² Pflaster verlegt', '2 m³ Schotter eingebaut'),
            "mats": ('Pflastersteine', 'Schotter'),
        },
        {
            "raw": 'Beet angelegt Pflanzen gesetzt Fläche bewässert.',
            "acts": ('Pflanzen gesetzt', 'Fläche bewässert'),
        },
        {
            "raw": 'heute ich machen Rasen mähen 100 quadrat.',
            "acts": ('100 m² Rasen gemäht',),
            "min_act": 1,
        },
        {
            "raw": 'Laub entfernt Gehweg kehren fertig.',
            "acts": ('Laub entfernt',),
            "min_act": 1,
        },
        {
            "raw": '15 Quadratmeter Naturstein verlegt Fugen verfugt.',
            "acts": ('Naturstein verlegt', 'Fliesen verfugt'),
        },
        {
            "raw": '45 qm Pflaster verlegt Pflastersteine verbaut Schotter eingebaut Kundin zufrieden.',
            "acts": ('45 m² Pflaster verlegt', 'Schotter eingebaut'),
            "mats": ('Pflastersteine', 'Schotter'),
            "forbid_acts": ('Pflastersteine verarbeitet',),
            "customer": True,
            "cust_not": ('pflaster', 'qm'),
            "mat_echo": True,
        },
        {
            "raw": 'Terrasse neu 35 Quadratmeter Keramikplatten verlegt Splitt eingebaut Bauherrin sehr happy Problem falsche Farbe Offen Umtausch nächste Woche.',
            "acts": ('35 m² Keramikterrasse verlegt',),
            "mats": ('Keramikplatten',),
            "problem": True,
            "open_": True,
            "customer": True,
        },
        {
            "raw": 'Mit dem Kunden gesprochen er möchte weiter mit uns arbeiten.',
            "acts": (),
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Heute 40 Quadratmeter Pflaster verlegt Feierabend.',
            "acts": ('40 m² Pflaster verlegt',),
            "mats": ('Pflastersteine',),
            "min_act": 1,
        },
        {
            "raw": '18 Quadratmeter Pflaster verlegt',
            "acts": ('18 m² Pflaster verlegt',),
            "mats": ('Pflastersteine',),
            "min_act": 1,
        },
        {
            "raw": '22 Quadratmeter Pflaster verlegt Problem Material knapp Offen Rest morgen.',
            "acts": ('22 m² Pflaster verlegt',),
            "mats": ('Pflastersteine',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '28 Quadratmeter Pflaster verlegt Bauherr informiert alles abgestimmt.',
            "acts": ('28 m² Pflaster verlegt',),
            "mats": ('Pflastersteine',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '33 Quadratmeter Pflaster verlegt Kundin mega zufrieden.',
            "acts": ('33 m² Pflaster verlegt',),
            "mats": ('Pflastersteine',),
            "customer": True,
            "min_act": 1,
            "cust_not": ('pflaster', 'qm'),
        },
        {
            "raw": '38 Quadratmeter Pflaster verlegt Auftraggeber kurz gesprochen Problem Wetter Offen nächste Woche.',
            "acts": ('38 m² Pflaster verlegt',),
            "mats": ('Pflastersteine',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
            "cust_not": ('pflaster', 'meter'),
        },
        {
            "raw": '42 Quadratmeter Pflaster verlegt',
            "acts": ('42 m² Pflaster verlegt',),
            "mats": ('Pflastersteine',),
            "min_act": 1,
        },
        {
            "raw": '48 Quadratmeter Pflaster verlegt Problem Material knapp Offen Rest morgen.',
            "acts": ('48 m² Pflaster verlegt',),
            "mats": ('Pflastersteine',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '52 Quadratmeter Pflaster verlegt Bauherr informiert alles abgestimmt.',
            "acts": ('52 m² Pflaster verlegt',),
            "mats": ('Pflastersteine',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '58 Quadratmeter Pflaster verlegt Kundin mega zufrieden.',
            "acts": ('58 m² Pflaster verlegt',),
            "mats": ('Pflastersteine',),
            "customer": True,
            "min_act": 1,
            "cust_not": ('pflaster', 'qm'),
        },
        {
            "raw": '65 Quadratmeter Pflaster verlegt Auftraggeber kurz gesprochen Problem Wetter Offen nächste Woche.',
            "acts": ('65 m² Pflaster verlegt',),
            "mats": ('Pflastersteine',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
            "cust_not": ('pflaster', 'meter'),
        },
        {
            "raw": '70 Quadratmeter Pflaster verlegt',
            "acts": ('70 m² Pflaster verlegt',),
            "mats": ('Pflastersteine',),
            "min_act": 1,
        },
        {
            "raw": '75 Quadratmeter Pflaster verlegt Problem Material knapp Offen Rest morgen.',
            "acts": ('75 m² Pflaster verlegt',),
            "mats": ('Pflastersteine',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '80 Quadratmeter Pflaster verlegt Bauherr informiert alles abgestimmt.',
            "acts": ('80 m² Pflaster verlegt',),
            "mats": ('Pflastersteine',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '85 Quadratmeter Pflaster verlegt Kundin mega zufrieden.',
            "acts": ('85 m² Pflaster verlegt',),
            "mats": ('Pflastersteine',),
            "customer": True,
            "min_act": 1,
            "cust_not": ('pflaster', 'qm'),
        },
        {
            "raw": '90 Quadratmeter Pflaster verlegt Auftraggeber kurz gesprochen Problem Wetter Offen nächste Woche.',
            "acts": ('90 m² Pflaster verlegt',),
            "mats": ('Pflastersteine',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
            "cust_not": ('pflaster', 'meter'),
        },
        {
            "raw": '95 Quadratmeter Pflaster verlegt',
            "acts": ('95 m² Pflaster verlegt',),
            "mats": ('Pflastersteine',),
            "min_act": 1,
        },
        {
            "raw": '105 Quadratmeter Pflaster verlegt Problem Material knapp Offen Rest morgen.',
            "acts": ('105 m² Pflaster verlegt',),
            "mats": ('Pflastersteine',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
    ],
    "Trockenbau": [
        {
            "raw": 'Gipskartonplatten montiert Decke abgehängt Problem Lieferung Offen letzte Wand mit der Bauleitung Rücksprache gehalten.',
            "acts": ('Gipskartonplatten montiert', 'Decke abgehängt'),
            "mats": ('Gipskartonplatten',),
            "problem": True,
            "open_": True,
            "customer": True,
            "cust_not": ('gipskarton', 'decke'),
        },
        {
            "raw": 'Trockenbauwand geschlossen Ständerwerk montiert.',
            "acts": ('Trockenbauwand geschlossen', 'Ständerwerk montiert'),
        },
        {
            "raw": 'Brandschutzwand hergestellt Akustikdecke eingebaut.',
            "acts": ('Brandschutzwand hergestellt', 'Akustikdecke eingebaut'),
        },
        {
            "raw": 'heute ich hab gipskarton gemacht decke abhaengen problem schrauben offen morgen',
            "acts": ('Gipskartonplatten montiert',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'CW-Profil und UW-Profil montiert Dämmmatte eingesetzt zwei Lagen Gipskarton verschraubt Fugenspachtel gezogen Bauleitung abgesprochen Problem Lieferverzug Offen Revisionsöffnung Freitag.',
            "acts": ('Gipskartonplatten montiert',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Decke abgehängt CD-Profile montiert Abhänger gesetzt.',
            "acts": ('Ständerwerk montiert',),
            "min_act": 1,
        },
        {
            "raw": 'Ständerwerk montiert Dämmung eingebaut Gipskartonplatten montiert.',
            "acts": ('Ständerwerk montiert', 'Dämmung eingebaut', 'Gipskartonplatten montiert'),
            "mats": ('Gipskartonplatten',),
        },
        {
            "raw": 'Fugen verspachtelt und geschliffen.',
            "acts": ('Fugen verspachtelt',),
            "min_act": 1,
        },
        {
            "raw": 'Revisionsklappe eingebaut.',
            "acts": ('Revisionsklappe eingebaut',),
            "min_act": 1,
        },
        {
            "raw": 'Kundengespräch gehabt Wandaufbau besprochen Problem Schrauben Offen Rest nächste Woche.',
            "acts": (),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'rigips dran gemacht wand zugemacht.',
            "acts": ('Gipskartonplatten montiert', 'Trockenbauwand geschlossen'),
        },
        {
            "raw": 'heute auf baustell ich hab rigips montiert 40 quadratmeter.',
            "acts": ('Gipskartonplatten montiert',),
            "min_act": 1,
        },
        {
            "raw": 'Zwei Trockenbauwände geschlossen Decke abgehängt Kunde war da und happy Problem Folie knapp Offen Rest morgen.',
            "acts": ('Decke abgehängt',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Akustikdecke eingebaut Mineralwolle eingebaut.',
            "acts": ('Dämmung eingebaut',),
            "min_act": 1,
        },
        {
            "raw": 'Brandschutzwand hergestellt zweifach beplankt.',
            "acts": ('Brandschutzwand hergestellt',),
            "min_act": 1,
        },
        {
            "raw": 'Gipskarton im Bad montiert Feuchtraumplatten gesetzt.',
            "acts": ('Gipskartonplatten montiert',),
            "min_act": 1,
        },
        {
            "raw": 'Trennwand gestellt Dämmung reingepackt Platten geschraubt.',
            "acts": ('Dämmung eingebaut',),
            "min_act": 1,
        },
        {
            "raw": 'Mit dem Kunden gesprochen er war zufrieden.',
            "acts": (),
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Spachtelarbeiten durchgeführt.',
            "acts": ('Spachtelarbeiten durchgeführt',),
            "min_act": 1,
        },
        {
            "raw": 'Staenderwerk montiert CW Profile gesetzt.',
            "acts": ('Ständerwerk montiert',),
            "min_act": 1,
        },
        {
            "raw": 'Decke abhaengen und GK Platten montiert Problem Lieferung Offen letzte Ecke.',
            "acts": ('Decke abgehängt', 'Gipskartonplatten montiert'),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Bauleitung informiert Wand fertig.',
            "acts": (),
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Doppelständerwand gebaut Schallschutz eingebaut.',
            "acts": ('Ständerwerk montiert',),
            "min_act": 1,
        },
        {
            "raw": 'Installationswand vorbereitet Unterkonstruktion montiert.',
            "acts": ('Installationswand vorbereitet unterkonstruktion montiert',),
            "min_act": 1,
        },
        {
            "raw": 'Fugenspachtel aufgetragen geschliffen grundiert.',
            "acts": ('Fugen verspachtelt',),
            "min_act": 1,
        },
        {
            "raw": 'Gipskartonplatten montiert Gipskartonplatten verarbeitet.',
            "acts": ('Gipskartonplatten montiert',),
            "mats": ('Gipskartonplatten',),
            "forbid_acts": ('Gipskartonplatten verarbeitet',),
            "min_act": 1,
            "mat_echo": True,
        },
        {
            "raw": 'Trockenbau komplett Wände Decke Spachtel Kundin zufrieden Problem Staub Offen Rest Freitag.',
            "acts": ('Spachtelarbeiten durchgeführt',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Nur Feierabend.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'Eine Wand zugemacht fertig.',
            "acts": ('Trockenbauwand geschlossen',),
            "min_act": 1,
        },
        {
            "raw": 'Abhangdecke montiert Lichtkuppel vorbereitet.',
            "acts": ('Decke abgehängt',),
            "min_act": 1,
        },
        {
            "raw": 'Brandschutz F90 Wand hergestellt.',
            "acts": ('Brandschutzwand hergestellt',),
            "min_act": 1,
        },
        {
            "raw": 'Dachausbau Rigips komplett montiert.',
            "acts": ('Gipskartonplatten montiert',),
            "min_act": 1,
        },
        {
            "raw": '12 Quadratmeter Gipskartonplatten montiert Problem Profile fehlen Offen morgen nachliefern.',
            "acts": ('Gipskartonplatten montiert', 'Ständerwerk montiert'),
            "mats": ('Gipskartonplatten',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '18 Quadratmeter Gipskartonplatten montiert Bauherr kurz informiert.',
            "acts": ('Gipskartonplatten montiert',),
            "mats": ('Gipskartonplatten',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '24 Quadratmeter Gipskartonplatten montiert Kundin sehr zufrieden.',
            "acts": ('Gipskartonplatten montiert',),
            "mats": ('Gipskartonplatten',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '30 Quadratmeter Gipskartonplatten montiert Auftraggeber da Problem Plan Offen Schacht.',
            "acts": ('Gipskartonplatten montiert',),
            "mats": ('Gipskartonplatten',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '36 Quadratmeter Gipskartonplatten montiert',
            "acts": ('Gipskartonplatten montiert',),
            "mats": ('Gipskartonplatten',),
            "min_act": 1,
        },
        {
            "raw": '44 Quadratmeter Gipskartonplatten montiert Problem Lieferung Offen Rest.',
            "acts": ('Gipskartonplatten montiert',),
            "mats": ('Gipskartonplatten',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '52 Quadratmeter Gipskartonplatten montiert mit dem Kunden gesprochen zufrieden.',
            "acts": ('Gipskartonplatten montiert',),
            "mats": ('Gipskartonplatten',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '60 Quadratmeter Gipskartonplatten montiert Bauleitung abgesprochen.',
            "acts": ('Gipskartonplatten montiert',),
            "mats": ('Gipskartonplatten',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '68 Quadratmeter Gipskartonplatten montiert Problem Schrauben Offen Wand.',
            "acts": ('Gipskartonplatten montiert',),
            "mats": ('Gipskartonplatten',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '76 Quadratmeter Gipskartonplatten montiert Kunde vor Ort.',
            "acts": ('Gipskartonplatten montiert',),
            "mats": ('Gipskartonplatten',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '84 Quadratmeter Gipskartonplatten montiert',
            "acts": ('Gipskartonplatten montiert',),
            "mats": ('Gipskartonplatten',),
            "min_act": 1,
        },
        {
            "raw": '92 Quadratmeter Gipskartonplatten montiert Problem Staub Offen Reinigung.',
            "acts": ('Gipskartonplatten montiert',),
            "mats": ('Gipskartonplatten',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '100 Quadratmeter Gipskartonplatten montiert Bauherr zufrieden.',
            "acts": ('Gipskartonplatten montiert',),
            "mats": ('Gipskartonplatten',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '108 Quadratmeter Gipskartonplatten montiert Kundengespräch gehabt.',
            "acts": ('Gipskartonplatten montiert',),
            "mats": ('Gipskartonplatten',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '116 Quadratmeter Gipskartonplatten montiert Problem Dämmung Offen Rest.',
            "acts": ('Gipskartonplatten montiert',),
            "mats": ('Gipskartonplatten',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '124 Quadratmeter Gipskartonplatten montiert Rücksprache mit Kunde.',
            "acts": ('Gipskartonplatten montiert',),
            "mats": ('Gipskartonplatten',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '132 Quadratmeter Gipskartonplatten montiert',
            "acts": ('Gipskartonplatten montiert',),
            "mats": ('Gipskartonplatten',),
            "min_act": 1,
        },
        {
            "raw": '140 Quadratmeter Gipskartonplatten montiert Problem Spachtel Offen Schliff.',
            "acts": ('Gipskartonplatten montiert',),
            "mats": ('Gipskartonplatten',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
    ],
    "Fliesen": [
        {
            "raw": 'Im Bad 25 Quadratmeter Fliesen verlegt Silikonfugen gemacht Problem Wasserdruck zu niedrig Offen Armatur morgen mit dem Kunden gesprochen er war zufrieden.',
            "acts": ('25 m² Fliesen verlegt', 'Silikonfugen'),
            "mats": ('Fliesen',),
            "problem": True,
            "open_": True,
            "customer": True,
            "cust_not": ('25', 'fliesen', 'bad'),
        },
        {
            "raw": '40 Quadratmeter Fliesen verlegt Fliesenkleber verwendet.',
            "acts": ('40 m² Fliesen verlegt', 'Fliesenkleber'),
            "mats": ('Fliesen', 'Fliesenkleber'),
        },
        {
            "raw": '35 qm Fliesen gelegt Fliesen verarbeitet.',
            "acts": ('35 m² Fliesen verlegt',),
            "mats": ('Fliesen',),
            "forbid_acts": ('Fliesen verarbeitet',),
            "mat_echo": True,
        },
        {
            "raw": 'WC montiert Waschbecken montiert.',
            "acts": ('WC montiert', 'Waschbecken montiert'),
            "min_act": 1,
        },
        {
            "raw": 'Im Bad erst Wandfliesen drauf geklebt Bodenfliesen verlegt verfugt Abdichtung Duschbereich Nivelliermasse gezogen Kunde meckert wegen Farbe Problem Wand schief Offen Rest Silikon Donnerstag.',
            "acts": ('Fliesen verlegt',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Wand grundiert Abdichtung hergestellt 40 Quadratmeter Fliesen verlegt verfugt Silikonfugen Kundin hat Farbe bestätigt Problem Untergrund uneben Offen Restfugen morgen.',
            "acts": ('40 m² Fliesen verlegt',),
            "mats": ('Fliesen',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Großformatfliesen verlegt Nivelliersystem verwendet.',
            "acts": ('Großformatfliesen verlegt',),
            "min_act": 1,
        },
        {
            "raw": 'Bodenablauf eingebaut Fliesen im Bad verlegt.',
            "acts": ('Bodenablauf eingebaut', 'Fliesen verlegt'),
            "min_act": 1,
        },
        {
            "raw": 'Naturstein verlegt und verfugt.',
            "acts": ('Naturstein verlegt',),
            "min_act": 1,
        },
        {
            "raw": 'Kundengespräch gehabt Fliesenmuster gewählt Problem Lieferung Offen Rest nächste Woche.',
            "acts": (),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'fliesen gelegt kleber gezogen verfugt fertig.',
            "acts": ('Fliesen verlegt', 'Fliesenkleber'),
            "min_act": 1,
        },
        {
            "raw": 'heute ich hab 22 quadrat fliesen im bad gemacht.',
            "acts": ('Fliesen verlegt',),
            "min_act": 1,
        },
        {
            "raw": 'Dusche fliesen Wand und Boden Abdichtung Silikon Kundin zufrieden Problem Fuge Offen Rest morgen.',
            "acts": (),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Mosaikfliesen gesetzt Wandfliesen verlegt.',
            "acts": ('Fliesen verlegt',),
            "min_act": 1,
        },
        {
            "raw": 'Nivelliermasse aufgetragen Fliesen verlegt.',
            "acts": ('Nivelliermasse aufgetragen', 'Fliesen verlegt'),
        },
        {
            "raw": 'Silikonfugen hergestellt im Bad.',
            "acts": ('Silikonfugen',),
            "min_act": 1,
        },
        {
            "raw": 'Mit dem Kunden gesprochen alles abgestimmt.',
            "acts": (),
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": '15 qm fliesen nur boden fertig.',
            "acts": ('Fliesen verlegt',),
            "min_act": 1,
        },
        {
            "raw": 'Bad komplett fertig fliesen verfugt silikon.',
            "acts": ('Fliesen verfugt',),
            "min_act": 1,
        },
        {
            "raw": 'Bauherr informiert Fliesenfarbe passt.',
            "acts": (),
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Abdichtung im Bad hergestellt.',
            "acts": ('Abdichtung hergestellt',),
            "min_act": 1,
        },
        {
            "raw": 'Fliesen im Flur und Bad verlegt.',
            "acts": ('Fliesen verlegt',),
            "min_act": 1,
        },
        {
            "raw": 'Problem Kleber härtet nicht Offen Wand neu machen Kunde informiert.',
            "acts": (),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'sockel fliesen gesetzt.',
            "acts": ('Fliesen verlegt',),
            "min_act": 1,
        },
        {
            "raw": 'Duschwanne eingebaut fliesen drum herum.',
            "acts": ('Dusche montiert',),
            "min_act": 1,
        },
        {
            "raw": '40 qm Fliesen verlegt Fliesenkleber aufgetragen Fliesen verarbeitet.',
            "acts": ('40 m² Fliesen verlegt',),
            "mats": ('Fliesen', 'Fliesenkleber'),
            "forbid_acts": ('Fliesen verarbeitet',),
            "mat_echo": True,
        },
        {
            "raw": 'Kunde war da und happy Problem Farbe Offen Muster.',
            "acts": (),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Feierabend.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'Nur verfugt heute.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'Spiegelfliesen montiert.',
            "acts": ('Spiegelfliesen montiert',),
            "min_act": 1,
        },
        {
            "raw": 'Balkonfliesen verlegt Gefälle eingebaut.',
            "acts": ('Fliesen verlegt',),
            "min_act": 1,
        },
        {
            "raw": 'Terrassenplatten verlegt.',
            "acts": ('Terrassenplatten verlegt',),
            "min_act": 1,
        },
        {
            "raw": '12 Quadratmeter Fliesen verlegt Problem Fuge. Offen Rest.',
            "acts": ('12 m² Fliesen verlegt',),
            "mats": ('Fliesen',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '16 Quadratmeter Fliesen verlegt Offen Rest.',
            "acts": ('16 m² Fliesen verlegt',),
            "mats": ('Fliesen',),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '20 Quadratmeter Fliesen verlegt Offen Rest. Kundin zufrieden.',
            "acts": ('20 m² Fliesen verlegt',),
            "mats": ('Fliesen',),
            "open_": True,
            "customer": True,
            "min_act": 1,
            "cust_not": ('fliesen', 'qm'),
        },
        {
            "raw": '24 Quadratmeter Fliesen verlegt Problem Fuge. Offen Rest.',
            "acts": ('24 m² Fliesen verlegt',),
            "mats": ('Fliesen',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '28 Quadratmeter Fliesen verlegt Offen Rest.',
            "acts": ('28 m² Fliesen verlegt',),
            "mats": ('Fliesen',),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '32 Quadratmeter Fliesen verlegt Offen Rest.',
            "acts": ('32 m² Fliesen verlegt',),
            "mats": ('Fliesen',),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '36 Quadratmeter Fliesen verlegt Problem Fuge. Offen Rest.',
            "acts": ('36 m² Fliesen verlegt',),
            "mats": ('Fliesen',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '44 Quadratmeter Fliesen verlegt Offen Rest.',
            "acts": ('44 m² Fliesen verlegt',),
            "mats": ('Fliesen',),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '48 Quadratmeter Fliesen verlegt Problem Fuge. Offen Rest.',
            "acts": ('48 m² Fliesen verlegt',),
            "mats": ('Fliesen',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '52 Quadratmeter Fliesen verlegt Offen Rest.',
            "acts": ('52 m² Fliesen verlegt',),
            "mats": ('Fliesen',),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '56 Quadratmeter Fliesen verlegt Offen Rest.',
            "acts": ('56 m² Fliesen verlegt',),
            "mats": ('Fliesen',),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '64 Quadratmeter Fliesen verlegt Offen Rest.',
            "acts": ('64 m² Fliesen verlegt',),
            "mats": ('Fliesen',),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '72 Quadratmeter Fliesen verlegt Problem Fuge. Offen Rest.',
            "acts": ('72 m² Fliesen verlegt',),
            "mats": ('Fliesen',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '80 Quadratmeter Fliesen verlegt Offen Rest. Kundin zufrieden.',
            "acts": ('80 m² Fliesen verlegt',),
            "mats": ('Fliesen',),
            "open_": True,
            "customer": True,
            "min_act": 1,
            "cust_not": ('fliesen', 'qm'),
        },
        {
            "raw": '88 Quadratmeter Fliesen verlegt Offen Rest.',
            "acts": ('88 m² Fliesen verlegt',),
            "mats": ('Fliesen',),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '96 Quadratmeter Fliesen verlegt Problem Fuge. Offen Rest.',
            "acts": ('96 m² Fliesen verlegt',),
            "mats": ('Fliesen',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '104 Quadratmeter Fliesen verlegt Offen Rest.',
            "acts": ('104 m² Fliesen verlegt',),
            "mats": ('Fliesen',),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '112 Quadratmeter Fliesen verlegt Offen Rest.',
            "acts": ('112 m² Fliesen verlegt',),
            "mats": ('Fliesen',),
            "open_": True,
            "min_act": 1,
        },
    ],
    "SHK": [
        {
            "raw": '40 laufende Meter KG-Rohre verlegt HT-Manschette montiert Problem Anschluss undicht Offen Druckprüfung morgen Kunde informiert war einverstanden.',
            "acts": ('KG-Rohre verlegt', 'HT-Manschette montiert'),
            "problem": True,
            "open_": True,
            "customer": True,
            "cust_not": ('kg', 'rohr', 'manschette'),
        },
        {
            "raw": 'Heizkörper montiert Thermostatventile eingebaut Problem Umlauf Offen hydraulischer Abgleich mit dem Kunden gesprochen zufrieden.',
            "acts": ('Heizkörper montiert',),
            "problem": True,
            "open_": True,
            "customer": True,
            "cust_not": ('heizkörper',),
        },
        {
            "raw": 'Dusche montiert Armaturen montiert Kundin sehr zufrieden.',
            "acts": ('Dusche montiert', 'Armaturen montiert'),
            "customer": True,
            "cust_not": ('dusche', 'armatur'),
        },
        {
            "raw": 'Druckprüfung durchgeführt.',
            "acts": ('Druckprüfung durchgeführt',),
            "min_act": 1,
        },
        {
            "raw": 'Morgens 20 laufende Meter KG-Rohre DN 160 verlegt HT-Rohre DN 50 verlegt drei Heizkörper montiert WC gesetzt Waschbecken montiert Druckprüfung durchgeführt Bauleitung kurz da Problem KG-Bogen fehlte Offen Bogen morgen nach dem Kundengespräch Feierabend.',
            "acts": ('KG-Rohre', 'Heizkörper montiert', 'WC montiert', 'Waschbecken montiert', 'Druckprüfung durchgeführt'),
            "mats": ('KG-Rohre',),
            "problem": True,
            "open_": True,
            "customer": True,
        },
        {
            "raw": 'Wasserleitungen verlegt Fußbodenheizung verlegt hydraulischen Abgleich durchgeführt.',
            "acts": ('Wasserleitungen verlegt', 'Fußbodenheizung verlegt', 'Hydraulischer Abgleich durchgeführt'),
        },
        {
            "raw": 'WC montiert Waschbecken montiert Dusche montiert.',
            "acts": ('WC montiert', 'Waschbecken montiert', 'Dusche montiert'),
            "min_act": 1,
        },
        {
            "raw": '20 laufende Meter KG-Rohre verlegt vier Heizkörper montiert WC gesetzt Druckprüfung durchgeführt Bauherr zufrieden Problem Lieferung spät Offen Rest Sanitär nächste Woche.',
            "acts": ('KG-Rohre verlegt', 'Heizkörper montiert', 'WC montiert', 'Druckprüfung durchgeführt'),
            "problem": True,
            "open_": True,
            "customer": True,
        },
        {
            "raw": 'Heizungsanschlüsse montiert Thermostatventile eingebaut.',
            "acts": ('Heizungsanschlüsse montiert',),
            "min_act": 1,
        },
        {
            "raw": 'Kundengespräch gehabt Heizungsplan besprochen Problem Material fehlt Offen Rest nächste Woche.',
            "acts": (),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'rohre gelegt heizung angeschlossen fertig.',
            "acts": ('Heizungsanschlüsse montiert', 'Wasserleitungen verlegt'),
            "min_act": 1,
        },
        {
            "raw": 'heute ich hab kg rohre 15 meter verlegt.',
            "acts": ('KG-Rohre verlegt',),
            "min_act": 1,
        },
        {
            "raw": 'HT-Rohre verlegt HT-Manschette montiert Problem Dichtung Offen Prüfung morgen.',
            "acts": ('HT-Rohre verlegt', 'HT-Manschette montiert'),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Wärmepumpe installiert Heizungsanschlüsse montiert.',
            "acts": ('Wärmepumpe installiert', 'Heizungsanschlüsse montiert'),
            "min_act": 1,
        },
        {
            "raw": 'Gastherme eingebaut Abgasanlage montiert.',
            "acts": ('Wärmepumpe installiert',),
            "min_act": 1,
        },
        {
            "raw": 'Mit dem Kunden gesprochen er war einverstanden.',
            "acts": (),
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Bodenablauf eingebaut HT-Rohr angeschlossen.',
            "acts": ('Bodenablauf eingebaut',),
            "min_act": 1,
        },
        {
            "raw": 'Rücklaufverschraubung montiert Heizkörper eingebaut.',
            "acts": ('Heizkörper montiert',),
            "min_act": 1,
        },
        {
            "raw": 'Problem undichtes Rohr Druckprüfung verschoben Kundengespräch gehabt Offen morgen nacharbeiten.',
            "acts": (),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Armaturen montiert Waschbecken angeschlossen.',
            "acts": ('Armaturen montiert', 'Waschbecken montiert'),
        },
        {
            "raw": 'Abwasser HT-Rohre 12 laufende Meter verlegt Wasserleitungen angeschlossen Rücksprache mit Kunde Problem Manschette undicht Offen morgen tauschen.',
            "acts": ('HT-Rohre verlegt',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Hydraulischer Abgleich durchgeführt.',
            "acts": ('Hydraulischer Abgleich durchgeführt',),
            "min_act": 1,
        },
        {
            "raw": 'WC und Waschbecken komplett montiert.',
            "acts": ('Waschbecken montiert',),
            "min_act": 1,
        },
        {
            "raw": 'Heizkessel angeschlossen Vorlauf Rücklauf montiert.',
            "acts": ('Wärmepumpe installiert',),
            "min_act": 1,
        },
        {
            "raw": 'Kunde informiert alles ok.',
            "acts": (),
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Feierabend.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'Nur Druckprüfung heute.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'Dusche komplett montiert Abdichtung geprüft.',
            "acts": ('Dusche montiert',),
            "min_act": 1,
        },
        {
            "raw": 'Fußbodenheizung verlegt Verteiler angeschlossen.',
            "acts": ('Fußbodenheizung verlegt',),
            "min_act": 1,
        },
        {
            "raw": 'Kanalanschluss hergestellt KG-Rohre verlegt.',
            "acts": ('KG-Rohre verlegt',),
            "min_act": 1,
        },
        {
            "raw": 'Sanitär komplett Bad montiert WC Waschbecken Dusche Kundin sehr zufrieden Problem Armatur Offen morgen.',
            "acts": ('Sanitär komplett bad montiert',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Rohrleitungen verlegt Fittings verbaut.',
            "acts": ('Wasserleitungen verlegt',),
            "min_act": 1,
        },
        {
            "raw": '8 laufende Meter KG-Rohre verlegt Offen morgen.',
            "acts": ('8 lfm KG-Rohre verlegt',),
            "mats": ('KG-Rohre',),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '12 laufende Meter KG-Rohre verlegt Problem Bogen fehlt.',
            "acts": ('12 lfm KG-Rohre verlegt',),
            "mats": ('KG-Rohre',),
            "problem": True,
            "min_act": 1,
        },
        {
            "raw": '16 laufende Meter KG-Rohre verlegt Offen morgen.',
            "acts": ('16 lfm KG-Rohre verlegt',),
            "mats": ('KG-Rohre',),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '20 laufende Meter KG-Rohre verlegt Bauherr zufrieden.',
            "acts": ('20 lfm KG-Rohre verlegt',),
            "mats": ('KG-Rohre',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '24 laufende Meter KG-Rohre verlegt Problem Bogen fehlt. Offen morgen.',
            "acts": ('24 lfm KG-Rohre verlegt',),
            "mats": ('KG-Rohre',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '28 laufende Meter KG-Rohre verlegt',
            "acts": ('28 lfm KG-Rohre verlegt',),
            "mats": ('KG-Rohre',),
            "min_act": 1,
        },
        {
            "raw": '32 laufende Meter KG-Rohre verlegt Offen morgen.',
            "acts": ('32 lfm KG-Rohre verlegt',),
            "mats": ('KG-Rohre',),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '36 laufende Meter KG-Rohre verlegt Problem Bogen fehlt.',
            "acts": ('36 lfm KG-Rohre verlegt',),
            "mats": ('KG-Rohre',),
            "problem": True,
            "min_act": 1,
        },
        {
            "raw": '40 laufende Meter KG-Rohre verlegt Offen morgen. Bauherr zufrieden.',
            "acts": ('40 lfm KG-Rohre verlegt',),
            "mats": ('KG-Rohre',),
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '44 laufende Meter KG-Rohre verlegt',
            "acts": ('44 lfm KG-Rohre verlegt',),
            "mats": ('KG-Rohre',),
            "min_act": 1,
        },
        {
            "raw": '48 laufende Meter KG-Rohre verlegt Problem Bogen fehlt. Offen morgen.',
            "acts": ('48 lfm KG-Rohre verlegt',),
            "mats": ('KG-Rohre',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '52 laufende Meter KG-Rohre verlegt',
            "acts": ('KG-Rohre verlegt',),
            "mats": ('KG-Rohre',),
            "min_act": 1,
        },
        {
            "raw": '56 laufende Meter KG-Rohre verlegt Offen morgen.',
            "acts": ('KG-Rohre verlegt',),
            "mats": ('KG-Rohre',),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '60 laufende Meter KG-Rohre verlegt Problem Bogen fehlt. Bauherr zufrieden.',
            "acts": ('KG-Rohre verlegt',),
            "mats": ('KG-Rohre',),
            "problem": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '64 laufende Meter KG-Rohre verlegt Offen morgen.',
            "acts": ('KG-Rohre verlegt',),
            "mats": ('KG-Rohre',),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '68 laufende Meter KG-Rohre verlegt',
            "acts": ('KG-Rohre verlegt',),
            "mats": ('KG-Rohre',),
            "min_act": 1,
        },
        {
            "raw": '72 laufende Meter KG-Rohre verlegt Problem Bogen fehlt. Offen morgen.',
            "acts": ('KG-Rohre verlegt',),
            "mats": ('KG-Rohre',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '76 laufende Meter KG-Rohre verlegt',
            "acts": ('KG-Rohre verlegt',),
            "mats": ('KG-Rohre',),
            "min_act": 1,
        },
    ],
    "Hochbau": [
        {
            "raw": 'Fundament betoniert Schalung erstellt Problem Wetter Offen Bewehrung Montag Bauleitung informiert.',
            "acts": ('Fundament erstellt', 'Schalung erstellt'),
            "problem": True,
            "open_": True,
            "customer": True,
            "cust_not": ('fundament', 'beton', 'schalung'),
        },
        {
            "raw": 'Mauerwerk erstellt Bewehrung eingebaut.',
            "acts": ('Mauerwerk erstellt', 'Bewehrung eingebaut'),
        },
        {
            "raw": 'Filigrandecke montiert Fußbodenheizung verlegt.',
            "acts": ('Filigrandecke montiert', 'Fußbodenheizung verlegt'),
        },
        {
            "raw": 'heute beton gegossen problem regen offen rest morgen kunde gred war ok',
            "acts": ('Beton eingebracht',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Fundamentplatte geschalt 15er Poroton hochgemauert Bewehrungsstahl gebunden 8 Kubikmeter Beton gegossen Schalung abgebaut Bauherr zufrieden Problem Frost Offen Nachbehandlung.',
            "acts": ('Schalung erstellt', 'Mauerwerk erstellt', 'Bewehrung eingebaut', 'Beton eingebracht'),
            "mats": ('Beton',),
            "problem": True,
            "open_": True,
            "customer": True,
        },
        {
            "raw": 'Erdarbeiten gemacht Schalung gestellt Betondecke gegossen Fundament erstellt.',
            "acts": ('Erdarbeiten durchgeführt', 'Schalung erstellt', 'Beton eingebracht', 'Fundament erstellt'),
        },
        {
            "raw": '11,5er Poroton gemauert.',
            "acts": ('Mauerwerk erstellt',),
            "min_act": 1,
        },
        {
            "raw": '5 Kubik Beton gegossen fertig.',
            "acts": ('Beton eingebracht',),
            "min_act": 1,
        },
        {
            "raw": 'Schalung erstellt Bewehrung eingebaut Beton eingebracht.',
            "acts": ('Schalung erstellt', 'Bewehrung eingebaut', 'Beton eingebracht'),
            "mats": ('Beton',),
        },
        {
            "raw": 'Kundengespräch gehabt Bauplan besprochen Problem Material Offen Rest Woche.',
            "acts": (),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'mauer gebaut beton gemacht.',
            "acts": ('Mauerwerk erstellt', 'Beton eingebracht'),
            "min_act": 1,
        },
        {
            "raw": 'heute ich hab 20 quadrat mauerwerk gemacht.',
            "acts": ('Mauerwerk erstellt',),
            "min_act": 1,
        },
        {
            "raw": 'Decke betoniert Schalung gestellt Problem Regen Offen Abbinden.',
            "acts": ('Schalung erstellt',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Stürze gesetzt Fensteröffnungen gemauert.',
            "acts": ('Stürze gesetzt fensteröffnungen gebaut',),
            "min_act": 1,
        },
        {
            "raw": 'Bewehrung gebunden für Decke.',
            "acts": ('Bewehrung eingebaut',),
            "min_act": 1,
        },
        {
            "raw": 'Mit dem Kunden gesprochen zufrieden.',
            "acts": (),
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Fundament erstellt Erdarbeiten durchgeführt.',
            "acts": ('Fundament erstellt', 'Erdarbeiten durchgeführt'),
        },
        {
            "raw": 'Beton eingebracht Beton verarbeitet.',
            "acts": ('Beton eingebracht',),
            "mats": ('Beton',),
            "forbid_acts": ('Beton verarbeitet',),
            "mat_echo": True,
        },
        {
            "raw": 'Auftraggeber kurz gesprochen.',
            "acts": (),
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Feierabend.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'Nur Schalung heute.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'Ringanker betoniert.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'Mauerwerk 17,5er KS hochgezogen.',
            "acts": ('Mauerwerk erstellt',),
            "min_act": 1,
        },
        {
            "raw": 'Bodenplatte geschalt bewehrt betoniert Problem Lieferung Offen Rest.',
            "acts": (),
            "problem": True,
            "open_": True,
            "min_act": 0,
        },
        {
            "raw": 'Bauherr zufrieden Mauerwerk fertig.',
            "acts": ('Mauerwerk erstellt',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Filigrandecke montiert.',
            "acts": ('Filigrandecke montiert',),
            "min_act": 1,
        },
        {
            "raw": 'Treppenhaus mauern Stürze setzen.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'Bewehrung Decke komplett.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": '8 Kubik Beton gegossen Schalung steht Problem Hitze Offen Nachbehandlung Plane.',
            "acts": ('Beton eingebracht',),
            "mats": ('Beton',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Rohbau EG fertig Kundin informiert.',
            "acts": (),
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Erdung Fundamenterder gesetzt.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'Balkonplatte geschalt betoniert.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": '3 Kubikmeter Beton eingebracht Problem Wetter.',
            "acts": ('3 m³ Beton eingebracht',),
            "mats": ('Beton',),
            "problem": True,
            "min_act": 1,
        },
        {
            "raw": '4 Kubikmeter Beton eingebracht Offen Rest.',
            "acts": ('4 m³ Beton eingebracht',),
            "mats": ('Beton',),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '5 Kubikmeter Beton eingebracht Bauleitung informiert.',
            "acts": ('5 m³ Beton eingebracht',),
            "mats": ('Beton',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '6 Kubikmeter Beton eingebracht Problem Wetter.',
            "acts": ('6 m³ Beton eingebracht',),
            "mats": ('Beton',),
            "problem": True,
            "min_act": 1,
        },
        {
            "raw": '7 Kubikmeter Beton eingebracht',
            "acts": ('7 m³ Beton eingebracht',),
            "mats": ('Beton',),
            "min_act": 1,
        },
        {
            "raw": '8 Kubikmeter Beton eingebracht Offen Rest.',
            "acts": ('8 m³ Beton eingebracht',),
            "mats": ('Beton',),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '9 Kubikmeter Beton eingebracht Problem Wetter.',
            "acts": ('9 m³ Beton eingebracht',),
            "mats": ('Beton',),
            "problem": True,
            "min_act": 1,
        },
        {
            "raw": '10 Kubikmeter Beton eingebracht Bauleitung informiert.',
            "acts": ('10 m³ Beton eingebracht',),
            "mats": ('Beton',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '11 Kubikmeter Beton eingebracht',
            "acts": ('11 m³ Beton eingebracht',),
            "mats": ('Beton',),
            "min_act": 1,
        },
        {
            "raw": '12 Kubikmeter Beton eingebracht Problem Wetter. Offen Rest.',
            "acts": ('12 m³ Beton eingebracht',),
            "mats": ('Beton',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '13 Kubikmeter Beton eingebracht',
            "acts": ('13 m³ Beton eingebracht',),
            "mats": ('Beton',),
            "min_act": 1,
        },
        {
            "raw": '14 Kubikmeter Beton eingebracht',
            "acts": ('14 m³ Beton eingebracht',),
            "mats": ('Beton',),
            "min_act": 1,
        },
        {
            "raw": '15 Kubikmeter Beton eingebracht Problem Wetter. Bauleitung informiert.',
            "acts": ('15 m³ Beton eingebracht',),
            "mats": ('Beton',),
            "problem": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '16 Kubikmeter Beton eingebracht Offen Rest.',
            "acts": ('Beton eingebracht',),
            "mats": ('Beton',),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '17 Kubikmeter Beton eingebracht',
            "acts": ('Beton eingebracht',),
            "mats": ('Beton',),
            "min_act": 1,
        },
        {
            "raw": '18 Kubikmeter Beton eingebracht Problem Wetter.',
            "acts": ('Beton eingebracht',),
            "mats": ('Beton',),
            "problem": True,
            "min_act": 1,
        },
        {
            "raw": '19 Kubikmeter Beton eingebracht',
            "acts": ('Beton eingebracht',),
            "mats": ('Beton',),
            "min_act": 1,
        },
        {
            "raw": '20 Kubikmeter Beton eingebracht Offen Rest. Bauleitung informiert.',
            "acts": ('Beton eingebracht',),
            "mats": ('Beton',),
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
    ],
    "Tiefbau": [
        {
            "raw": 'Graben ausgehoben Kanalrohre verlegt Problem Leitung Offen Verfüllung morgen Auftraggeber kurz gesprochen.',
            "acts": ('Graben ausgehoben',),
            "problem": True,
            "open_": True,
            "customer": True,
            "cust_not": ('graben', 'kanal'),
        },
        {
            "raw": 'Asphalt eingebaut Untergrund verdichtet Problem Maschine Offen letzte Bahn.',
            "acts": ('Asphalt eingebaut', 'Untergrund verdichtet'),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Verbau gesetzt Spundwand eingebaut.',
            "acts": ('Verbau gesetzt',),
            "min_act": 1,
        },
        {
            "raw": 'Hausanschluss hergestellt Problem Wasserdruck Offen Anmeldung Kunde zufrieden.',
            "acts": ('Hausanschluss hergestellt',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Erdaushub gemacht 22 laufende Meter KG Rohre DN 125 verlegt Splittschicht reingepackt Graben verfüllt Planum verdichtet Auftraggeber informiert Problem Material knapp Offen Rest morgen.',
            "acts": ('Graben ausgehoben', 'KG-Rohre', 'Splitt eingebaut', 'Graben verfüllt', 'Untergrund verdichtet'),
            "mats": ('KG-Rohre',),
            "problem": True,
            "open_": True,
            "customer": True,
        },
        {
            "raw": 'Baugrube ausgehoben Kanal angeschlossen Drainage verlegt Leitungstrasse angelegt.',
            "acts": ('Graben ausgehoben', 'Kanal-/Schachtarbeiten durchgeführt', 'Drainage/Entwässerung eingebaut', 'Leitungstrasse hergestellt'),
        },
        {
            "raw": 'Sand reingepackt und verdichtet.',
            "acts": ('Sand eingebaut', 'Untergrund verdichtet'),
        },
        {
            "raw": '15 Meter KG verlegt fertig.',
            "acts": ('KG-Rohre',),
            "min_act": 1,
        },
        {
            "raw": 'Erdaushub gemacht 22 laufende Meter KG Rohre verlegt Splittschicht Graben verfüllt Hausanschluss vorbereitet Auftraggeber da Problem Plan fehlt Offen Schacht setzen.',
            "acts": ('Graben ausgehoben', 'KG-Rohre'),
            "mats": ('KG-Rohre',),
            "problem": True,
            "open_": True,
            "customer": True,
        },
        {
            "raw": 'Kundengespräch gehabt Trassenplan besprochen Problem Genehmigung Offen Rest.',
            "acts": (),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'graben gezogen boden verdichtet.',
            "acts": ('Graben ausgehoben', 'Untergrund verdichtet'),
            "min_act": 1,
        },
        {
            "raw": 'heute ich hab 18 meter kg rohre verlegt.',
            "acts": ('KG-Rohre verlegt',),
            "min_act": 1,
        },
        {
            "raw": 'Kanalisation angeschlossen Schacht gesetzt Problem Rohr Offen morgen.',
            "acts": ('Kanal-/Schachtarbeiten durchgeführt',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Asphaltdecke eingebaut Tragschicht verdichtet.',
            "acts": ('Asphalt eingebaut',),
            "min_act": 1,
        },
        {
            "raw": 'Leitungstrasse hergestellt Kies eingebaut.',
            "acts": ('Leitungstrasse hergestellt',),
            "min_act": 1,
        },
        {
            "raw": 'Mit dem Kunden gesprochen einverstanden.',
            "acts": (),
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Spundwand gezogen Verbau gesetzt.',
            "acts": ('Verbau gesetzt',),
            "min_act": 1,
        },
        {
            "raw": 'Drainage verlegt Kies drumherum.',
            "acts": ('Drainage/Entwässerung eingebaut',),
            "min_act": 1,
        },
        {
            "raw": 'Bauherr zufrieden Graben fertig.',
            "acts": ('Graben ausgehoben',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Feierabend.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'Nur verdichten heute.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'Hausanschluss Wasser und Abwasser.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'Straßenausbau Asphalt eingebaut Problem Temperatur Offen letzte Bahn.',
            "acts": ('Asphalt eingebaut',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Rücksprache mit Kunde Trasse besprochen.',
            "acts": (),
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'KG Schacht gesetzt Rohre angeschlossen.',
            "acts": ('Kanal-/Schachtarbeiten durchgeführt',),
            "min_act": 1,
        },
        {
            "raw": 'Erdaushub 50 Kubik Aushub entsorgt.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'Frostschutz eingebaut Planum verdichtet.',
            "acts": ('Untergrund verdichtet',),
            "min_act": 1,
        },
        {
            "raw": 'Bodenaustausch gemacht Schotter eingebaut.',
            "acts": ('Schotter eingebaut',),
            "mats": ('Schotter',),
            "min_act": 1,
        },
        {
            "raw": 'Komplett Tag Graben KG verfüllen verdichten Auftraggeber informiert Problem Leitung Offen morgen.',
            "acts": ('Graben verfüllt',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'HT-Rohre im Graben verlegt.',
            "acts": ('HT-Rohre verlegt',),
            "min_act": 1,
        },
        {
            "raw": 'Baugrube ausgehoben gesichert.',
            "acts": ('Graben ausgehoben',),
            "min_act": 1,
        },
        {
            "raw": 'Kanal TV-Inspektion vorbereitet.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": '10 laufende Meter KG-Rohre verlegt Graben verfüllt Problem Rohr.',
            "acts": ('KG-Rohre verlegt', 'Graben verfüllt'),
            "mats": ('KG-Rohre',),
            "problem": True,
            "min_act": 1,
        },
        {
            "raw": '14 laufende Meter KG-Rohre verlegt Graben verfüllt Offen Verfüllung.',
            "acts": ('KG-Rohre verlegt', 'Graben verfüllt'),
            "mats": ('KG-Rohre',),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '18 laufende Meter KG-Rohre verlegt Graben verfüllt Auftraggeber da.',
            "acts": ('KG-Rohre verlegt', 'Graben verfüllt'),
            "mats": ('KG-Rohre',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '22 laufende Meter KG-Rohre verlegt Graben verfüllt',
            "acts": ('KG-Rohre verlegt', 'Graben verfüllt'),
            "mats": ('KG-Rohre',),
            "min_act": 1,
        },
        {
            "raw": '26 laufende Meter KG-Rohre verlegt Graben verfüllt',
            "acts": ('KG-Rohre verlegt', 'Graben verfüllt'),
            "mats": ('KG-Rohre',),
            "min_act": 1,
        },
        {
            "raw": '30 laufende Meter KG-Rohre verlegt Graben verfüllt Problem Rohr.',
            "acts": ('KG-Rohre verlegt', 'Graben verfüllt'),
            "mats": ('KG-Rohre',),
            "problem": True,
            "min_act": 1,
        },
        {
            "raw": '34 laufende Meter KG-Rohre verlegt Graben verfüllt',
            "acts": ('KG-Rohre verlegt', 'Graben verfüllt'),
            "mats": ('KG-Rohre',),
            "min_act": 1,
        },
        {
            "raw": '38 laufende Meter KG-Rohre verlegt Graben verfüllt',
            "acts": ('KG-Rohre verlegt', 'Graben verfüllt'),
            "mats": ('KG-Rohre',),
            "min_act": 1,
        },
        {
            "raw": '42 laufende Meter KG-Rohre verlegt Graben verfüllt Offen Verfüllung.',
            "acts": ('KG-Rohre verlegt', 'Graben verfüllt'),
            "mats": ('KG-Rohre',),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '46 laufende Meter KG-Rohre verlegt Graben verfüllt',
            "acts": ('KG-Rohre verlegt', 'Graben verfüllt'),
            "mats": ('KG-Rohre',),
            "min_act": 1,
        },
        {
            "raw": '50 laufende Meter KG-Rohre verlegt Graben verfüllt Problem Rohr.',
            "acts": ('KG-Rohre verlegt', 'Graben verfüllt'),
            "mats": ('KG-Rohre',),
            "problem": True,
            "min_act": 1,
        },
        {
            "raw": '54 laufende Meter KG-Rohre verlegt Graben verfüllt Auftraggeber da.',
            "acts": ('KG-Rohre verlegt', 'Graben verfüllt'),
            "mats": ('KG-Rohre',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '58 laufende Meter KG-Rohre verlegt Graben verfüllt',
            "acts": ('KG-Rohre verlegt', 'Graben verfüllt'),
            "mats": ('KG-Rohre',),
            "min_act": 1,
        },
        {
            "raw": '62 laufende Meter KG-Rohre verlegt Graben verfüllt',
            "acts": ('KG-Rohre verlegt', 'Graben verfüllt'),
            "mats": ('KG-Rohre',),
            "min_act": 1,
        },
        {
            "raw": '66 laufende Meter KG-Rohre verlegt Graben verfüllt',
            "acts": ('KG-Rohre verlegt', 'Graben verfüllt'),
            "mats": ('KG-Rohre',),
            "min_act": 1,
        },
        {
            "raw": '70 laufende Meter KG-Rohre verlegt Graben verfüllt Problem Rohr. Offen Verfüllung.',
            "acts": ('KG-Rohre verlegt', 'Graben verfüllt'),
            "mats": ('KG-Rohre',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '74 laufende Meter KG-Rohre verlegt Graben verfüllt',
            "acts": ('KG-Rohre verlegt', 'Graben verfüllt'),
            "mats": ('KG-Rohre',),
            "min_act": 1,
        },
        {
            "raw": '78 laufende Meter KG-Rohre verlegt Graben verfüllt',
            "acts": ('KG-Rohre verlegt', 'Graben verfüllt'),
            "mats": ('KG-Rohre',),
            "min_act": 1,
        },
    ],
    "Putz": [
        {
            "raw": '120 Quadratmeter Außenputz aufgetragen Grundierung aufgetragen Problem Gerüst zu spät Offen Sockel nächste Woche Bauherr kurz informiert alles abgestimmt.',
            "acts": ('Außenputz aufgetragen', 'Grundierung aufgetragen'),
            "problem": True,
            "open_": True,
            "customer": True,
            "cust_not": ('120', 'putz', 'm²'),
        },
        {
            "raw": '80 qm Putz aufgetragen Putz verarbeitet.',
            "acts": ('Putz aufgebracht',),
            "mats": ('Putz',),
            "sum_forbid": ('Putz verarbeitet',),
            "mat_echo": True,
        },
        {
            "raw": 'WDVS gedämmt Fassadenarmierung ausgeführt.',
            "acts": ('WDVS ausgeführt',),
            "min_act": 1,
            "min_act": 1,
        },
        {
            "raw": 'Stuck geschlagen Gesims hergestellt Problem Form Offen Rest Freitag.',
            "acts": ('Stuckarbeiten',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'WDVS Platten angeklebt Armierungsgewebe eingebettet Reibputz drauf gemacht Sockelleiste stucken Kunde informiert Problem Kleber knapp Offen Rest morgen.',
            "acts": ('WDVS ausgeführt', 'Armierung ausgeführt', 'Reibputz aufgetragen'),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Fassade gedämmt Gewebe reingemacht Außenputz aufgetragen Gesims stuckiert.',
            "acts": ('WDVS ausgeführt', 'Fassadenarmierung ausgeführt', 'Außenputz aufgetragen'),
        },
        {
            "raw": 'Unterputz aufgetragen Oberputz aufgetragen.',
            "acts": ('Unterputz aufgetragen', 'Oberputz aufgetragen'),
        },
        {
            "raw": 'Sanierputz aufgetragen Altputz entfernt.',
            "acts": ('Sanierputz aufgebracht', 'Altputz entfernt'),
            "mats": ('Sanierputz',),
            "min_act": 2,
        },
        {
            "raw": 'Schimmelbefall behandelt Sanierputz aufgebracht.',
            "acts": ('Sanierputz aufgebracht', 'Schimmel beseitigt'),
            "min_act": 1,
        },
        {
            "raw": 'Kundengespräch gehabt Putzfarbe besprochen Problem Lieferung Offen Rest.',
            "acts": (),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'putz drauf gemacht grundierung gemacht.',
            "acts": ('Grundierung aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": 'heute ich hab 60 quadrat aussenputz gemacht.',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": 'Innenputz Küche und Flur aufgetragen Kundin zufrieden Problem Riss Offen Nacharbeit.',
            "acts": ('Innenputz aufgetragen',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Sockelputz aufgetragen Reibputz Fassade.',
            "acts": ('Sockelputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": 'Kratzputz aufgetragen Grundierung vorher.',
            "acts": ('Kratzputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": 'Mit dem Kunden gesprochen die Farbe wurde abgestimmt.',
            "acts": (),
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Stuckarbeiten Gesims Fenster.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'WDVS komplett gedämmt armiert putz.',
            "acts": ('WDVS ausgeführt',),
            "min_act": 1,
        },
        {
            "raw": 'Bauherr zufrieden Fassade fertig.',
            "acts": (),
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Feierabend.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'Nur Grundierung heute.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'Abdichtung Kellerwand hergestellt.',
            "acts": ('Abdichtung hergestellt',),
            "min_act": 1,
        },
        {
            "raw": 'Außenputz zweiter Anstrich.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'Problem Gerüst rutscht Offen Sicherung Kunde informiert.',
            "acts": (),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Risse geschlossen Spachtelgrund aufgetragen.',
            "acts": ('Risse geschlossen spachtelgrund aufgebracht',),
            "min_act": 1,
        },
        {
            "raw": 'Stuck stuckiert Decke Zierleiste.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "min_act": 1,
        },
        {
            "raw": 'Fassadenarmierung ausgeführt WDVS.',
            "acts": ('Fassadenarmierung ausgeführt',),
            "min_act": 1,
        },
        {
            "raw": 'Innenputz Bad aufgetragen.',
            "acts": ('Innenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": '100 qm Putz Außen Kunde meckert wegen Farbe Problem Ton Offen Muster.',
            "acts": (),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Oberputz aufgetragen Oberputz verarbeitet.',
            "acts": ('Oberputz aufgetragen',),
            "mats": ('Oberputz',),
            "sum_forbid": ('Oberputz verarbeitet',),
            "mat_echo": True,
        },
        {
            "raw": 'Rücksprache mit Kunde Putzplan.',
            "acts": (),
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Laibungen putz fertig.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": '25 Quadratmeter Außenputz aufgetragen',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": '35 Quadratmeter Außenputz aufgetragen',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": '45 Quadratmeter Außenputz aufgetragen',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": '55 Quadratmeter Außenputz aufgetragen',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": '65 Quadratmeter Außenputz aufgetragen',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": '75 Quadratmeter Außenputz aufgetragen',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": '85 Quadratmeter Außenputz aufgetragen',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": '95 Quadratmeter Außenputz aufgetragen',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": '105 Quadratmeter Außenputz aufgetragen',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": '115 Quadratmeter Außenputz aufgetragen',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": '125 Quadratmeter Außenputz aufgetragen',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": '135 Quadratmeter Außenputz aufgetragen',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": '145 Quadratmeter Außenputz aufgetragen',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": '155 Quadratmeter Außenputz aufgetragen',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": '165 Quadratmeter Außenputz aufgetragen',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": '175 Quadratmeter Außenputz aufgetragen',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": '185 Quadratmeter Außenputz aufgetragen',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": '195 Quadratmeter Außenputz aufgetragen',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
    ],
}


def all_base_scenarios() -> list[tuple[str, dict]]:
    """Liefert (trade, scenario_dict) für alle 350 Basisszenarien."""
    out: list[tuple[str, dict]] = []
    for trade, items in TRADE_SCENARIOS.items():
        if len(items) != 50:
            raise ValueError(f"{trade}: erwartet 50, got {len(items)}")
        for item in items:
            out.append((trade, item))
    return out
