"""Pilot Real-Speech Welle 51 — 40 Basisszenarien (Diktat-Muster Session 11.07.)."""

from __future__ import annotations


def all_base_scenarios() -> list[dict]:
    return [
        {
            "raw": 'Oh hab ich gemacht heute die Bagger mit Lock hab ich gemacht dann drei Kubik Schotter 32 danach ich hab gemacht Split ungefähr zwei Kubik dann hat viel geregnet Arbeit stopp',
            "act_tokens": ('schotter', 'splitt', 'graben', 'bagger'),
            "mat_tokens": ('schotter',),
            "mach_sug": ('Bagger',),
            "forbid_acts": ('Pflasterfugen verfugt',),
            "prob_must": ('regen',),
            "problem": True,
            "strict": True,
            "min_act": 2,
        },
        {
            "raw": 'Als erstes haben wir den Untergrund vorbereitet mit dem Bagger das ging ungefähr 3 Stunden danach haben wir 5 m³ Frostschutzschotter null 32 reingepackt danach ging noch 2 m³ Split zwei Fünfer rein dann haben wir die Pflasterfläche von 40 m² fertig gestellt morgen müssen wir dann noch mal zur Baustelle und die Fugen mit Fugensand füllen',
            "act_tokens": ('frostschutz', 'splitt', 'pflaster', 'unterbau'),
            "mat_tokens": ('schotter', 'splitt'),
            "mach_sug": ('Bagger',),
            "forbid_acts": ('Pflasterfugen verfugt',),
            "open_must": ('fugensand', 'offen'),
            "open_": True,
            "strict": True,
            "min_act": 2,
        },
        {
            "raw": 'Heute haben wir erst mal den Unterbau mit dem Bagger vorgearbeitet und fertig gestellt dann haben wir 5 m³ Schotter eingebaut und 3 m³ Pflaster wir wollten dann gerade mit dem Pflastern anfangen für 40 m² leider hat uns das Wetter Strich durch die Rechnung gemacht und es hat angefangen zu regnen und wir mussten die Arbeiten abbrechen Trotzdem war die Kundin sehr froh und stolz auf unsere Arbeit',
            "act_tokens": ('unterbau', 'schotter', 'bagger'),
            "mat_tokens": ('schotter',),
            "mach_sug": ('Bagger',),
            "forbid_acts": ('Pflaster verlegt', 'wollten', 'Graben ausgehoben'),
            "forbid_mats": ('wollten', '3 m³ Pflaster'),
            "prob_must": ('regen',),
            "open_must": ('pflaster', 'offen'),
            "cust_must": ('kundin', 'froh'),
            "sum_not": ('pflaster verlegt',),
            "problem": True,
            "open_": True,
            "customer": True,
            "strict": True,
            "min_act": 2,
        },
        {
            "raw": 'Heute wir ham gemacht Bagger mit Loch dann fünf Kubik Schotter 32 danach zwei Kubik Split zwei Fünfer und dann viel Regen Arbeit stopp',
            "act_tokens": ('schotter', 'splitt', 'bagger'),
            "mat_tokens": ('schotter', 'splitt'),
            "mach_sug": ('Bagger',),
            "prob_must": ('regen',),
            "problem": True,
            "min_act": 1,
        },
        {
            "raw": 'Ich hab gemacht heute Untergrund mit Bagger dann drei Kubik Schotter null 32 danach Split ungefähr zwei Kubik und Feierabend',
            "act_tokens": ('schotter', 'splitt', 'bagger'),
            "mat_tokens": ('schotter',),
            "mach_sug": ('Bagger',),
            "min_act": 1,
        },
        {
            "raw": 'Also heute Bagger mit Lock hab ich gemacht dann vier Kubik Schotter 32 danach ich hab gemacht Split zwei Kubik dann hat viel geregnet',
            "act_tokens": ('schotter', 'splitt', 'graben', 'bagger'),
            "mat_tokens": ('schotter',),
            "prob_must": ('regen',),
            "problem": True,
            "min_act": 1,
        },
        {
            "raw": 'Morgens hamma den Graben frei gebaggert mittags drei Kubik Schotter 32 reingemacht nachmittags zwei Kubik Split rein',
            "act_tokens": ('schotter', 'splitt', 'graben', 'bagger'),
            "mat_tokens": ('schotter', 'splitt'),
            "mach_sug": ('Bagger',),
            "min_act": 1,
        },
        {
            "raw": 'Heute auf der Baustelle Baggerarbeiten dann fünf m³ Schotter eingebaut danach Split zwei Fünfer ich hab gemacht fertig',
            "act_tokens": ('schotter', 'splitt', 'bagger'),
            "mat_tokens": ('schotter', 'splitt'),
            "mach_sug": ('Bagger',),
            "min_act": 1,
        },
        {
            "raw": 'Wir haben heute Untergrund gebaggert und 6 Kubik Schotter null 32 verdichtet und drei Kubik Split verarbeitet Kunde war zufrieden',
            "act_tokens": ('schotter', 'splitt', 'bagger'),
            "mat_tokens": ('schotter', 'splitt'),
            "mach_sug": ('Bagger',),
            "cust_must": ('zufrieden',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Zuerst Schmitz Außenanlage Untergrund mit Bagger vorbereitet circa 2 Stunden dann 5 m³ Frostschutzschotter 0/32 reingepackt danach 2 m³ Splitt 2/5 eingebaut Pflasterfläche 32 m² fertig gestellt morgen müssen wir die Fugen mit Fugensand füllen noch offen',
            "act_tokens": ('frostschutz', 'splitt', 'pflaster', 'unterbau'),
            "mat_tokens": ('schotter', 'splitt'),
            "mach_sug": ('Bagger',),
            "forbid_acts": ('Pflasterfugen verfugt',),
            "open_must": ('fugensand', 'offen'),
            "open_": True,
            "min_act": 2,
        },
        {
            "raw": 'Auf Müller Gartenbau Bagger drei Stunden Unterbau fertig dann 4 m³ Schotter null 32 danach ging noch 2 m³ Split zwei Fünfer rein 28 m² Pflasterfläche fertig gestellt morgen müssen wir die Fugen mit Fugensand füllen',
            "act_tokens": ('schotter', 'splitt', 'pflaster', 'unterbau'),
            "mat_tokens": ('schotter',),
            "mach_sug": ('Bagger',),
            "forbid_acts": ('Pflasterfugen verfugt',),
            "open_must": ('fugensand',),
            "open_": True,
            "min_act": 2,
        },
        {
            "raw": 'Den Unterbau haben wir mit dem Bagger vorgearbeitet und fertig gestellt 5 m³ Frostschutzschotter null 32 eingebaut 2 m³ Splitt 2/5 mm eingebaut 45 m² Pflasterfläche fertig gestellt morgen müssen wir Fugensand in die Fugen füllen',
            "act_tokens": ('frostschutz', 'splitt', 'pflaster'),
            "mat_tokens": ('schotter',),
            "mach_sug": ('Bagger',),
            "forbid_acts": ('Pflasterfugen verfugt',),
            "open_must": ('fugensand', 'offen'),
            "open_": True,
            "min_act": 2,
        },
        {
            "raw": 'Heute Schmitz Außenanlage Untergrund gebaggert Schotterplanum 4 m³ Schotter 0/32 verdichtet Splitt 2/5 eingebaut 36 m² Pflaster gelegt morgen noch Fugen mit Sand füllen',
            "act_tokens": ('schotter', 'splitt', 'pflaster', 'bagger'),
            "mat_tokens": ('schotter', 'splitt'),
            "mach_sug": ('Bagger',),
            "forbid_acts": ('Pflasterfugen verfugt',),
            "open_must": ('fugen', 'offen'),
            "open_": True,
            "min_act": 2,
        },
        {
            "raw": 'Müller Gartenbau Unterbau mit Bagger fertig 5 m³ Schotter eingebaut wir wollten gerade mit dem Pflastern anfangen für 32 m² leider hat es angefangen zu regnen und wir mussten abbrechen Rest morgen Pflaster noch offen',
            "act_tokens": ('unterbau', 'schotter', 'bagger'),
            "mat_tokens": ('schotter',),
            "mach_sug": ('Bagger',),
            "forbid_acts": ('Pflaster verlegt', 'wollten', 'Graben ausgehoben'),
            "prob_must": ('regen',),
            "open_must": ('pflaster', 'offen'),
            "sum_not": ('pflaster verlegt',),
            "problem": True,
            "open_": True,
            "forbid_future_pflaster": True,
            "min_act": 1,
        },
        {
            "raw": 'Schotter und Splitt heute eingebaut wir wollten gerade mit dem Pflastern anfangen für 25 m² Wetter hat Strich durch die Rechnung gemacht angefangen zu regnen Arbeiten abbrechen',
            "act_tokens": ('schotter', 'splitt'),
            "mat_tokens": ('schotter', 'splitt'),
            "forbid_acts": ('Pflaster verlegt',),
            "prob_must": ('regen',),
            "open_must": ('pflaster', 'offen'),
            "problem": True,
            "open_": True,
            "forbid_future_pflaster": True,
            "min_act": 1,
        },
        {
            "raw": 'Heute Schmitz Außenanlage 4 m³ Schotter 0/32 verdichtet 2 m³ Splitt eingebaut wir wollten gerade mit dem Pflastern anfangen für 38 m² leider mussten wegen Regen stoppen',
            "act_tokens": ('schotter', 'splitt'),
            "mat_tokens": ('schotter',),
            "forbid_acts": ('Pflaster verlegt', 'Graben ausgehoben'),
            "prob_must": ('regen',),
            "problem": True,
            "forbid_future_pflaster": True,
            "min_act": 1,
        },
        {
            "raw": 'Unterbau mit Bagger vorbereitet 5 m³ Schotter eingebaut wir wollten gerade mit dem Pflastern anfangen für 42 m² Problem wegen Regen mussten die Arbeiten abbrechen Offen Rest Pflaster morgen',
            "act_tokens": ('unterbau', 'schotter', 'bagger'),
            "mat_tokens": ('schotter',),
            "mach_sug": ('Bagger',),
            "forbid_acts": ('Pflaster verlegt', 'wollten'),
            "prob_must": ('regen',),
            "open_must": ('pflaster', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Graben frei gebaggert Schotter null 32 Splitt eingebaut wollten Pflaster legen 30 m² leider Regen Müller Gartenbau dementsprechend Pflastern morgen noch offen',
            "act_tokens": ('schotter', 'splitt', 'graben', 'bagger'),
            "mat_tokens": ('schotter', 'splitt'),
            "mach_sug": ('Bagger',),
            "forbid_acts": ('30 m² Pflaster verlegt',),
            "prob_must": ('regen',),
            "open_must": ('morgen', 'pflaster', 'offen'),
            "problem": True,
            "open_": True,
            "forbid_future_pflaster": True,
            "min_act": 1,
        },
        {
            "raw": 'morgen müssen wir noch 22 m² Pflaster legen Schmitz Außenanlage',
            "open_must": ('morgen', 'pflaster', 'offen'),
            "open_": True,
            "forbid_future_pflaster": True,
            "min_act": 0,
        },
        {
            "raw": 'Heute Schotter eingebaut Splitt verarbeitet dementsprechend verschiebt sich das Pflastern auf morgen Müller Gartenbau',
            "act_tokens": ('schotter', 'splitt'),
            "mat_tokens": ('schotter', 'splitt'),
            "open_must": ('morgen', 'pflaster', 'verschoben'),
            "open_": True,
            "forbid_future_pflaster": True,
            "min_act": 1,
        },
        {
            "raw": 'Untergrund gebaggert 3 m³ Schotter verdichtet zwei Kubik Splitt und morgen Pflaster legen noch offen Schmitz Außenanlage',
            "act_tokens": ('schotter', 'splitt', 'bagger'),
            "mat_tokens": ('schotter', 'splitt'),
            "mach_sug": ('Bagger',),
            "open_must": ('morgen', 'pflaster', 'offen'),
            "open_": True,
            "forbid_future_pflaster": True,
            "min_act": 1,
        },
        {
            "raw": 'Schotterplanum hergestellt Splitt eingebaut Rest Pflaster morgen legen Müller Gartenbau',
            "mat_tokens": ('splitt',),
            "open_must": ('morgen', 'pflaster', 'offen'),
            "open_": True,
            "min_act": 0,
        },
        {
            "raw": 'Untergrund gebaggert Schotter verdichtet leider mussten wir abbrechen weil es angefangen zu regnen Schmitz Außenanlage',
            "act_tokens": ('schotter', 'bagger'),
            "mach_sug": ('Bagger',),
            "prob_must": ('regen',),
            "problem": True,
            "min_act": 0,
        },
        {
            "raw": '3 m³ Schotter eingebaut leider mussten wir die Arbeiten abrechnen weil es stark angefangen zu regnen',
            "mat_tokens": ('schotter',),
            "prob_must": ('regen',),
            "problem": True,
            "min_act": 0,
        },
        {
            "raw": 'Problem Lieferung Schotter spät Offen Splitt morgen nachliefern Müller Gartenbau',
            "prob_must": ('liefer', 'spät'),
            "open_must": ('morgen', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 0,
        },
        {
            "raw": 'Baggerarbeiten Graben Schotter verdichtet Problem Wetter Offen Rest morgen Pflaster Schmitz Außenanlage',
            "act_tokens": ('bagger', 'schotter'),
            "mach_sug": ('Bagger',),
            "prob_must": ('wetter',),
            "open_must": ('morgen', 'pflaster'),
            "problem": True,
            "open_": True,
            "min_act": 0,
        },
        {
            "raw": '5 m³ Schotter 0/32 eingebaut Schmitz Außenanlage',
            "mat_tokens": ('schotter',),
            "min_act": 0,
        },
        {
            "raw": 'drei Kubik Splitt zwei Fünfer eingebaut Müller Gartenbau',
            "act_tokens": ('splitt',),
            "mat_tokens": ('splitt',),
            "min_act": 0,
        },
        {
            "raw": 'zwei Kubikmeter Schotter null 45 verdichtet Schmitz Außenanlage',
            "mat_tokens": ('schotter',),
            "min_act": 0,
        },
        {
            "raw": '4 Kubik Split 0/8 eingebaut auf der Müller Gartenbau',
            "mat_tokens": ('splitt',),
            "min_act": 0,
        },
        {
            "raw": 'Schotter 0/32 6 m³ eingebaut Splitt 2/5 2 m³ Schmitz Außenanlage',
            "mat_tokens": ('schotter', 'splitt'),
            "min_act": 0,
        },
        {
            "raw": 'Frostschutz 5 m³ Schotter null 32 reingepackt Splitt 2/5 2 m³ Müller Gartenbau',
            "act_tokens": ('frostschutz', 'splitt'),
            "mat_tokens": ('schotter', 'splitt'),
            "min_act": 1,
        },
        {
            "raw": 'heute 35 Quadratmeter Pflaster gelegt Schmitz Außenanlage',
            "act_tokens": ('pflaster',),
            "mat_tokens": ('pflaster',),
            "min_act": 1,
        },
        {
            "raw": 'Untergrund gebaggert 4 m³ Schotter null 32 Splitt 2/5 eingebaut und 40 m² Pflaster eingebaut Müller Gartenbau',
            "act_tokens": ('schotter', 'splitt', 'pflaster', 'bagger'),
            "mat_tokens": ('schotter', 'splitt'),
            "mach_sug": ('Bagger',),
            "min_act": 2,
        },
        {
            "raw": 'Heute Schmitz Außenanlage Schotter Splitt eingebaut mit der Kundin gesprochen sie ist sehr zufrieden',
            "mat_tokens": ('schotter', 'splitt'),
            "cust_must": ('gesprochen', 'zufrieden'),
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Bauherr war da Pflaster Muster gewählt Schotter heute eingebaut Müller Gartenbau',
            "mat_tokens": ('schotter',),
            "cust_must": ('bauherr',),
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Also heute Schmitz Außenanlage erst Untergrund frei gebaggert dann Schotter null 32 und drei Kubik Splitt zwei Fünfer',
            "act_tokens": ('schotter', 'splitt', 'bagger', 'graben'),
            "mat_tokens": ('schotter', 'splitt'),
            "mach_sug": ('Bagger',),
            "min_act": 1,
        },
        {
            "raw": 'hamma graben frei gebaggert und 5 kubik schotter eingebaut Müller Gartenbau',
            "act_tokens": ('schotter', 'graben', 'bagger'),
            "mat_tokens": ('schotter',),
            "mach_sug": ('Bagger',),
            "min_act": 1,
        },
        {
            "raw": 'Heute Schmitz Außenanlage Untergrund gebaggert 4 m³ Schotter 0/32 verdichtet 3 Kubik Splitt 2/5 ohne Pflaster',
            "act_tokens": ('schotter', 'splitt', 'bagger'),
            "mat_tokens": ('schotter', 'splitt'),
            "mach_sug": ('Bagger',),
            "forbid_future_pflaster": True,
            "min_act": 1,
        },
        {
            "raw": 'Schotter eingebaut Splitt eingebaut Problem Maschine kaputt Offen Rest morgen Müller Gartenbau',
            "mat_tokens": ('schotter', 'splitt'),
            "prob_must": ('maschine', 'kaputt'),
            "open_must": ('morgen', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 0,
        },
    ]

