"""Putz & Stuck Welle 18 — 100 Basisszenarien (generiert)."""

from __future__ import annotations


def all_base_scenarios() -> list[dict]:
    return [
        {
            "raw": 'Nachmittag Höxter Altputz runter Wand geschliffen Grundierung drauf Unterputz aufgetragen Problem Starkregen mussten abbrechen Offen Oberputz Decke morgen Bauherr war einverstanden und zufrieden.',
            "acts": ('Altputz entfernt', 'Wand geschliffen', 'Grundierung aufgetragen', 'Unterputz aufgetragen'),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 2,
        },
        {
            "raw": 'WDVS Dämmung geklebt Armierungsgewebe eingebettet Reibputz aufgetragen Problem Putzmaschine defekt mussten stoppen.',
            "acts": ('WDVS Dämmung geklebt', 'Armierung ausgeführt', 'Reibputz aufgetragen'),
            "problem": True,
            "min_act": 2,
        },
        {
            "raw": 'Baustelle Warburg Sockelprofil montiert APU-Leiste montiert Leibungsprofil gesetzt Eckschutz gesetzt Untergrund war uneben was zu Problemen geführt hat Bauleitung kurz informiert Termin abgestimmt.',
            "acts": ('Sockelprofile montiert', 'APU-Leisten montiert', 'Leibungsprofile gesetzt', 'Eckschutzprofile gesetzt'),
            "problem": True,
            "customer": True,
            "min_act": 2,
        },
        {
            "raw": 'Innenputz mit Gipsputz aufgetragen Oberputz glatt Putz geglättet Offen WDVS letzte Fläche Donnerstag.',
            "acts": ('Innenputz aufgetragen', 'Oberputz aufgetragen', 'Putz geglättet'),
            "open_": True,
            "min_act": 2,
        },
        {
            "raw": 'Beverungen Hotel-Fassade Außenputz Kratzputz aufgetragen Putz filziert Silikatputz verarbeitet Problem Kleber Lieferung verspätet Offen Fertigstellung nächste Woche.',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert', 'Außenputz aufgetragen'),
            "problem": True,
            "open_": True,
            "min_act": 2,
        },
        {
            "raw": 'WDVS gedübelt Tropfkantenprofil gesetzt Außenputz strukturiert Offen Oberputz Decke morgen machen wir morgen früh den Rest fertig.',
            "acts": ('WDVS gedübelt', 'Tropfkantenprofile gesetzt', 'Außenputz aufgetragen'),
            "open_": True,
            "min_act": 2,
        },
        {
            "raw": 'Schimmel weg gemacht Sanierputz drauf Unterputz nachgearbeitet Bauherr war einverstanden und zufrieden.',
            "acts": ('Schimmel beseitigt', 'Sanierputz aufgebracht', 'Unterputz aufgetragen'),
            "customer": True,
            "min_act": 2,
        },
        {
            "raw": 'Heute nur Bauleitung kurz informiert Termin abgestimmt wegen Besprechung kein Putz wegen Wetter.',
            "acts": (),
            "problem": True,
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Altputz runter Wand geschliffen Grundierung drauf Unterputz aufgetragen',
            "acts": ('Altputz entfernt', 'Wand geschliffen', 'Grundierung aufgetragen', 'Unterputz aufgetragen'),
            "min_act": 2,
        },
        {
            "raw": 'Erst WDVS Dämmung geklebt Armierungsgewebe eingebettet Reibputz aufgetragen dann Sockelprofil montiert APU-Leiste montiert Leibungsprofil gesetzt Eckschutz gesetzt.',
            "acts": ('WDVS Dämmung geklebt', 'Armierung ausgeführt', 'Reibputz aufgetragen', 'Sockelprofile montiert', 'APU-Leisten montiert', 'Leibungsprofile gesetzt', 'Eckschutzprofile gesetzt'),
            "min_act": 3,
        },
        {
            "raw": 'Innenputz mit Gipsputz aufgetragen Oberputz glatt Putz geglättet und am Ende Außenputz Kratzputz aufgetragen Putz filziert Silikatputz verarbeitet.',
            "acts": ('Innenputz aufgetragen', 'Oberputz aufgetragen', 'Putz geglättet', 'Kratzputz aufgetragen', 'Putz filziert', 'Außenputz aufgetragen'),
            "min_act": 3,
        },
        {
            "raw": 'Morgens Höxter Altputz abgetragen Wand geschliffen mittags Grundierung Unterputz aufgetragen nachmittags Oberputz aufgetragen Putz geglättet Bauherr zufrieden Problem Feuchte Offen Rest Montag.',
            "acts": ('Altputz entfernt', 'Wand geschliffen', 'Grundierung aufgetragen', 'Unterputz aufgetragen', 'Oberputz aufgetragen', 'Putz geglättet'),
            "mats": ('Feinputz',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 4,
        },
        {
            "raw": 'WDVS Dämmung geklebt mit EPS und Klebe- und Armierungsmörtel WDVS gedübelt Tellerdübel Armierungsgewebe eingebettet Sockelprofil montiert APU-Leisten montiert Putzmaschine 6 std.',
            "acts": ('WDVS Dämmung geklebt', 'WDVS gedübelt', 'Armierung ausgeführt', 'Sockelprofile montiert', 'APU-Leisten montiert'),
            "mats": ('EPS Dämmplatten', 'Klebe- und Armierungsmörtel', 'Tellerdübel'),
            "mach": ('Putzmaschine',),
            "min_act": 4,
        },
        {
            "raw": 'Fassade Warburg Kratzputz aufgetragen Reibputz nachgearbeitet Putz filziert Außenputz aufgetragen Silikonharzputz verarbeitet.',
            "acts": ('Kratzputz aufgetragen', 'Reibputz aufgetragen', 'Putz filziert', 'Außenputz aufgetragen'),
            "mats": ('Silikonharzputz',),
            "min_act": 3,
        },
        {
            "raw": 'Neubau Treppenhaus Grundputz aufgetragen Innenputz Gipsputz 85 Quadratmeter Sockelputz gemacht Leibungsprofile gesetzt.',
            "acts": ('Grundputz aufgetragen', 'Innenputz aufgetragen', 'Sockelputz aufgetragen', 'Leibungsprofile gesetzt'),
            "mats": ('Gipsputz',),
            "min_act": 3,
        },
        {
            "raw": 'An der Fassade WDVS Platten angeklebt Gewebe reingemacht Reibputz drauf Tropfkantenprofil gesetzt Eckschutzschiene gesetzt.',
            "acts": ('WDVS ausgeführt', 'Armierung ausgeführt', 'Reibputz aufgetragen', 'Tropfkantenprofile gesetzt', 'Eckschutzprofile gesetzt'),
            "min_act": 3,
        },
        {
            "raw": 'Schimmel beseitigt Sanierputz aufgebracht Unterputz aufgetragen Oberputz aufgetragen fertig.',
            "acts": ('Schimmel beseitigt', 'Sanierputz aufgebracht', 'Unterputz aufgetragen', 'Oberputz aufgetragen'),
            "mats": ('Sanierputz',),
            "min_act": 3,
        },
        {
            "raw": 'Sockelleiste stuckiert Gesims angebracht Stuckarbeiten gemacht Kunde informiert.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Sockelprofil montiert APU-Leiste montiert Leibungsprofil gesetzt Eckschutz gesetzt Problem Material knapp Offen Rest morgen.',
            "acts": ('Sockelprofile montiert', 'APU-Leisten montiert', 'Leibungsprofile gesetzt', 'Eckschutzprofile gesetzt'),
            "problem": True,
            "open_": True,
            "min_act": 2,
        },
        {
            "raw": 'WDVS Dämmung geklebt Armierungsgewebe eingebettet Reibputz aufgetragen Problem Tellerdübel fehlen Offen nächste Woche.',
            "acts": ('WDVS Dämmung geklebt', 'Armierung ausgeführt', 'Reibputz aufgetragen'),
            "problem": True,
            "open_": True,
            "min_act": 2,
        },
        {
            "raw": 'Altputz runter Wand geschliffen Grundierung drauf Unterputz aufgetragen leider mussten wir abbrechen morgen weiter.',
            "acts": ('Altputz entfernt', 'Wand geschliffen', 'Grundierung aufgetragen', 'Unterputz aufgetragen'),
            "problem": True,
            "open_": True,
            "min_act": 2,
        },
        {
            "raw": 'Außenputz Kratzputz aufgetragen Putz filziert Silikatputz verarbeitet Kundengespräch mit Bauleitung Abstimmung Termin.',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert', 'Außenputz aufgetragen'),
            "customer": True,
            "min_act": 2,
        },
        {
            "raw": 'Problem Gerüst zu spät Offen Ersatz übermorgen.',
            "acts": (),
            "problem": True,
            "open_": True,
            "min_act": 0,
        },
        {
            "raw": 'Stuckarbeiten gemacht Gesims stuckiert Bauherr zufrieden.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Problem Feuchte im Mauerwerk Offen Sanierung nächste Woche Bauleitung informiert.',
            "acts": (),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'WDVS gedübelt Tropfkantenprofil gesetzt Außenputz strukturiert Auftraggeber kurz da.',
            "acts": ('WDVS gedübelt', 'Tropfkantenprofile gesetzt', 'Außenputz aufgetragen'),
            "customer": True,
            "min_act": 2,
        },
        {
            "raw": 'Heute Höxter und Warburg zuerst Altputz runter Wand geschliffen Grundierung drauf Unterputz aufgetragen danach WDVS Dämmung geklebt Armierungsgewebe eingebettet Reibputz aufgetragen Problem Starkregen mussten abbrechen Offen Oberputz Decke morgen Bauherr war einverstanden und zufrieden Problem Lieferant zu spät Offen Rest Donnerstag.',
            "acts": ('Altputz entfernt', 'Wand geschliffen', 'Grundierung aufgetragen', 'Unterputz aufgetragen'),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 2,
        },
        {
            "raw": 'Früh um halb sechs gestartet mit Sockelprofil montiert APU-Leiste montiert Leibungsprofil gesetzt Eckschutz gesetzt danach Innenputz mit Gipsputz aufgetragen Oberputz glatt Putz geglättet zwischendurch Bauleitung kurz informiert Termin abgestimmt leider Problem Putzmaschine defekt mussten stoppen dementsprechend machen wir morgen früh den Rest fertig Offen Fertigstellung nächste Woche.',
            "acts": ('Sockelprofile montiert', 'APU-Leisten montiert', 'Leibungsprofile gesetzt', 'Eckschutzprofile gesetzt', 'Innenputz aufgetragen', 'Oberputz aufgetragen'),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 3,
        },
        {
            "raw": 'Ja also vom Tag her WDVS Dämmung geklebt Armierungsgewebe eingebettet Reibputz aufgetragen und also Außenputz Kratzputz aufgetragen Putz filziert Silikatputz verarbeitet und Feierabend.',
            "acts": ('WDVS Dämmung geklebt', 'Armierung ausgeführt', 'Kratzputz aufgetragen', 'Putz filziert'),
            "min_act": 2,
        },
        {
            "raw": 'Also heute früh erst den alten Putz abgetragen dann die Wand geschliffen danach grundiert Unterputz aufgetragen während der Unterputz trocknete Bauleitung kurz da Problem Feuchte im Mauerwerk Offen Rest Decke morgen nach dem Kundengespräch Oberputz aufgetragen und Feierabend.',
            "acts": ('Altputz entfernt', 'Wand geschliffen', 'Grundierung aufgetragen', 'Unterputz aufgetragen', 'Oberputz aufgetragen'),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 4,
        },
        {
            "raw": 'heute altputz runter wand geschliffen unterputz auf getragen problem feuchte offen morgen kunde zufrieden putzmaschine 4 std',
            "acts": ('Altputz entfernt', 'Wand geschliffen', 'Unterputz aufgetragen'),
            "mach": ('Putzmaschine',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 2,
        },
        {
            "raw": 'heute auf baustelle wdvs kleben fertig',
            "acts": ('WDVS Dämmung geklebt',),
            "min_act": 1,
        },
        {
            "raw": 'Außenputz Kratzputz aufgetragen Putz filziert Silikatputz verarbeitet bauherr kurz da',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert', 'Außenputz aufgetragen'),
            "customer": True,
            "min_act": 2,
        },
        {
            "raw": 'Oberputz gemacht.',
            "acts": ('Oberputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": 'Armierungsgewebe eingebettet.',
            "acts": ('Armierung ausgeführt',),
            "min_act": 1,
        },
        {
            "raw": 'heute ich hab gemacht APU montiert und Eckschutz',
            "acts": ('APU-Leisten montiert', 'Eckschutzprofile gesetzt'),
            "min_act": 1,
        },
        {
            "raw": 'hamma wdvs gedübelt mit tellerdübel',
            "acts": ('WDVS gedübelt',),
            "mats": ('Tellerdübel',),
            "min_act": 1,
        },
        {
            "raw": 'putz filzen mit filzbrett fertig',
            "acts": ('Putz filziert',),
            "min_act": 1,
        },
        {
            "raw": 'innenputz glätten feinputz verarbeitet',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "min_act": 1,
        },
        {
            "raw": 'laibungsprofil gesetzt fenster fertig',
            "acts": ('Leibungsprofile gesetzt',),
            "min_act": 1,
        },
        {
            "raw": '35 Quadratmeter Innenputz Gipsputz aufgetragen Kalkputz nachgearbeitet.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz', 'Kalkputz'),
            "min_act": 1,
        },
        {
            "raw": '35 Quadratmeter WDVS Dämmung geklebt EPS 55 Millimeter Mineralwolle. leider Regen abbrechen morgen weiter.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '35 Meter APU-Leiste montiert Eckschutzschiene gesetzt Klebeputz verarbeitet. Bauherr informiert.',
            "acts": ('APU-Leisten montiert', 'Eckschutzprofile gesetzt'),
            "mats": ('Klebeputz',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '35 Quadratmeter Außenputz Kratzputz Reibputz Putz filziert. Problem Wetter Offen nächste Woche. Putzmaschine 5 std.',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert'),
            "mats": ('Reibputz',),
            "mach": ('Putzmaschine',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'WDVS gedübelt 42 Quadratmeter Tellerdübel Armierungsgewebe eingebettet.',
            "acts": ('WDVS gedübelt', 'Armierung ausgeführt'),
            "mats": ('Tellerdübel', 'Armierungsgewebe'),
            "min_act": 1,
        },
        {
            "raw": '42 Quadratmeter Unterputz aufgetragen Oberputz aufgetragen Putz geglättet. leider Regen abbrechen morgen weiter.',
            "acts": ('Unterputz aufgetragen', 'Oberputz aufgetragen', 'Putz geglättet'),
            "mats": ('Feinputz',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Sockelprofil 42 Millimeter montiert Tropfkante gesetzt. Bauherr informiert.',
            "acts": ('Sockelprofile montiert', 'Tropfkantenprofile gesetzt'),
            "mats": ('Sockelprofil',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 42 Fenster Anputzleiste montiert. Problem Wetter Offen nächste Woche. Putzmaschine 5 std.',
            "acts": ('Leibungsprofile gesetzt', 'APU-Leisten montiert'),
            "mats": ('Leibungsprofil',),
            "mach": ('Putzmaschine',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '49 Quadratmeter Innenputz Gipsputz aufgetragen Kalkputz nachgearbeitet.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz', 'Kalkputz'),
            "min_act": 1,
        },
        {
            "raw": '49 Quadratmeter WDVS Dämmung geklebt EPS 69 Millimeter Mineralwolle. leider Regen abbrechen morgen weiter.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '49 Meter APU-Leiste montiert Eckschutzschiene gesetzt Klebeputz verarbeitet. Bauherr informiert.',
            "acts": ('APU-Leisten montiert', 'Eckschutzprofile gesetzt'),
            "mats": ('Klebeputz',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '49 Quadratmeter Außenputz Kratzputz Reibputz Putz filziert. Problem Wetter Offen nächste Woche. Putzmaschine 5 std.',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert'),
            "mats": ('Reibputz',),
            "mach": ('Putzmaschine',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'WDVS gedübelt 56 Quadratmeter Tellerdübel Armierungsgewebe eingebettet.',
            "acts": ('WDVS gedübelt', 'Armierung ausgeführt'),
            "mats": ('Tellerdübel', 'Armierungsgewebe'),
            "min_act": 1,
        },
        {
            "raw": '56 Quadratmeter Unterputz aufgetragen Oberputz aufgetragen Putz geglättet. leider Regen abbrechen morgen weiter.',
            "acts": ('Unterputz aufgetragen', 'Oberputz aufgetragen', 'Putz geglättet'),
            "mats": ('Feinputz',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Sockelprofil 56 Millimeter montiert Tropfkante gesetzt. Bauherr informiert.',
            "acts": ('Sockelprofile montiert', 'Tropfkantenprofile gesetzt'),
            "mats": ('Sockelprofil',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 56 Fenster Anputzleiste montiert. Problem Wetter Offen nächste Woche. Putzmaschine 5 std.',
            "acts": ('Leibungsprofile gesetzt', 'APU-Leisten montiert'),
            "mats": ('Leibungsprofil',),
            "mach": ('Putzmaschine',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '63 Quadratmeter Innenputz Gipsputz aufgetragen Kalkputz nachgearbeitet.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz', 'Kalkputz'),
            "min_act": 1,
        },
        {
            "raw": '63 Quadratmeter WDVS Dämmung geklebt EPS 83 Millimeter Mineralwolle. leider Regen abbrechen morgen weiter.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '63 Meter APU-Leiste montiert Eckschutzschiene gesetzt Klebeputz verarbeitet. Bauherr informiert.',
            "acts": ('APU-Leisten montiert', 'Eckschutzprofile gesetzt'),
            "mats": ('Klebeputz',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '63 Quadratmeter Außenputz Kratzputz Reibputz Putz filziert. Problem Wetter Offen nächste Woche. Putzmaschine 5 std.',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert'),
            "mats": ('Reibputz',),
            "mach": ('Putzmaschine',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'WDVS gedübelt 70 Quadratmeter Tellerdübel Armierungsgewebe eingebettet.',
            "acts": ('WDVS gedübelt', 'Armierung ausgeführt'),
            "mats": ('Tellerdübel', 'Armierungsgewebe'),
            "min_act": 1,
        },
        {
            "raw": '70 Quadratmeter Unterputz aufgetragen Oberputz aufgetragen Putz geglättet. leider Regen abbrechen morgen weiter.',
            "acts": ('Unterputz aufgetragen', 'Oberputz aufgetragen', 'Putz geglättet'),
            "mats": ('Feinputz',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Sockelprofil 70 Millimeter montiert Tropfkante gesetzt. Bauherr informiert.',
            "acts": ('Sockelprofile montiert', 'Tropfkantenprofile gesetzt'),
            "mats": ('Sockelprofil',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 70 Fenster Anputzleiste montiert. Problem Wetter Offen nächste Woche. Putzmaschine 5 std.',
            "acts": ('Leibungsprofile gesetzt', 'APU-Leisten montiert'),
            "mats": ('Leibungsprofil',),
            "mach": ('Putzmaschine',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '77 Quadratmeter Innenputz Gipsputz aufgetragen Kalkputz nachgearbeitet.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz', 'Kalkputz'),
            "min_act": 1,
        },
        {
            "raw": '77 Quadratmeter WDVS Dämmung geklebt EPS 97 Millimeter Mineralwolle. leider Regen abbrechen morgen weiter.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '77 Meter APU-Leiste montiert Eckschutzschiene gesetzt Klebeputz verarbeitet. Bauherr informiert.',
            "acts": ('APU-Leisten montiert', 'Eckschutzprofile gesetzt'),
            "mats": ('Klebeputz',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '77 Quadratmeter Außenputz Kratzputz Reibputz Putz filziert. Problem Wetter Offen nächste Woche. Putzmaschine 5 std.',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert'),
            "mats": ('Reibputz',),
            "mach": ('Putzmaschine',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'WDVS gedübelt 84 Quadratmeter Tellerdübel Armierungsgewebe eingebettet.',
            "acts": ('WDVS gedübelt', 'Armierung ausgeführt'),
            "mats": ('Tellerdübel', 'Armierungsgewebe'),
            "min_act": 1,
        },
        {
            "raw": '84 Quadratmeter Unterputz aufgetragen Oberputz aufgetragen Putz geglättet. leider Regen abbrechen morgen weiter.',
            "acts": ('Unterputz aufgetragen', 'Oberputz aufgetragen', 'Putz geglättet'),
            "mats": ('Feinputz',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Sockelprofil 84 Millimeter montiert Tropfkante gesetzt. Bauherr informiert.',
            "acts": ('Sockelprofile montiert', 'Tropfkantenprofile gesetzt'),
            "mats": ('Sockelprofil',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 84 Fenster Anputzleiste montiert. Problem Wetter Offen nächste Woche. Putzmaschine 5 std.',
            "acts": ('Leibungsprofile gesetzt', 'APU-Leisten montiert'),
            "mats": ('Leibungsprofil',),
            "mach": ('Putzmaschine',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '91 Quadratmeter Innenputz Gipsputz aufgetragen Kalkputz nachgearbeitet.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz', 'Kalkputz'),
            "min_act": 1,
        },
        {
            "raw": '91 Quadratmeter WDVS Dämmung geklebt EPS 111 Millimeter Mineralwolle. leider Regen abbrechen morgen weiter.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '91 Meter APU-Leiste montiert Eckschutzschiene gesetzt Klebeputz verarbeitet. Bauherr informiert.',
            "acts": ('APU-Leisten montiert', 'Eckschutzprofile gesetzt'),
            "mats": ('Klebeputz',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '91 Quadratmeter Außenputz Kratzputz Reibputz Putz filziert. Problem Wetter Offen nächste Woche. Putzmaschine 5 std.',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert'),
            "mats": ('Reibputz',),
            "mach": ('Putzmaschine',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'WDVS gedübelt 98 Quadratmeter Tellerdübel Armierungsgewebe eingebettet.',
            "acts": ('WDVS gedübelt', 'Armierung ausgeführt'),
            "mats": ('Tellerdübel', 'Armierungsgewebe'),
            "min_act": 1,
        },
        {
            "raw": '98 Quadratmeter Unterputz aufgetragen Oberputz aufgetragen Putz geglättet. leider Regen abbrechen morgen weiter.',
            "acts": ('Unterputz aufgetragen', 'Oberputz aufgetragen', 'Putz geglättet'),
            "mats": ('Feinputz',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Sockelprofil 98 Millimeter montiert Tropfkante gesetzt. Bauherr informiert.',
            "acts": ('Sockelprofile montiert', 'Tropfkantenprofile gesetzt'),
            "mats": ('Sockelprofil',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 98 Fenster Anputzleiste montiert. Problem Wetter Offen nächste Woche. Putzmaschine 5 std.',
            "acts": ('Leibungsprofile gesetzt', 'APU-Leisten montiert'),
            "mats": ('Leibungsprofil',),
            "mach": ('Putzmaschine',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '105 Quadratmeter Innenputz Gipsputz aufgetragen Kalkputz nachgearbeitet.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz', 'Kalkputz'),
            "min_act": 1,
        },
        {
            "raw": '105 Quadratmeter WDVS Dämmung geklebt EPS 125 Millimeter Mineralwolle. leider Regen abbrechen morgen weiter.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '105 Meter APU-Leiste montiert Eckschutzschiene gesetzt Klebeputz verarbeitet. Bauherr informiert.',
            "acts": ('APU-Leisten montiert', 'Eckschutzprofile gesetzt'),
            "mats": ('Klebeputz',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '105 Quadratmeter Außenputz Kratzputz Reibputz Putz filziert. Problem Wetter Offen nächste Woche. Putzmaschine 5 std.',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert'),
            "mats": ('Reibputz',),
            "mach": ('Putzmaschine',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'WDVS gedübelt 112 Quadratmeter Tellerdübel Armierungsgewebe eingebettet.',
            "acts": ('WDVS gedübelt', 'Armierung ausgeführt'),
            "mats": ('Tellerdübel', 'Armierungsgewebe'),
            "min_act": 1,
        },
        {
            "raw": '112 Quadratmeter Unterputz aufgetragen Oberputz aufgetragen Putz geglättet. leider Regen abbrechen morgen weiter.',
            "acts": ('Unterputz aufgetragen', 'Oberputz aufgetragen', 'Putz geglättet'),
            "mats": ('Feinputz',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Sockelprofil 112 Millimeter montiert Tropfkante gesetzt. Bauherr informiert.',
            "acts": ('Sockelprofile montiert', 'Tropfkantenprofile gesetzt'),
            "mats": ('Sockelprofil',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 112 Fenster Anputzleiste montiert. Problem Wetter Offen nächste Woche. Putzmaschine 5 std.',
            "acts": ('Leibungsprofile gesetzt', 'APU-Leisten montiert'),
            "mats": ('Leibungsprofil',),
            "mach": ('Putzmaschine',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '119 Quadratmeter Innenputz Gipsputz aufgetragen Kalkputz nachgearbeitet.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz', 'Kalkputz'),
            "min_act": 1,
        },
        {
            "raw": '119 Quadratmeter WDVS Dämmung geklebt EPS 139 Millimeter Mineralwolle. leider Regen abbrechen morgen weiter.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '119 Meter APU-Leiste montiert Eckschutzschiene gesetzt Klebeputz verarbeitet. Bauherr informiert.',
            "acts": ('APU-Leisten montiert', 'Eckschutzprofile gesetzt'),
            "mats": ('Klebeputz',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '119 Quadratmeter Außenputz Kratzputz Reibputz Putz filziert. Problem Wetter Offen nächste Woche. Putzmaschine 5 std.',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert'),
            "mats": ('Reibputz',),
            "mach": ('Putzmaschine',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'WDVS gedübelt 126 Quadratmeter Tellerdübel Armierungsgewebe eingebettet.',
            "acts": ('WDVS gedübelt', 'Armierung ausgeführt'),
            "mats": ('Tellerdübel', 'Armierungsgewebe'),
            "min_act": 1,
        },
        {
            "raw": '126 Quadratmeter Unterputz aufgetragen Oberputz aufgetragen Putz geglättet. leider Regen abbrechen morgen weiter.',
            "acts": ('Unterputz aufgetragen', 'Oberputz aufgetragen', 'Putz geglättet'),
            "mats": ('Feinputz',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Sockelprofil 126 Millimeter montiert Tropfkante gesetzt. Bauherr informiert.',
            "acts": ('Sockelprofile montiert', 'Tropfkantenprofile gesetzt'),
            "mats": ('Sockelprofil',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 126 Fenster Anputzleiste montiert. Problem Wetter Offen nächste Woche. Putzmaschine 5 std.',
            "acts": ('Leibungsprofile gesetzt', 'APU-Leisten montiert'),
            "mats": ('Leibungsprofil',),
            "mach": ('Putzmaschine',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '133 Quadratmeter Innenputz Gipsputz aufgetragen Kalkputz nachgearbeitet.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz', 'Kalkputz'),
            "min_act": 1,
        },
        {
            "raw": '133 Quadratmeter WDVS Dämmung geklebt EPS 153 Millimeter Mineralwolle. leider Regen abbrechen morgen weiter.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": '133 Meter APU-Leiste montiert Eckschutzschiene gesetzt Klebeputz verarbeitet. Bauherr informiert.',
            "acts": ('APU-Leisten montiert', 'Eckschutzprofile gesetzt'),
            "mats": ('Klebeputz',),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": '133 Quadratmeter Außenputz Kratzputz Reibputz Putz filziert. Problem Wetter Offen nächste Woche. Putzmaschine 5 std.',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert'),
            "mats": ('Reibputz',),
            "mach": ('Putzmaschine',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
    ]
