"""Putz & Stuck Welle 19 — 150 Basisszenarien (generiert)."""

from __future__ import annotations


def all_base_scenarios() -> list[dict]:
    return [
        {
            "raw": 'Höxter Innenputz mit Gipsputz aufgetragen 120 Quadratmeter fertig.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "sugs": ('Putzmaschine benutzt?', 'Kartätsche benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Außenputz Silikatputz aufgetragen Fassade Warburg Nordseite.',
            "acts": ('Außenputz aufgetragen',),
            "mats": ('Silikatputz',),
            "sugs": ('Haftbrücke benutzt?', 'Putzmaschine benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Putz geglättet mit Feinputz Decke OG fertig.',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "sugs": ('Glättkelle benutzt?',),
            "forbid_sugs": ('Feinputz benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Außenputz Kratzputz aufgetragen Putz filziert Fassade fertig.',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert', 'Außenputz aufgetragen'),
            "sugs": ('Filzbrett benutzt?',),
            "min_act": 2,
        },
        {
            "raw": 'WDVS Dämmung geklebt EPS-Dämmplatten Fassade Süd.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "sugs": ('Zahntraufel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'WDVS gedübelt an der Fassade komplett.',
            "acts": ('WDVS gedübelt',),
            "sugs": ('Tellerdübel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Armierungsgewebe eingebettet WDVS Armierung fertig.',
            "acts": ('Armierung ausgeführt',),
            "mats": ('Armierungsgewebe',),
            "sugs": ('Armierungsmörtel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Eckschutzschiene gesetzt an allen Außenecken.',
            "acts": ('Eckschutzprofile gesetzt',),
            "sugs": ('Klebeputz benutzt?', 'Spachtelmasse benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'APU-Leiste montiert Fensteranschluss Nord.',
            "acts": ('APU-Leisten montiert',),
            "sugs": ('Klebeputz benutzt?', 'Dichtlippe benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 14 Fenster.',
            "acts": ('Leibungsprofile gesetzt',),
            "mats": ('Leibungsprofil',),
            "sugs": ('Klebeputz benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Sockelprofil montiert Sockelzone komplett.',
            "acts": ('Sockelprofile montiert',),
            "sugs": ('Sockeldämmung benutzt?', 'Noppenbahn benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Tropfkantenprofil gesetzt Gesimsabschluss.',
            "acts": ('Tropfkantenprofile gesetzt',),
            "sugs": ('Klebeputz benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Altputz entfernt Wand geschliffen Grundierung drauf.',
            "acts": ('Altputz entfernt', 'Wand geschliffen', 'Grundierung aufgetragen'),
            "sugs": ('Entsorgungssäcke benutzt?',),
            "min_act": 2,
        },
        {
            "raw": 'Schimmel beseitigt Sanierputz aufgebracht.',
            "acts": ('Schimmel beseitigt', 'Sanierputz aufgebracht'),
            "mats": ('Sanierputz',),
            "sugs": ('Schimmelentferner benutzt?',),
            "min_act": 2,
        },
        {
            "raw": 'Oberputz aufgetragen. Wand war trocken.',
            "acts": ('Oberputz aufgetragen',),
            "sugs": ('Grundierung benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Stuckarbeiten gemacht Gesims stuckiert Rosette angebracht.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "sugs": ('Montagekleber benutzt?', 'Feinspachtel benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Reibputz aufgetragen WDVS Schicht Beverungen.',
            "acts": ('Reibputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": 'Unterputz aufgetragen Grundputz vorher fertig.',
            "acts": ('Unterputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": 'Sockelputz aufgetragen Kellerwand.',
            "acts": ('Sockelputz aufgetragen',),
            "sugs": ('Grundierung benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Morgens Höxter WDVS Dämmung geklebt mittags WDVS gedübelt nachmittags Armierungsgewebe eingebettet.',
            "acts": ('WDVS Dämmung geklebt', 'WDVS gedübelt', 'Armierung ausgeführt'),
            "sugs": ('Zahntraufel benutzt?', 'Tellerdübel benutzt?'),
            "min_act": 2,
        },
        {
            "raw": 'Komplett Fassade Warburg: Sockelprofil montiert APU-Leisten montiert Leibungsprofile gesetzt Eckschutzprofile gesetzt.',
            "acts": ('Sockelprofile montiert', 'APU-Leisten montiert', 'Leibungsprofile gesetzt', 'Eckschutzprofile gesetzt'),
            "sugs": ('Klebeputz benutzt?',),
            "min_act": 3,
        },
        {
            "raw": 'Innenputz Kalkputz aufgetragen 65 Quadratmeter Treppenhaus.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Kalkputz',),
            "sugs": ('Putzmaschine benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Silikonharzputz verarbeitet Außenputz strukturiert.',
            "acts": ('Außenputz aufgetragen',),
            "mats": ('Silikonharzputz',),
            "sugs": ('Haftbrücke benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Oberputz glatt Putz geglättet Innenwand Wohnzimmer.',
            "acts": ('Oberputz aufgetragen', 'Putz geglättet'),
            "sugs": ('Glättkelle benutzt?', 'Schwammbrett benutzt?'),
            "min_act": 2,
        },
        {
            "raw": 'Fassadenarmierung ausgeführt an Hotel-Fassade.',
            "acts": ('Fassadenarmierung ausgeführt',),
            "sugs": ('Armierungsmörtel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Putz geglättet mit Glättkelle und Feinputz fertig.',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "forbid_sugs": ('Glättkelle benutzt?', 'Feinputz benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Putz filziert mit Filzbrett Außenwand strukturiert.',
            "acts": ('Putz filziert',),
            "forbid_sugs": ('Filzbrett benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'WDVS gedübelt mit Tellerdübel 6 pro Quadratmeter.',
            "acts": ('WDVS gedübelt',),
            "mats": ('Tellerdübel',),
            "forbid_sugs": ('Tellerdübel benutzt?', 'Schraubdübel benutzt?', 'Schlagdübel benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'WDVS Dämmung geklebt mit Zahntraufel und Klebe- und Armierungsmörtel.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('Klebe- und Armierungsmörtel',),
            "forbid_sugs": ('Zahntraufel benutzt?', 'Klebe- und Armierungsmörtel benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Eckschutzprofile gesetzt mit Klebeputz und Spachtelmasse.',
            "acts": ('Eckschutzprofile gesetzt',),
            "mats": ('Klebeputz', 'Spachtelmasse'),
            "forbid_sugs": ('Klebeputz benutzt?', 'Spachtelmasse benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'APU-Leiste montiert Klebeputz verarbeitet Dichtlippe gesetzt.',
            "acts": ('APU-Leisten montiert',),
            "mats": ('Klebeputz',),
            "forbid_sugs": ('Klebeputz benutzt?', 'Dichtlippe benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Sockelprofil montiert Sockeldämmung und Noppenbahn drunter.',
            "acts": ('Sockelprofile montiert',),
            "forbid_sugs": ('Sockeldämmung benutzt?', 'Noppenbahn benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Innenputz mit Putzmaschine aufgetragen Gipsputz 90 Quadratmeter.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "forbid_sugs": ('Putzmaschine benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Innenputz mit Kartätsche gezogen Kalkputz Wand.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Kalkputz',),
            "forbid_sugs": ('Kartätsche benutzt?', 'Putzmaschine benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Außenputz mit Haftbrücke vorbereitet Silikatputz aufgetragen.',
            "acts": ('Außenputz aufgetragen',),
            "mats": ('Silikatputz',),
            "forbid_sugs": ('Haftbrücke benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Schimmel beseitigt mit Schimmelentferner. Sanierputz drauf.',
            "acts": ('Schimmel beseitigt', 'Sanierputz aufgebracht'),
            "mats": ('Sanierputz',),
            "forbid_sugs": ('Schimmelentferner benutzt?',),
            "min_act": 2,
        },
        {
            "raw": 'Stuckarbeiten mit Montagekleber und Feinspachtel fertig.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "forbid_sugs": ('Montagekleber benutzt?', 'Feinspachtel benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Armierungsgewebe eingebettet Armierungsmörtel verarbeitet.',
            "acts": ('Armierung ausgeführt',),
            "mats": ('Armierungsmörtel', 'Armierungsgewebe'),
            "forbid_sugs": ('Armierungsmörtel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Leibungsprofil gesetzt Klebeputz und Dichtlippe eingesetzt.',
            "acts": ('Leibungsprofile gesetzt',),
            "mats": ('Klebeputz',),
            "forbid_sugs": ('Klebeputz benutzt?', 'Dichtlippe benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Tropfkantenprofil gesetzt Klebeputz Armierungsgewebe an Ecke.',
            "acts": ('Tropfkantenprofile gesetzt',),
            "mats": ('Klebeputz',),
            "forbid_sugs": ('Klebeputz benutzt?', 'Armierung benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Altputz runter Entsorgungssäcke voll Container bestellt.',
            "acts": ('Altputz entfernt',),
            "forbid_sugs": ('Entsorgungssäcke benutzt?', 'Container benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Oberputz aufgetragen. Grundierung und Haftgrund vorher drauf.',
            "acts": ('Oberputz aufgetragen',),
            "mats": ('Grundierung', 'Haftgrund'),
            "forbid_sugs": ('Grundierung benutzt?', 'Haftgrund benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Putz filziert Schwammbrett benutzt Struktur fein.',
            "acts": ('Putz filziert',),
            "forbid_sugs": ('Filzbrett benutzt?', 'Schwammbrett benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'WDVS gedübelt Schlagdübel gesetzt Mineralwolle Platten.',
            "acts": ('WDVS gedübelt',),
            "forbid_sugs": ('Tellerdübel benutzt?', 'Schraubdübel benutzt?', 'Schlagdübel benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Außenputz Gewebeeinlage an Brüstung. Armierung ausgeführt.',
            "acts": ('Armierung ausgeführt',),
            "forbid_sugs": ('Gewebeeinlage benutzt?', 'Armierungsgewebe benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Höxter Innenputz Gipsputz aufgetragen 80 Quadratmeter Problem Lieferung Gipsputz verspätet Offen Rest Flur Montag mit der Bauherrin gesprochen sie ist einverstanden.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "prob_must": ('liefer', 'verspät'),
            "prob_not": ('gipsputz aufgetragen', '80', 'quadratmeter'),
            "open_must": ('montag', 'flur', 'offen'),
            "open_not": ('gipsputz', '80'),
            "cust_must": ('einverstanden', 'bauherrin'),
            "cust_not": ('80', 'quadratmeter', 'aufgetragen'),
            "problem": True,
            "open_": True,
            "customer": True,
            "mat_echo": True,
        },
        {
            "raw": 'WDVS Dämmung geklebt Warburg Problem Starkregen mussten abbrechen Offen letzte Fläche Donnerstag Bauleitung informiert.',
            "acts": ('WDVS Dämmung geklebt',),
            "prob_must": ('regen', 'abbrechen'),
            "prob_not": ('wdvs', 'geklebt'),
            "open_must": ('donnerstag', 'offen'),
            "cust_must": ('informiert',),
            "cust_not": ('geklebt',),
            "problem": True,
            "open_": True,
            "customer": True,
        },
        {
            "raw": 'Putz geglättet Oberputz aufgetragen Problem Putzmaschine defekt Offen Decke OG morgen Auftraggeber kurz da.',
            "acts": ('Putz geglättet', 'Oberputz aufgetragen'),
            "prob_must": ('defekt', 'putzmaschine'),
            "prob_not": ('geglättet', 'oberputz'),
            "open_must": ('decke', 'morgen', 'offen'),
            "cust_must": ('auftraggeber',),
            "cust_not": ('geglättet',),
            "problem": True,
            "open_": True,
            "customer": True,
        },
        {
            "raw": 'Schimmel beseitigt Sanierputz aufgebracht Problem hohe Feuchte Offen Sanierung Keller nächste Woche.',
            "acts": ('Schimmel beseitigt', 'Sanierputz aufgebracht'),
            "mats": ('Sanierputz',),
            "prob_must": ('feuchte',),
            "open_must": ('keller', 'woche', 'offen'),
            "open_not": ('sanierputz',),
            "problem": True,
            "open_": True,
        },
        {
            "raw": 'Sockelprofil montiert APU-Leisten montiert Problem Material knapp Offen Rest Fenster morgen Kundengespräch Termin abgestimmt.',
            "acts": ('Sockelprofile montiert', 'APU-Leisten montiert'),
            "prob_must": ('material', 'knapp'),
            "open_must": ('fenster', 'morgen', 'offen'),
            "cust_must": ('abgestimmt', 'termin'),
            "cust_not": ('montiert', 'sockelprofil'),
            "problem": True,
            "open_": True,
            "customer": True,
        },
        {
            "raw": 'Fassade Beverungen Kratzputz aufgetragen Putz filziert Problem Wind zu stark Offen Nordwestseite Freitag.',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert'),
            "prob_must": ('wind',),
            "prob_not": ('kratzputz', 'filziert'),
            "open_must": ('freitag', 'offen'),
            "open_not": ('kratzputz',),
            "problem": True,
            "open_": True,
        },
        {
            "raw": 'Heute nur mit dem Bauherr Rücksprache gehalten nächster Termin abgestimmt kein Putz wegen Frost.',
            "acts": (),
            "prob_must": ('frost',),
            "cust_must": ('rücksprache', 'abgestimmt'),
            "cust_not": ('aufgetragen', 'm²'),
            "problem": True,
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'Altputz entfernt Wand geschliffen Problem Gerüst zu spät Offen Oberputz übermorgen Bauherr zufrieden.',
            "acts": ('Altputz entfernt', 'Wand geschliffen'),
            "prob_must": ('gerüst', 'spät'),
            "open_must": ('oberputz', 'offen'),
            "cust_must": ('zufrieden',),
            "cust_not": ('entfernt', 'geschiffen'),
            "problem": True,
            "open_": True,
            "customer": True,
        },
        {
            "raw": 'WDVS gedübelt Tellerdübel Problem Lieferant Tellerdübel fehlen Offen Nachlieferung Mittwoch.',
            "acts": ('WDVS gedübelt',),
            "mats": ('Tellerdübel',),
            "prob_must": ('fehlen', 'tellerdübel'),
            "prob_not": ('gedübelt',),
            "open_must": ('mittwoch', 'offen'),
            "problem": True,
            "open_": True,
        },
        {
            "raw": 'Leibungsprofile gesetzt Problem Untergrund uneben was zu Problemen geführt hat Offen Korrektur Laibung Donnerstag Kunde informiert.',
            "acts": ('Leibungsprofile gesetzt',),
            "prob_must": ('uneben',),
            "prob_not": ('gesetzt',),
            "open_must": ('donnerstag', 'offen'),
            "cust_must": ('informiert',),
            "problem": True,
            "open_": True,
            "customer": True,
        },
        {
            "raw": 'Eckschutzprofile gesetzt Problem Kleber Lieferung verspätet Offen Fertigstellung nächste Woche.',
            "acts": ('Eckschutzprofile gesetzt',),
            "prob_must": ('kleber', 'liefer'),
            "open_must": ('woche', 'offen'),
            "problem": True,
            "open_": True,
        },
        {
            "raw": 'Stuckarbeiten gemacht Gesims stuckiert mit dem Kunden unterhalten er wünscht gleiche Ausführung im Flur.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "cust_must": ('unterhalten', 'kunden'),
            "cust_not": ('stuckiert', 'gesims'),
            "customer": True,
        },
        {
            "raw": 'Innenputz aufgetragen Problem Temperatur zu niedrig Offen Rest Bad morgen.',
            "acts": ('Innenputz aufgetragen',),
            "prob_must": ('temperatur',),
            "prob_not": ('innenputz',),
            "open_must": ('bad', 'morgen', 'offen'),
            "problem": True,
            "open_": True,
        },
        {
            "raw": 'Reibputz aufgetragen Armierung ausgeführt Problem Mörtelcharge schlecht Offen Nacharbeit Samstag Bauleitung kurz informiert.',
            "acts": ('Reibputz aufgetragen', 'Armierung ausgeführt'),
            "prob_must": ('mörtel', 'charge'),
            "open_must": ('samstag', 'offen'),
            "cust_must": ('informiert',),
            "problem": True,
            "open_": True,
            "customer": True,
        },
        {
            "raw": 'Tropfkantenprofile gesetzt Offen Abschluss Gesims nächste Woche.',
            "acts": ('Tropfkantenprofile gesetzt',),
            "open_must": ('gesims', 'woche', 'offen'),
            "open_not": ('gesetzt',),
            "open_": True,
        },
        {
            "raw": 'Unterputz aufgetragen Oberputz aufgetragen Problem Feuchte Decke Offen Rest Montag.',
            "acts": ('Unterputz aufgetragen', 'Oberputz aufgetragen'),
            "prob_must": ('feuchte',),
            "prob_not": ('unterputz aufgetragen',),
            "open_must": ('montag', 'offen'),
            "problem": True,
            "open_": True,
        },
        {
            "raw": 'Also heute früh Höxter WDVS kleben dann dübeln Problem Hitze Kleber zu schnell Offen Nordgiebel Donnerstag.',
            "acts": ('WDVS Dämmung geklebt', 'WDVS gedübelt'),
            "prob_must": ('hitze', 'kleber'),
            "open_must": ('donnerstag', 'offen'),
            "problem": True,
            "open_": True,
        },
        {
            "raw": 'Sockelputz aufgetragen Problem Untergrund nass Offen Trocknung abwarten Dienstag.',
            "acts": ('Sockelputz aufgetragen',),
            "prob_must": ('nass',),
            "open_must": ('dienstag', 'offen'),
            "problem": True,
            "open_": True,
        },
        {
            "raw": 'Fassadenarmierung ausgeführt Reibputz drauf Bauherr war einverstanden und zufrieden.',
            "acts": ('Fassadenarmierung ausgeführt', 'Reibputz aufgetragen'),
            "cust_must": ('zufrieden', 'einverstanden'),
            "cust_not": ('reibputz', 'armierung'),
            "customer": True,
            "min_act": 2,
        },
        {
            "raw": 'Problem Wetter Offen nächste Woche. Heute kein Außenputz.',
            "acts": (),
            "prob_must": ('wetter',),
            "open_must": ('woche', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 0,
        },
        {
            "raw": 'WDVS Dämmung geklebt mit EPS und Klebe- und Armierungsmörtel WDVS gedübelt Tellerdübel Armierungsgewebe eingebettet Putzmaschine 5 std.',
            "acts": ('WDVS Dämmung geklebt', 'WDVS gedübelt', 'Armierung ausgeführt'),
            "mats": ('EPS Dämmplatten', 'Klebe- und Armierungsmörtel', 'Tellerdübel', 'Armierungsgewebe'),
            "mach": ('Putzmaschine',),
            "forbid_sugs": ('Tellerdübel benutzt?',),
            "min_act": 3,
        },
        {
            "raw": 'Neubau Warburg Grundputz aufgetragen Innenputz Gipsputz 95 Quadratmeter Sockelputz gemacht Feinputz nachgearbeitet.',
            "acts": ('Grundputz aufgetragen', 'Innenputz aufgetragen', 'Sockelputz aufgetragen'),
            "mats": ('Gipsputz', 'Feinputz'),
            "min_act": 3,
        },
        {
            "raw": 'An der Fassade WDVS Platten angeklebt Gewebe reingemacht Reibputz drauf Tropfkantenprofil gesetzt Eckschutzschiene gesetzt.',
            "acts": ('WDVS ausgeführt', 'Armierung ausgeführt', 'Reibputz aufgetragen', 'Tropfkantenprofile gesetzt', 'Eckschutzprofile gesetzt'),
            "min_act": 3,
        },
        {
            "raw": 'Schimmel beseitigt Sanierputz aufgebracht Unterputz aufgetragen Oberputz aufgetragen Haftgrund verwendet.',
            "acts": ('Schimmel beseitigt', 'Sanierputz aufgebracht', 'Unterputz aufgetragen', 'Oberputz aufgetragen'),
            "mats": ('Sanierputz',),
            "forbid_sugs": ('Schimmelentferner benutzt?', 'Haftgrund benutzt?'),
            "min_act": 3,
        },
        {
            "raw": 'Beverungen Hotel-Fassade Kalkzementputz aufgetragen Kratzputz Reibputz nachgearbeitet Silikonharzputz verarbeitet.',
            "acts": ('Außenputz aufgetragen', 'Kratzputz aufgetragen', 'Reibputz aufgetragen'),
            "mats": ('Kalkzementputz', 'Silikonharzputz'),
            "min_act": 2,
        },
        {
            "raw": 'Holzfaserplatten geklebt WDVS Dämmung geklebt Mineralwolle ergänzt.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('Holzfaserplatten',),
            "min_act": 1,
        },
        {
            "raw": 'PU-Stuckprofil montiert Stuckkleber verarbeitet Gesims angebracht.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "mats": ('PU-Stuckprofil',),
            "forbid_sugs": ('Montagekleber benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Gips-Stuckprofil stuckiert Feinspachtel nachgearbeitet.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "forbid_sugs": ('Feinspachtel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Lehmputz aufgetragen Innenputz Wohnbereich 45 Quadratmeter.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Lehmputz',),
            "min_act": 1,
        },
        {
            "raw": 'Kalkputz und Kalkfeinputz verarbeitet Putz geglättet.',
            "acts": ('Innenputz aufgetragen', 'Putz geglättet'),
            "mats": ('Kalkputz',),
            "min_act": 2,
        },
        {
            "raw": 'Armierungsgewebe 200g eingebettet. Armierungsmörtel verarbeitet.',
            "acts": ('Armierung ausgeführt',),
            "mats": ('Armierungsgewebe', 'Armierungsmörtel'),
            "forbid_sugs": ('Armierungsmörtel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'APU 6mm mit Gewebe montiert Anputzleiste Fensterbank.',
            "acts": ('APU-Leisten montiert',),
            "mats": ('APU-Leiste',),
            "min_act": 1,
        },
        {
            "raw": 'Eckschutzschiene Alu gesetzt PVC-Eckprofil Ersatz.',
            "acts": ('Eckschutzprofile gesetzt',),
            "mats": ('Eckschutzschiene',),
            "min_act": 1,
        },
        {
            "raw": 'Sockelprofil mit Tropfkante montiert Sockeldämmung eingebaut.',
            "acts": ('Sockelprofile montiert',),
            "forbid_sugs": ('Sockeldämmung benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Tropfkantenprofil PVC gesetzt Tropfkante Alu Fensterbrüstung.',
            "acts": ('Tropfkantenprofile gesetzt',),
            "mats": ('Tropfkantenprofil',),
            "min_act": 1,
        },
        {
            "raw": 'Heute Höxter und Warburg zuerst Altputz runter Wand geschliffen Grundierung drauf Unterputz aufgetragen danach WDVS Dämmung geklebt Armierungsgewebe eingebettet Problem Starkregen mussten abbrechen Offen Oberputz Decke morgen Bauherr war einverstanden und zufrieden.',
            "acts": ('Altputz entfernt', 'Wand geschliffen', 'Grundierung aufgetragen', 'Unterputz aufgetragen', 'WDVS Dämmung geklebt', 'Armierung ausgeführt'),
            "prob_must": ('regen',),
            "open_must": ('oberputz', 'morgen'),
            "cust_must": ('zufrieden',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 4,
        },
        {
            "raw": 'Früh um halb sechs gestartet mit Sockelprofil montiert APU-Leiste montiert Leibungsprofil gesetzt Eckschutz gesetzt danach Innenputz mit Gipsputz aufgetragen Oberputz glatt Putz geglättet zwischendurch Bauleitung kurz informiert Termin abgestimmt leider Problem Putzmaschine defekt mussten stoppen dementsprechend machen wir morgen früh den Rest fertig Offen Fertigstellung nächste Woche.',
            "acts": ('Sockelprofile montiert', 'APU-Leisten montiert', 'Leibungsprofile gesetzt', 'Eckschutzprofile gesetzt', 'Innenputz aufgetragen', 'Oberputz aufgetragen', 'Putz geglättet'),
            "prob_must": ('defekt',),
            "open_must": ('woche',),
            "cust_must": ('informiert',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 5,
        },
        {
            "raw": 'Also heute vom Tag her erst den alten Putz abgetragen dann die Wand geschliffen danach grundiert Unterputz aufgetragen während der Unterputz trocknete WDVS gedübelt Tellerdübel gesetzt Armierungsgewebe eingebettet Reibputz aufgetragen nach dem Kundengespräch mit der Bauherrin Putz filziert Außenputz strukturiert Problem hohe Feuchte Offen Rest Decke Montag und Feierabend.',
            "acts": ('Altputz entfernt', 'Wand geschliffen', 'Unterputz aufgetragen', 'WDVS gedübelt', 'Armierung ausgeführt', 'Reibputz aufgetragen', 'Putz filziert', 'Außenputz aufgetragen'),
            "prob_must": ('feuchte',),
            "open_must": ('montag',),
            "cust_must": ('kundengespräch',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 5,
        },
        {
            "raw": 'Ja also vom Tag her WDVS Dämmung geklebt und also Außenputz Kratzputz aufgetragen Putz filziert und Feierabend.',
            "acts": ('WDVS Dämmung geklebt', 'Kratzputz aufgetragen', 'Putz filziert'),
            "min_act": 2,
        },
        {
            "raw": 'Morgens Beverungen Schimmel weg gemacht Sanierputz drauf Unterputz nachgearbeitet mittags Oberputz aufgetragen nachmittags Putz geglättet Bauherr zufrieden.',
            "acts": ('Schimmel beseitigt', 'Sanierputz aufgebracht', 'Unterputz aufgetragen', 'Oberputz aufgetragen', 'Putz geglättet'),
            "cust_must": ('zufrieden',),
            "customer": True,
            "min_act": 4,
        },
        {
            "raw": 'Komplettsanierung Höxter Treppenhaus: Altputz entfernt Grundputz aufgetragen Innenputz Kalkputz 110 Quadratmeter Sockelputz gemacht Leibungsprofile gesetzt Putzmaschine 7 std Kunde informiert.',
            "acts": ('Altputz entfernt', 'Grundputz aufgetragen', 'Innenputz aufgetragen', 'Sockelputz aufgetragen', 'Leibungsprofile gesetzt'),
            "mats": ('Kalkputz',),
            "mach": ('Putzmaschine',),
            "customer": True,
            "min_act": 4,
        },
        {
            "raw": 'WDVS Komplett Warburg: Dämmung geklebt gedübelt Armierung Reibputz Sockelprofil montiert APU-Leisten montiert Tropfkanten gesetzt Eckschutz gesetzt Problem Lieferant zu spät Offen letzte Ecke Freitag.',
            "acts": ('WDVS Dämmung geklebt', 'WDVS gedübelt', 'Armierung ausgeführt', 'Reibputz aufgetragen', 'Sockelprofile montiert', 'APU-Leisten montiert', 'Tropfkantenprofile gesetzt', 'Eckschutzprofile gesetzt'),
            "prob_must": ('liefer', 'spät'),
            "open_must": ('freitag',),
            "problem": True,
            "open_": True,
            "min_act": 5,
        },
        {
            "raw": 'Innen und außen: Innenputz Gipsputz aufgetragen und am Ende Außenputz Silikatputz Kratzputz Putz filziert.',
            "acts": ('Innenputz aufgetragen', 'Außenputz aufgetragen', 'Kratzputz aufgetragen', 'Putz filziert'),
            "mats": ('Gipsputz', 'Silikatputz'),
            "min_act": 3,
        },
        {
            "raw": 'innenputz gipsputz drauf 40 qm',
            "acts": ('Innenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": 'wdvs kleben fertig',
            "acts": ('WDVS Dämmung geklebt',),
            "min_act": 1,
        },
        {
            "raw": 'putz glätten feinputz',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "min_act": 1,
        },
        {
            "raw": 'eckschutz gesetzt',
            "acts": ('Eckschutzprofile gesetzt',),
            "min_act": 1,
        },
        {
            "raw": 'hamma wdvs gedübelt tellerdübel',
            "acts": ('WDVS gedübelt',),
            "mats": ('Tellerdübel',),
            "forbid_sugs": ('Tellerdübel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'putz filziert mit filzbrett',
            "acts": ('Putz filziert',),
            "forbid_sugs": ('Filzbrett benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'problem regen offen morgen kein putz',
            "acts": (),
            "prob_must": ('regen',),
            "open_must": ('morgen',),
            "problem": True,
            "open_": True,
            "min_act": 0,
        },
        {
            "raw": 'bauherr kurz da',
            "acts": (),
            "cust_must": ('bauherr',),
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'stuck gemacht gesims',
            "acts": ('Stuckarbeiten durchgeführt',),
            "min_act": 1,
        },
        {
            "raw": 'reibputz drauf armierung',
            "acts": ('Reibputz aufgetragen', 'Armierung ausgeführt'),
            "min_act": 2,
        },
        {
            "raw": 'heute nur bauleitung informiert termin',
            "acts": (),
            "cust_must": ('informiert', 'termin'),
            "customer": True,
            "min_act": 0,
        },
        {
            "raw": 'oberputz glatt putz geglättet',
            "acts": ('Oberputz aufgetragen', 'Putz geglättet'),
            "min_act": 2,
        },
        {
            "raw": '40 Quadratmeter Innenputz Gipsputz aufgetragen.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "sugs": ('Putzmaschine benutzt?',),
        },
        {
            "raw": '40 Quadratmeter WDVS Dämmung geklebt EPS 55 Millimeter.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "sugs": ('Zahntraufel benutzt?',),
        },
        {
            "raw": 'Putz geglättet 40 Quadratmeter Feinputz Decke.',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "sugs": ('Glättkelle benutzt?',),
            "forbid_sugs": ('Feinputz benutzt?',),
        },
        {
            "raw": 'WDVS gedübelt 45 Quadratmeter Tellerdübel gesetzt.',
            "acts": ('WDVS gedübelt',),
            "mats": ('Tellerdübel',),
            "forbid_sugs": ('Tellerdübel benutzt?',),
        },
        {
            "raw": '45 Meter APU-Leiste montiert Eckschutzschiene gesetzt.',
            "acts": ('APU-Leisten montiert', 'Eckschutzprofile gesetzt'),
            "sugs": ('Klebeputz benutzt?',),
        },
        {
            "raw": '45 Quadratmeter Außenputz Kratzputz Reibputz Putz filziert.',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert'),
            "mats": ('Reibputz',),
            "sugs": ('Filzbrett benutzt?',),
        },
        {
            "raw": 'Sockelprofil 50 Millimeter montiert Tropfkante gesetzt.',
            "acts": ('Sockelprofile montiert', 'Tropfkantenprofile gesetzt'),
            "mats": ('Sockelprofil',),
            "sugs": ('Sockeldämmung benutzt?',),
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 50 Fenster Problem Material fehlt Offen Rest Donnerstag.',
            "acts": ('Leibungsprofile gesetzt',),
            "mats": ('Leibungsprofil',),
            "sugs": ('Klebeputz benutzt?',),
            "prob_must": ('material',),
            "open_must": ('donnerstag',),
            "problem": True,
            "open_": True,
        },
        {
            "raw": '50 Quadratmeter Innenputz Gipsputz aufgetragen.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "sugs": ('Putzmaschine benutzt?',),
        },
        {
            "raw": '55 Quadratmeter WDVS Dämmung geklebt EPS 70 Millimeter.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "sugs": ('Zahntraufel benutzt?',),
        },
        {
            "raw": 'Putz geglättet 55 Quadratmeter Feinputz Decke.',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "sugs": ('Glättkelle benutzt?',),
            "forbid_sugs": ('Feinputz benutzt?',),
        },
        {
            "raw": 'WDVS gedübelt 55 Quadratmeter Tellerdübel gesetzt.',
            "acts": ('WDVS gedübelt',),
            "mats": ('Tellerdübel',),
            "forbid_sugs": ('Tellerdübel benutzt?',),
        },
        {
            "raw": '60 Meter APU-Leiste montiert Eckschutzschiene gesetzt.',
            "acts": ('APU-Leisten montiert', 'Eckschutzprofile gesetzt'),
            "sugs": ('Klebeputz benutzt?',),
        },
        {
            "raw": '60 Quadratmeter Außenputz Kratzputz Reibputz Putz filziert.',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert'),
            "mats": ('Reibputz',),
            "sugs": ('Filzbrett benutzt?',),
        },
        {
            "raw": 'Sockelprofil 60 Millimeter montiert Tropfkante gesetzt.',
            "acts": ('Sockelprofile montiert', 'Tropfkantenprofile gesetzt'),
            "mats": ('Sockelprofil',),
            "sugs": ('Sockeldämmung benutzt?',),
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 65 Fenster Problem Material fehlt Offen Rest Donnerstag.',
            "acts": ('Leibungsprofile gesetzt',),
            "mats": ('Leibungsprofil',),
            "sugs": ('Klebeputz benutzt?',),
            "prob_must": ('material',),
            "open_must": ('donnerstag',),
            "problem": True,
            "open_": True,
        },
        {
            "raw": '65 Quadratmeter Innenputz Gipsputz aufgetragen.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "sugs": ('Putzmaschine benutzt?',),
        },
        {
            "raw": '65 Quadratmeter WDVS Dämmung geklebt EPS 80 Millimeter.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "sugs": ('Zahntraufel benutzt?',),
        },
        {
            "raw": 'Putz geglättet 70 Quadratmeter Feinputz Decke.',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "sugs": ('Glättkelle benutzt?',),
            "forbid_sugs": ('Feinputz benutzt?',),
        },
        {
            "raw": 'WDVS gedübelt 70 Quadratmeter Tellerdübel gesetzt.',
            "acts": ('WDVS gedübelt',),
            "mats": ('Tellerdübel',),
            "forbid_sugs": ('Tellerdübel benutzt?',),
        },
        {
            "raw": '70 Meter APU-Leiste montiert Eckschutzschiene gesetzt.',
            "acts": ('APU-Leisten montiert', 'Eckschutzprofile gesetzt'),
            "sugs": ('Klebeputz benutzt?',),
        },
        {
            "raw": '75 Quadratmeter Außenputz Kratzputz Reibputz Putz filziert.',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert'),
            "mats": ('Reibputz',),
            "sugs": ('Filzbrett benutzt?',),
        },
        {
            "raw": 'Sockelprofil 75 Millimeter montiert Tropfkante gesetzt.',
            "acts": ('Sockelprofile montiert', 'Tropfkantenprofile gesetzt'),
            "mats": ('Sockelprofil',),
            "sugs": ('Sockeldämmung benutzt?',),
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 75 Fenster Problem Material fehlt Offen Rest Donnerstag.',
            "acts": ('Leibungsprofile gesetzt',),
            "mats": ('Leibungsprofil',),
            "sugs": ('Klebeputz benutzt?',),
            "prob_must": ('material',),
            "open_must": ('donnerstag',),
            "problem": True,
            "open_": True,
        },
        {
            "raw": '80 Quadratmeter Innenputz Gipsputz aufgetragen.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "sugs": ('Putzmaschine benutzt?',),
        },
        {
            "raw": '80 Quadratmeter WDVS Dämmung geklebt EPS 95 Millimeter.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "sugs": ('Zahntraufel benutzt?',),
        },
        {
            "raw": 'Putz geglättet 80 Quadratmeter Feinputz Decke.',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "sugs": ('Glättkelle benutzt?',),
            "forbid_sugs": ('Feinputz benutzt?',),
        },
        {
            "raw": 'WDVS gedübelt 85 Quadratmeter Tellerdübel gesetzt.',
            "acts": ('WDVS gedübelt',),
            "mats": ('Tellerdübel',),
            "forbid_sugs": ('Tellerdübel benutzt?',),
        },
        {
            "raw": '85 Meter APU-Leiste montiert Eckschutzschiene gesetzt.',
            "acts": ('APU-Leisten montiert', 'Eckschutzprofile gesetzt'),
            "sugs": ('Klebeputz benutzt?',),
        },
        {
            "raw": '85 Quadratmeter Außenputz Kratzputz Reibputz Putz filziert.',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert'),
            "mats": ('Reibputz',),
            "sugs": ('Filzbrett benutzt?',),
        },
        {
            "raw": 'Sockelprofil 90 Millimeter montiert Tropfkante gesetzt.',
            "acts": ('Sockelprofile montiert', 'Tropfkantenprofile gesetzt'),
            "mats": ('Sockelprofil',),
            "sugs": ('Sockeldämmung benutzt?',),
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 90 Fenster Problem Material fehlt Offen Rest Donnerstag.',
            "acts": ('Leibungsprofile gesetzt',),
            "mats": ('Leibungsprofil',),
            "sugs": ('Klebeputz benutzt?',),
            "prob_must": ('material',),
            "open_must": ('donnerstag',),
            "problem": True,
            "open_": True,
        },
        {
            "raw": '90 Quadratmeter Innenputz Gipsputz aufgetragen.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "sugs": ('Putzmaschine benutzt?',),
        },
        {
            "raw": '95 Quadratmeter WDVS Dämmung geklebt EPS 110 Millimeter.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "sugs": ('Zahntraufel benutzt?',),
        },
        {
            "raw": 'Putz geglättet 95 Quadratmeter Feinputz Decke.',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "sugs": ('Glättkelle benutzt?',),
            "forbid_sugs": ('Feinputz benutzt?',),
        },
        {
            "raw": 'WDVS gedübelt 95 Quadratmeter Tellerdübel gesetzt.',
            "acts": ('WDVS gedübelt',),
            "mats": ('Tellerdübel',),
            "forbid_sugs": ('Tellerdübel benutzt?',),
        },
        {
            "raw": '100 Meter APU-Leiste montiert Eckschutzschiene gesetzt.',
            "acts": ('APU-Leisten montiert', 'Eckschutzprofile gesetzt'),
            "sugs": ('Klebeputz benutzt?',),
        },
        {
            "raw": '100 Quadratmeter Außenputz Kratzputz Reibputz Putz filziert.',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert'),
            "mats": ('Reibputz',),
            "sugs": ('Filzbrett benutzt?',),
        },
        {
            "raw": 'Sockelprofil 100 Millimeter montiert Tropfkante gesetzt.',
            "acts": ('Sockelprofile montiert', 'Tropfkantenprofile gesetzt'),
            "mats": ('Sockelprofil',),
            "sugs": ('Sockeldämmung benutzt?',),
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 105 Fenster Problem Material fehlt Offen Rest Donnerstag.',
            "acts": ('Leibungsprofile gesetzt',),
            "mats": ('Leibungsprofil',),
            "sugs": ('Klebeputz benutzt?',),
            "prob_must": ('material',),
            "open_must": ('donnerstag',),
            "problem": True,
            "open_": True,
        },
        {
            "raw": '105 Quadratmeter Innenputz Gipsputz aufgetragen.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "sugs": ('Putzmaschine benutzt?',),
        },
        {
            "raw": '105 Quadratmeter WDVS Dämmung geklebt EPS 120 Millimeter.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "sugs": ('Zahntraufel benutzt?',),
        },
        {
            "raw": 'Putz geglättet 110 Quadratmeter Feinputz Decke.',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "sugs": ('Glättkelle benutzt?',),
            "forbid_sugs": ('Feinputz benutzt?',),
        },
        {
            "raw": 'WDVS gedübelt 110 Quadratmeter Tellerdübel gesetzt.',
            "acts": ('WDVS gedübelt',),
            "mats": ('Tellerdübel',),
            "forbid_sugs": ('Tellerdübel benutzt?',),
        },
        {
            "raw": '110 Meter APU-Leiste montiert Eckschutzschiene gesetzt.',
            "acts": ('APU-Leisten montiert', 'Eckschutzprofile gesetzt'),
            "sugs": ('Klebeputz benutzt?',),
        },
        {
            "raw": '115 Quadratmeter Außenputz Kratzputz Reibputz Putz filziert.',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert'),
            "mats": ('Reibputz',),
            "sugs": ('Filzbrett benutzt?',),
        },
        {
            "raw": 'Sockelprofil 115 Millimeter montiert Tropfkante gesetzt.',
            "acts": ('Sockelprofile montiert', 'Tropfkantenprofile gesetzt'),
            "mats": ('Sockelprofil',),
            "sugs": ('Sockeldämmung benutzt?',),
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 115 Fenster Problem Material fehlt Offen Rest Donnerstag.',
            "acts": ('Leibungsprofile gesetzt',),
            "mats": ('Leibungsprofil',),
            "sugs": ('Klebeputz benutzt?',),
            "prob_must": ('material',),
            "open_must": ('donnerstag',),
            "problem": True,
            "open_": True,
        },
        {
            "raw": '120 Quadratmeter Innenputz Gipsputz aufgetragen.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "sugs": ('Putzmaschine benutzt?',),
        },
        {
            "raw": '120 Quadratmeter WDVS Dämmung geklebt EPS 135 Millimeter.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "sugs": ('Zahntraufel benutzt?',),
        },
    ]
