"""Putz & Stuck Welle 21 — 300 Basisszenarien (generiert)."""

from __future__ import annotations


def all_base_scenarios() -> list[dict]:
    return [
        {
            "raw": 'Nieheim Stuckgesims montiert PU-Profil 24 Meter Wohnzimmer Decke.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "sugs": ('Montagekleber benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Gips-Stuckprofil stuckiert Rosette angebracht Steinheim Salon.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "mats": ('Gips-Stuckprofil',),
            "sugs": ('Feinspachtel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Stuckarbeiten Gesims stuckiert mit Montagekleber Borgentreich Flur OG.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "forbid_sugs": ('Montagekleber benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'PU-Stuckprofil Fensterlaibung stuckiert Feinspachtel nachgearbeitet Willebadessen.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "mats": ('PU-Stuckprofil',),
            "forbid_sugs": ('Feinspachtel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Morgens Bad Karlshafen Innenputz Kalkputz 58 qm² nachmittags Oberputz geglättet abends Stuck Gesims stuckiert Kunde wünscht gleiche Leiste im Flur.',
            "acts": ('Innenputz aufgetragen', 'Stuckarbeiten durchgeführt'),
            "mats": ('Kalkputz',),
            "cust_must": ('wünscht', 'flur'),
            "sum_qty": ('58',),
            "customer": True,
            "min_act": 2,
        },
        {
            "raw": 'WDVS Nieheim 88 qm geklebt gedübelt Armierung Reibputz Problem Kleber zu schnell wegen Hitze Offen Nordwand Donnerstag Bauherr informiert.',
            "acts": ('WDVS gedübelt', 'Armierung ausgeführt'),
            "prob_must": ('hitze', 'kleber'),
            "open_must": ('donnerstag', 'offen'),
            "cust_must": ('informiert',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 2,
        },
        {
            "raw": 'Also heute Steinheim erst Altputz runter dann Wand geschliffen Grundierung Unterputz 44 qm und Oberputz 22 qm und Kundengespräch wegen Farbton.',
            "acts": ('Altputz entfernt', 'Oberputz aufgetragen', 'Unterputz aufgetragen', 'Wand geschliffen', 'Grundierung aufgetragen'),
            "cust_must": ('kundengespräch',),
            "sum_qty": ('44', '22'),
            "customer": True,
            "min_act": 5,
        },
        {
            "raw": 'innenputz lehmputz 36 qm Borgentreich altbau',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Lehmputz',),
            "sum_qty": ('36',),
            "min_act": 1,
        },
        {
            "raw": 'hamma wdvs kleben und dübeln Willebadessen 102 qm',
            "acts": ('WDVS Dämmung geklebt', 'WDVS gedübelt'),
            "min_act": 2,
        },
        {
            "raw": 'problem lieferant offen montag kein gipsputz Bad Karlshafen',
            "acts": (),
            "prob_must": ('liefer',),
            "open_must": ('montag', 'offen'),
            "min_act": 0,
        },
        {
            "raw": 'bauherr gred wegen stuck profil Nieheim',
            "acts": (),
            "cust_must": ('bauherr', 'gred'),
            "min_act": 0,
        },
        {
            "raw": 'Kompletttag Steinheim: Sockelprofil Tropfkante APU-Leiste Leibungsprofil Eckschutz WDVS Armierung Reibputz Kratzputz filziert.',
            "acts": ('Kratzputz aufgetragen', 'Armierung ausgeführt'),
            "min_act": 2,
        },
        {
            "raw": 'Sanierung Borgentreich Schimmel weg Sanierputz Unterputz Oberputz 31 qm fertig.',
            "acts": ('Sanierputz aufgebracht',),
            "mats": ('Sanierputz',),
            "sum_qty": ('31',),
            "min_act": 1,
        },
        {
            "raw": 'Außenputz Silikonharzputz 77 qm Kratzputz strukturiert Willebadessen Giebel.',
            "acts": ('Außenputz aufgetragen',),
            "mats": ('Silikonharzputz',),
            "min_act": 1,
        },
        {
            "raw": 'Putzmaschine 7 std Innenputz Gipsputz 93 qm Bad Karlshafen Neubau Block A.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "mach": ('Putzmaschine',),
            "forbid_sugs": ('Putzmaschine benutzt?',),
            "sum_qty": ('93',),
            "min_act": 1,
        },
        {
            "raw": 'Fassade Nieheim Mineralwolle WDVS geklebt Schraubdübel Armierungsgewebe Reibputz Problem Gewebe falsch Offen Austausch Mittwoch.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('Mineralwolle',),
            "prob_must": ('falsch',),
            "open_must": ('mittwoch', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Grundputz 48 qm Unterputz 48 qm Oberputz glatt Steinheim Treppenhaus komplett.',
            "acts": ('Oberputz aufgetragen', 'Unterputz aufgetragen'),
            "sum_qty": ('48',),
            "min_act": 2,
        },
        {
            "raw": 'Kalkfeinputz Putz geglättet 29 qm Decke Borgentreich mit Glättkelle fertig.',
            "acts": ('Putz geglättet',),
            "forbid_sugs": ('Glättkelle benutzt?', 'Kalkfeinputz benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Stuckarbeiten Willebadessen Gesims stuckiert Problem Profilbruch Offen Ersatz Mittwoch Kunde einverstanden.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "prob_must": ('bruch',),
            "open_must": ('mittwoch', 'offen'),
            "cust_must": ('einverstanden',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'wdvs armierung reibputz drauf 66 qm Bad Karlshafen',
            "acts": ('Reibputz aufgetragen', 'Armierung ausgeführt'),
            "sum_qty": ('66',),
            "min_act": 2,
        },
        {
            "raw": 'Heute nur Besichtigung Nieheim mit Bauherr Problem Zugang gesperrt Offen Start Montag Termin abgestimmt.',
            "acts": (),
            "prob_must": ('gesperrt',),
            "open_must": ('montag', 'offen'),
            "cust_must": ('abgestimmt', 'bauherr'),
            "min_act": 0,
        },
        {
            "raw": 'Holzfaserplatten WDVS geklebt 54 qm Steinheim Innenseite Dämmung.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('Holzfaserplatten',),
            "sugs": ('Zahntraufel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Kalkzementputz Außenputz 83 qm Haftbrücke vorher Borgentreich Südseite.',
            "acts": ('Außenputz aufgetragen',),
            "mats": ('Kalkzementputz',),
            "forbid_sugs": ('Haftbrücke benutzt?',),
            "sum_qty": ('83',),
            "min_act": 1,
        },
        {
            "raw": 'Megabericht Willebadessen: Altputz ab geschliffen grundiert Unterputz Oberputz Stuck Rosette WDVS kleben dübeln Armierung Reibputz Problem Regen Offen Außenputz Freitag Bauleitung informiert.',
            "acts": ('Altputz entfernt', 'WDVS gedübelt', 'Grundierung aufgetragen'),
            "prob_must": ('regen',),
            "open_must": ('freitag', 'offen'),
            "cust_must": ('informiert',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 3,
        },
        {
            "raw": 'heute haben wir 50qm² Oberputz aufgetragen',
            "acts": ('Oberputz aufgetragen',),
            "sum_qty": ('50',),
            "min_act": 1,
        },
        {
            "raw": 'Nieheim heute 50 qm² Oberputz aufgetragen Wohnzimmer fertig.',
            "acts": ('Oberputz aufgetragen',),
            "sum_qty": ('50',),
            "min_act": 1,
        },
        {
            "raw": '50 Quadratmeter Oberputz aufgetragen Decke OG.',
            "acts": ('Oberputz aufgetragen',),
            "sum_qty": ('50',),
            "min_act": 1,
        },
        {
            "raw": 'Oberputz 50 m² aufgetragen Innenwand Flur.',
            "acts": ('Oberputz aufgetragen',),
            "sum_qty": ('50',),
            "min_act": 1,
        },
        {
            "raw": 'heute 50qm² Oberputz drauf gemacht Schlafzimmer.',
            "acts": ('Oberputz aufgetragen',),
            "sum_qty": ('50',),
            "min_act": 1,
        },
        {
            "raw": 'Unterputz 72 Quadratmeter aufgetragen Steinheim Treppenhaus.',
            "acts": ('Unterputz aufgetragen',),
            "sum_qty": ('72',),
            "min_act": 1,
        },
        {
            "raw": '72 qm² Unterputz aufgetragen heute komplett.',
            "acts": ('Unterputz aufgetragen',),
            "sum_qty": ('72',),
            "min_act": 1,
        },
        {
            "raw": 'Unterputz 72 m² verarbeitet Kellerwand.',
            "acts": ('Unterputz aufgetragen',),
            "sum_qty": ('72',),
            "min_act": 1,
        },
        {
            "raw": 'Borgentreich 85 Quadratmeter Innenputz mit Gipsputz aufgetragen.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "sum_qty": ('85',),
            "min_act": 1,
        },
        {
            "raw": 'Innenputz 85 qm² Gipsputz Wohnbereich fertig.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "sum_qty": ('85',),
            "min_act": 1,
        },
        {
            "raw": '85 m² Innenputz aufgetragen mit Gipsputz.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "sum_qty": ('85',),
            "min_act": 1,
        },
        {
            "raw": 'Außenputz 120 Quadratmeter Kratzputz Fassade Willebadessen.',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": '120 qm² Außenputz Kratzputz Nordseite aufgetragen.',
            "acts": ('Außenputz aufgetragen', 'Kratzputz aufgetragen'),
            "sum_qty": ('120',),
            "min_act": 2,
        },
        {
            "raw": 'Außenputz 120 m² Kratzputz verarbeitet.',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": 'Reibputz 95 Quadratmeter aufgetragen WDVS Bad Karlshafen.',
            "acts": ('Reibputz aufgetragen',),
            "sum_qty": ('95',),
            "min_act": 1,
        },
        {
            "raw": '95 qm² Reibputz drauf Armierung fertig.',
            "acts": ('Reibputz aufgetragen', 'Armierung ausgeführt'),
            "sum_qty": ('95',),
            "min_act": 2,
        },
        {
            "raw": 'Reibputz 95 m² Fassade Süd aufgetragen.',
            "acts": ('Reibputz aufgetragen',),
            "sum_qty": ('95',),
            "min_act": 1,
        },
        {
            "raw": 'Nieheim 60 Quadratmeter Kalkputz Innenputz aufgetragen.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Kalkputz',),
            "sum_qty": ('60',),
            "min_act": 1,
        },
        {
            "raw": 'Innenputz 60 qm² Kalkputz Altbau Wohnzimmer.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Kalkputz',),
            "sum_qty": ('60',),
            "min_act": 1,
        },
        {
            "raw": '60 m² Kalkputz Innenputz verarbeitet.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Kalkputz',),
            "sum_qty": ('60',),
            "min_act": 1,
        },
        {
            "raw": 'WDVS Dämmung geklebt 140 Quadratmeter EPS Steinheim.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "min_act": 1,
        },
        {
            "raw": '140 qm² WDVS geklebt Fassade West.',
            "acts": ('WDVS Dämmung geklebt',),
            "min_act": 1,
        },
        {
            "raw": 'WDVS 140 m² Dämmung angeklebt.',
            "acts": ('WDVS ausgeführt',),
            "min_act": 1,
        },
        {
            "raw": 'Putz geglättet 38 Quadratmeter Feinputz Borgentreich.',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "min_act": 1,
        },
        {
            "raw": '38 qm² Putz geglättet Decke.',
            "acts": ('Putz geglättet',),
            "min_act": 1,
        },
        {
            "raw": 'Putz geglättet 38 m² Feinputz.',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "min_act": 1,
        },
        {
            "raw": 'Sockelputz 22 Quadratmeter aufgetragen Willebadessen Keller.',
            "acts": ('Sockelputz aufgetragen',),
            "sum_qty": ('22',),
            "min_act": 1,
        },
        {
            "raw": '22 qm² Sockelputz verarbeitet.',
            "acts": ('Sockelputz aufgetragen',),
            "sum_qty": ('22',),
            "min_act": 1,
        },
        {
            "raw": 'Sockelputz 22 m² fertig.',
            "acts": ('Sockelputz aufgetragen',),
            "sum_qty": ('22',),
            "min_act": 1,
        },
        {
            "raw": 'Grundputz 55 Quadratmeter aufgetragen Neubau Bad Karlshafen.',
            "acts": ('Grundputz aufgetragen',),
            "sum_qty": ('55',),
            "min_act": 1,
        },
        {
            "raw": '55 qm² Grundputz drauf Wand.',
            "acts": ('Grundputz aufgetragen',),
            "sum_qty": ('55',),
            "min_act": 1,
        },
        {
            "raw": 'Grundputz 55 m² verarbeitet.',
            "acts": ('Grundputz aufgetragen',),
            "sum_qty": ('55',),
            "min_act": 1,
        },
        {
            "raw": 'Sanierputz 18 Quadratmeter aufgebracht Schimmelstelle Nieheim.',
            "acts": ('Sanierputz aufgebracht',),
            "mats": ('Sanierputz',),
            "sum_qty": ('18',),
            "min_act": 1,
        },
        {
            "raw": '18 qm² Sanierputz Kellerwand.',
            "acts": ('Sanierputz aufgebracht',),
            "mats": ('Sanierputz',),
            "min_act": 1,
        },
        {
            "raw": 'Sanierputz 18 m² verarbeitet.',
            "acts": ('Sanierputz aufgebracht',),
            "mats": ('Sanierputz',),
            "sum_qty": ('18',),
            "min_act": 1,
        },
        {
            "raw": 'Lehmputz 42 Quadratmeter Innenputz Steinheim Wohnbereich.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Lehmputz',),
            "sum_qty": ('42',),
            "min_act": 1,
        },
        {
            "raw": '42 qm² Lehmputz aufgetragen.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Lehmputz',),
            "min_act": 1,
        },
        {
            "raw": 'Lehmputz 42 m² verarbeitet.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Lehmputz',),
            "min_act": 1,
        },
        {
            "raw": 'Silikatputz 110 Quadratmeter Außenputz Borgentreich Fassade.',
            "acts": ('Außenputz aufgetragen',),
            "mats": ('Silikatputz',),
            "sum_qty": ('110',),
            "min_act": 1,
        },
        {
            "raw": '110 qm² Silikatputz Außenwand.',
            "acts": ('Außenputz aufgetragen',),
            "mats": ('Silikatputz',),
            "sum_qty": ('110',),
            "min_act": 1,
        },
        {
            "raw": 'Silikatputz 110 m² verarbeitet.',
            "acts": ('Außenputz aufgetragen',),
            "mats": ('Silikatputz',),
            "min_act": 1,
        },
        {
            "raw": 'Kratzputz 78 Quadratmeter Putz filziert Willebadessen.',
            "acts": ('Putz filziert',),
            "min_act": 1,
        },
        {
            "raw": '78 qm² Kratzputz filziert Fassade.',
            "acts": ('Putz filziert',),
            "min_act": 1,
        },
        {
            "raw": 'Kratzputz 78 m² strukturiert Putz filziert.',
            "acts": ('Putz filziert',),
            "min_act": 1,
        },
        {
            "raw": 'heute 67qm² Innenputz Gipsputz und 33 qm² Oberputz glatt Bad Karlshafen.',
            "acts": ('Oberputz aufgetragen', 'Innenputz aufgetragen'),
            "mats": ('Gipsputz',),
            "sum_qty": ('67', '33'),
            "min_act": 2,
        },
        {
            "raw": 'Nieheim Innenputz mit Gipsputz aufgetragen 120 Quadratmeter fertig.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "sugs": ('Putzmaschine benutzt?', 'Kartätsche benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Außenputz Silikatputz aufgetragen Fassade Steinheim Nordseite.',
            "acts": ('Außenputz aufgetragen',),
            "mats": ('Silikatputz',),
            "sugs": ('Haftbrücke benutzt?', 'Putzmaschine benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Putz geglättet mit Feinputz Decke OG fertig.',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "sugs": ('Glättkelle benutzt?',),
            "forbid_sugs": ('Feinputz benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Außenputz Kratzputz aufgetragen Putz filziert Fassade fertig.',
            "acts": ('Außenputz aufgetragen', 'Kratzputz aufgetragen', 'Putz filziert'),
            "sugs": ('Filzbrett benutzt?',),
            "min_act": 3,
        },
        {
            "raw": 'WDVS Dämmung geklebt EPS-Dämmplatten Fassade Süd.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "sugs": ('Zahntraufel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'WDVS gedübelt an der Fassade komplett.',
            "acts": ('WDVS gedübelt',),
            "min_act": 1,
        },
        {
            "raw": 'Armierungsgewebe eingebettet WDVS Armierung fertig.',
            "acts": ('Armierung ausgeführt',),
            "mats": ('Armierungsgewebe',),
            "sugs": ('Armierungsmörtel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Eckschutzschiene gesetzt an allen Außenecken.',
            "acts": ('Eckschutzprofile gesetzt',),
            "sugs": ('Klebeputz benutzt?', 'Spachtelmasse benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'APU-Leiste montiert Fensteranschluss Nord.',
            "acts": ('APU-Leisten montiert',),
            "sugs": ('Klebeputz benutzt?', 'Dichtlippe benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 14 Fenster.',
            "acts": ('Leibungsprofile gesetzt',),
            "mats": ('Leibungsprofil',),
            "sugs": ('Klebeputz benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Sockelprofil montiert Sockelzone komplett.',
            "acts": ('Sockelprofile montiert',),
            "sugs": ('Sockeldämmung benutzt?', 'Noppenbahn benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Tropfkantenprofil gesetzt Gesimsabschluss.',
            "acts": ('Tropfkantenprofile gesetzt',),
            "sugs": ('Klebeputz benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Altputz entfernt Wand geschliffen Grundierung drauf.',
            "acts": ('Altputz entfernt', 'Wand geschliffen', 'Grundierung aufgetragen'),
            "sugs": ('Entsorgungssäcke benutzt?',),
            "min_act": 3,
        },
        {
            "raw": 'Schimmel beseitigt Sanierputz aufgebracht.',
            "acts": ('Sanierputz aufgebracht', 'Schimmel beseitigt'),
            "mats": ('Sanierputz',),
            "sugs": ('Schimmelentferner benutzt?',),
            "min_act": 2,
        },
        {
            "raw": 'Oberputz aufgetragen. Wand war trocken.',
            "acts": ('Oberputz aufgetragen',),
            "sugs": ('Grundierung benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Stuckarbeiten gemacht Gesims stuckiert Rosette angebracht.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "sugs": ('Montagekleber benutzt?', 'Feinspachtel benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Reibputz aufgetragen WDVS Schicht Borgentreich.',
            "acts": ('Reibputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": 'Unterputz aufgetragen Grundputz vorher fertig.',
            "acts": ('Unterputz aufgetragen', 'Grundputz aufgetragen'),
            "min_act": 2,
        },
        {
            "raw": 'Sockelputz aufgetragen Kellerwand.',
            "acts": ('Sockelputz aufgetragen',),
            "sugs": ('Grundierung benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Morgens Nieheim WDVS Dämmung geklebt mittags WDVS gedübelt nachmittags Armierungsgewebe eingebettet.',
            "acts": ('WDVS Dämmung geklebt', 'WDVS gedübelt', 'Armierung ausgeführt'),
            "sugs": ('Zahntraufel benutzt?',),
            "min_act": 3,
        },
        {
            "raw": 'Komplett Fassade Steinheim: Sockelprofil montiert APU-Leisten montiert Leibungsprofile gesetzt Eckschutzprofile gesetzt.',
            "acts": ('Sockelprofile montiert', 'APU-Leisten montiert', 'Leibungsprofile gesetzt', 'Eckschutzprofile gesetzt'),
            "sugs": ('Klebeputz benutzt?',),
            "min_act": 4,
        },
        {
            "raw": 'Innenputz Kalkputz aufgetragen 65 Quadratmeter Treppenhaus.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Kalkputz',),
            "sugs": ('Putzmaschine benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Silikonharzputz verarbeitet Außenputz strukturiert.',
            "acts": ('Außenputz aufgetragen',),
            "mats": ('Silikonharzputz',),
            "sugs": ('Haftbrücke benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Oberputz glatt Putz geglättet Innenwand Wohnzimmer.',
            "acts": ('Oberputz aufgetragen', 'Putz geglättet'),
            "sugs": ('Glättkelle benutzt?', 'Schwammbrett benutzt?'),
            "min_act": 2,
        },
        {
            "raw": 'Fassadenarmierung ausgeführt an Hotel-Fassade.',
            "acts": ('Armierung ausgeführt',),
            "sugs": ('Armierungsmörtel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Willebadessen Mineralwolle WDVS Dämmung geklebt Fassade Ost.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('Mineralwolle',),
            "sugs": ('Zahntraufel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Kalkzementputz aufgetragen Außenputz Bad Karlshafen Giebel.',
            "acts": ('Außenputz aufgetragen',),
            "mats": ('Kalkzementputz',),
            "sugs": ('Haftbrücke benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Grundputz aufgetragen Neubau Innenwand Block B.',
            "acts": ('Grundputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": 'Haftgrund aufgetragen vor Außenputz Fassade.',
            "acts": ('Außenputz aufgetragen',),
            "min_act": 1,
        },
        {
            "raw": 'Gips-Stuckprofil stuckiert Gesims Wohnzimmer.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "mats": ('Gips-Stuckprofil',),
            "sugs": ('Montagekleber benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'PU-Stuckprofil montiert Fensterlaibung.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "mats": ('PU-Stuckprofil',),
            "sugs": ('Montagekleber benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'WDVS ausgeführt Borgentreich komplett Dämmung Armierung Reibputz.',
            "acts": ('Reibputz aufgetragen', 'Armierung ausgeführt'),
            "min_act": 2,
        },
        {
            "raw": 'Anputzleiste montiert Fensterbank Außen.',
            "acts": ('APU-Leisten montiert',),
            "sugs": ('Klebeputz benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Dichtlippe gesetzt Fensteranschluss WDVS.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'Noppenbahn verlegt Sockelzone vor Sockelprofil.',
            "acts": ('Abdichtung eingebaut',),
            "min_act": 1,
        },
        {
            "raw": 'Lehmputz aufgetragen Innenputz Nieheim Altbau.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Lehmputz',),
            "sugs": ('Putzmaschine benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Kalkfeinputz verarbeitet Putz geglättet Decke.',
            "acts": ('Putz geglättet',),
            "sugs": ('Glättkelle benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Holzfaserplatten geklebt WDVS Innenseite.',
            "acts": (),
            "mats": ('Holzfaserplatten',),
            "min_act": 0,
        },
        {
            "raw": 'Gewebeeinlage an Brüstung Armierung Steinheim.',
            "acts": ('Armierung ausgeführt',),
            "min_act": 1,
        },
        {
            "raw": 'Schwammbrett Struktur Außenputz fein.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'Putz geglättet mit Glättkelle und Feinputz fertig.',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "forbid_sugs": ('Glättkelle benutzt?', 'Feinputz benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Putz filziert mit Filzbrett Außenwand strukturiert.',
            "acts": ('Putz filziert',),
            "forbid_sugs": ('Filzbrett benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'WDVS gedübelt mit Tellerdübel 6 pro Quadratmeter.',
            "acts": ('WDVS gedübelt',),
            "mats": ('Tellerdübel',),
            "forbid_sugs": ('Tellerdübel benutzt?', 'Schraubdübel benutzt?', 'Schlagdübel benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'WDVS Dämmung geklebt mit Zahntraufel und Klebe- und Armierungsmörtel.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('Klebe- und Armierungsmörtel',),
            "forbid_sugs": ('Zahntraufel benutzt?', 'Klebe- und Armierungsmörtel benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Eckschutzprofile gesetzt mit Klebeputz und Spachtelmasse.',
            "acts": ('Eckschutzprofile gesetzt', 'Spachtelarbeiten durchgeführt'),
            "mats": ('Klebeputz', 'Spachtelmasse'),
            "forbid_sugs": ('Klebeputz benutzt?', 'Spachtelmasse benutzt?'),
            "min_act": 2,
        },
        {
            "raw": 'APU-Leiste montiert Klebeputz verarbeitet Dichtlippe gesetzt.',
            "acts": ('APU-Leisten montiert',),
            "mats": ('Klebeputz',),
            "forbid_sugs": ('Klebeputz benutzt?', 'Dichtlippe benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Sockelprofil montiert Sockeldämmung und Noppenbahn drunter.',
            "acts": ('Sockelprofile montiert',),
            "forbid_sugs": ('Sockeldämmung benutzt?', 'Noppenbahn benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Innenputz mit Putzmaschine aufgetragen Gipsputz 90 Quadratmeter.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "forbid_sugs": ('Putzmaschine benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Innenputz mit Kartätsche gezogen Kalkputz Wand.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Kalkputz',),
            "forbid_sugs": ('Kartätsche benutzt?', 'Putzmaschine benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Außenputz mit Haftbrücke vorbereitet Silikatputz aufgetragen.',
            "acts": ('Außenputz aufgetragen',),
            "mats": ('Silikatputz',),
            "forbid_sugs": ('Haftbrücke benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Schimmel beseitigt mit Schimmelentferner. Sanierputz drauf.',
            "acts": ('Sanierputz aufgebracht', 'Schimmel beseitigt'),
            "mats": ('Sanierputz',),
            "forbid_sugs": ('Schimmelentferner benutzt?',),
            "min_act": 2,
        },
        {
            "raw": 'Stuckarbeiten mit Montagekleber und Feinspachtel fertig.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "forbid_sugs": ('Montagekleber benutzt?', 'Feinspachtel benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Armierungsgewebe eingebettet Armierungsmörtel verarbeitet.',
            "acts": ('Armierung ausgeführt',),
            "mats": ('Armierungsmörtel', 'Armierungsgewebe'),
            "forbid_sugs": ('Armierungsmörtel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Leibungsprofil gesetzt Klebeputz und Dichtlippe eingesetzt.',
            "acts": ('Leibungsprofile gesetzt',),
            "mats": ('Klebeputz',),
            "forbid_sugs": ('Klebeputz benutzt?', 'Dichtlippe benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Tropfkantenprofil gesetzt Klebeputz Armierungsgewebe an Ecke.',
            "acts": ('Tropfkantenprofile gesetzt',),
            "mats": ('Klebeputz',),
            "forbid_sugs": ('Klebeputz benutzt?', 'Armierung benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Altputz runter Entsorgungssäcke voll Container bestellt.',
            "acts": ('Altputz entfernt',),
            "forbid_sugs": ('Entsorgungssäcke benutzt?', 'Container benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Oberputz aufgetragen. Grundierung und Haftgrund vorher drauf.',
            "acts": ('Oberputz aufgetragen',),
            "mats": ('Grundierung', 'Haftgrund'),
            "forbid_sugs": ('Grundierung benutzt?', 'Haftgrund benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Putz filziert Schwammbrett benutzt Struktur fein.',
            "acts": ('Putz filziert',),
            "forbid_sugs": ('Filzbrett benutzt?', 'Schwammbrett benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'WDVS gedübelt Schlagdübel gesetzt Mineralwolle Platten.',
            "acts": ('WDVS gedübelt',),
            "forbid_sugs": ('Tellerdübel benutzt?', 'Schraubdübel benutzt?', 'Schlagdübel benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Außenputz Gewebeeinlage an Brüstung. Armierung ausgeführt.',
            "acts": ('Armierung ausgeführt',),
            "forbid_sugs": ('Gewebeeinlage benutzt?', 'Armierungsgewebe benutzt?'),
            "min_act": 1,
        },
        {
            "raw": 'Willebadessen Putzmaschine 8 std Innenputz Gipsputz aufgetragen.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "mach": ('Putzmaschine',),
            "forbid_sugs": ('Putzmaschine benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Kalkputz mit Kartätsche gezogen 70 Quadratmeter.',
            "acts": (),
            "mats": ('Kalkputz',),
            "forbid_sugs": ('Kartätsche benutzt?',),
            "min_act": 0,
        },
        {
            "raw": 'Zahntraufel WDVS Kleber verarbeitet EPS Platten.',
            "acts": (),
            "mats": ('EPS Dämmplatten',),
            "forbid_sugs": ('Zahntraufel benutzt?',),
            "min_act": 0,
        },
        {
            "raw": 'Montagekleber PU-Stuckprofil Gesims montiert.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "mats": ('PU-Stuckprofil',),
            "forbid_sugs": ('Montagekleber benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Haftbrücke und Silikonharzputz Außenputz Bad Karlshafen fertig.',
            "acts": ('Außenputz aufgetragen',),
            "mats": ('Silikonharzputz',),
            "forbid_sugs": ('Haftbrücke benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Nieheim Innenputz Gipsputz aufgetragen 80 Quadratmeter Problem Lieferung Gipsputz verspätet Offen Rest Flur Montag mit der Bauherrin gesprochen sie ist einverstanden.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "prob_must": ('liefer', 'verspät'),
            "prob_not": ('gipsputz aufgetragen', '80', 'quadratmeter'),
            "open_must": ('montag', 'flur', 'offen'),
            "open_not": ('gipsputz', '80'),
            "cust_must": ('einverstanden', 'bauherrin'),
            "cust_not": ('80', 'quadratmeter', 'aufgetragen'),
            "problem": True,
            "open_": True,
            "customer": True,
            "mat_echo": True,
            "min_act": 1,
        },
        {
            "raw": 'WDVS Dämmung geklebt Steinheim Problem Starkregen mussten abbrechen Offen letzte Fläche Donnerstag Bauleitung informiert.',
            "acts": ('WDVS Dämmung geklebt',),
            "prob_must": ('regen', 'abbrechen'),
            "prob_not": ('wdvs', 'geklebt'),
            "open_must": ('donnerstag', 'offen'),
            "cust_must": ('informiert',),
            "cust_not": ('geklebt',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Putz geglättet Oberputz aufgetragen Problem Putzmaschine defekt Offen Decke OG morgen Auftraggeber kurz da.',
            "acts": ('Oberputz aufgetragen', 'Putz geglättet'),
            "prob_must": ('defekt', 'putzmaschine'),
            "prob_not": ('geglättet', 'oberputz'),
            "open_must": ('decke', 'morgen', 'offen'),
            "cust_must": ('auftraggeber',),
            "cust_not": ('geglättet',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 2,
        },
        {
            "raw": 'Schimmel beseitigt Sanierputz aufgebracht Problem hohe Feuchte Offen Sanierung Keller nächste Woche.',
            "acts": ('Sanierputz aufgebracht', 'Schimmel beseitigt'),
            "mats": ('Sanierputz',),
            "prob_must": ('feuchte',),
            "open_must": ('keller', 'woche', 'offen'),
            "open_not": ('sanierputz',),
            "problem": True,
            "open_": True,
            "min_act": 2,
        },
        {
            "raw": 'Sockelprofil montiert APU-Leisten montiert Problem Material knapp Offen Rest Fenster morgen Kundengespräch Termin abgestimmt.',
            "acts": ('Sockelprofile montiert', 'APU-Leisten montiert'),
            "prob_must": ('material', 'knapp'),
            "open_must": ('fenster', 'morgen', 'offen'),
            "cust_must": ('abgestimmt', 'termin'),
            "cust_not": ('montiert', 'sockelprofil'),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 2,
        },
        {
            "raw": 'Fassade Borgentreich Kratzputz aufgetragen Putz filziert Problem Wind zu stark Offen Nordwestseite Freitag.',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert'),
            "prob_must": ('wind',),
            "prob_not": ('kratzputz', 'filziert'),
            "open_must": ('freitag', 'offen'),
            "open_not": ('kratzputz',),
            "problem": True,
            "open_": True,
            "min_act": 2,
        },
        {
            "raw": 'Heute nur mit dem Bauherr Rücksprache gehalten nächster Termin abgestimmt kein Putz wegen Frost.',
            "acts": (),
            "prob_must": ('frost',),
            "cust_must": ('rücksprache', 'abgestimmt'),
            "cust_not": ('aufgetragen', 'm²'),
            "min_act": 0,
        },
        {
            "raw": 'Altputz entfernt Wand geschliffen Problem Gerüst zu spät Offen Oberputz übermorgen Bauherr zufrieden.',
            "acts": ('Altputz entfernt', 'Wand geschliffen'),
            "prob_must": ('gerüst', 'spät'),
            "open_must": ('oberputz', 'offen'),
            "cust_must": ('zufrieden',),
            "cust_not": ('entfernt', 'geschiffen'),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 2,
        },
        {
            "raw": 'WDVS gedübelt Tellerdübel Problem Lieferant Tellerdübel fehlen Offen Nachlieferung Mittwoch.',
            "acts": ('WDVS gedübelt',),
            "mats": ('Tellerdübel',),
            "prob_must": ('fehlen', 'tellerdübel'),
            "prob_not": ('gedübelt',),
            "open_must": ('mittwoch', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Leibungsprofile gesetzt Problem Untergrund uneben was zu Problemen geführt hat Offen Korrektur Laibung Donnerstag Kunde informiert.',
            "acts": ('Leibungsprofile gesetzt',),
            "prob_must": ('uneben',),
            "prob_not": ('gesetzt',),
            "open_must": ('donnerstag', 'offen'),
            "cust_must": ('informiert',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Eckschutzprofile gesetzt Problem Kleber Lieferung verspätet Offen Fertigstellung nächste Woche.',
            "acts": ('Eckschutzprofile gesetzt',),
            "prob_must": ('kleber', 'liefer'),
            "open_must": ('woche', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Stuckarbeiten gemacht Gesims stuckiert mit dem Kunden unterhalten er wünscht gleiche Ausführung im Flur.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "cust_must": ('unterhalten', 'kunden'),
            "cust_not": ('stuckiert', 'gesims'),
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Innenputz aufgetragen Problem Temperatur zu niedrig Offen Rest Bad morgen.',
            "acts": ('Innenputz aufgetragen',),
            "prob_must": ('temperatur',),
            "prob_not": ('innenputz',),
            "open_must": ('bad', 'morgen', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Reibputz aufgetragen Armierung ausgeführt Problem Mörtelcharge schlecht Offen Nacharbeit Samstag Bauleitung kurz informiert.',
            "acts": ('Reibputz aufgetragen', 'Armierung ausgeführt'),
            "prob_must": ('mörtel', 'charge'),
            "open_must": ('samstag', 'offen'),
            "cust_must": ('informiert',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 2,
        },
        {
            "raw": 'Tropfkantenprofile gesetzt Offen Abschluss Gesims nächste Woche.',
            "acts": ('Tropfkantenprofile gesetzt',),
            "open_must": ('gesims', 'woche', 'offen'),
            "open_not": ('gesetzt',),
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Unterputz aufgetragen Oberputz aufgetragen Problem Feuchte Decke Offen Rest Montag.',
            "acts": ('Oberputz aufgetragen', 'Unterputz aufgetragen'),
            "prob_must": ('feuchte',),
            "prob_not": ('unterputz aufgetragen',),
            "open_must": ('montag', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 2,
        },
        {
            "raw": 'Also heute früh Nieheim WDVS kleben dann dübeln Problem Hitze Kleber zu schnell Offen Nordgiebel Donnerstag.',
            "acts": ('WDVS Dämmung geklebt', 'WDVS gedübelt'),
            "prob_must": ('hitze', 'kleber'),
            "open_must": ('donnerstag', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 2,
        },
        {
            "raw": 'Sockelputz aufgetragen Problem Untergrund nass Offen Trocknung abwarten Dienstag.',
            "acts": ('Sockelputz aufgetragen',),
            "prob_must": ('nass',),
            "open_must": ('dienstag', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Fassadenarmierung ausgeführt Reibputz drauf Bauherr war einverstanden und zufrieden.',
            "acts": ('Reibputz aufgetragen', 'Armierung ausgeführt'),
            "cust_must": ('zufrieden', 'einverstanden'),
            "cust_not": ('reibputz', 'armierung'),
            "customer": True,
            "min_act": 2,
        },
        {
            "raw": 'Problem Wetter Offen nächste Woche. Heute kein Außenputz.',
            "acts": (),
            "prob_must": ('wetter',),
            "open_must": ('woche', 'offen'),
            "min_act": 0,
        },
        {
            "raw": 'Willebadessen Außenputz Silikatputz 95 Quadratmeter Problem Lieferant zu spät Offen Rest Giebel Montag Bauherr informiert.',
            "acts": ('Außenputz aufgetragen',),
            "mats": ('Silikatputz',),
            "prob_must": ('liefer', 'spät'),
            "prob_not": ('95',),
            "open_must": ('montag', 'offen'),
            "cust_must": ('informiert',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'WDVS Armierung Bad Karlshafen Problem Gewebe falsch geliefert Offen Austausch Dienstag Kunde kurz angerufen.',
            "acts": ('Armierung ausgeführt',),
            "prob_must": ('falsch', 'geliefert'),
            "prob_not": ('armierung ausgeführt',),
            "open_must": ('dienstag', 'offen'),
            "cust_must": ('angerufen',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Grundputz aufgetragen Unterputz aufgetragen Problem Haarriss am Untergrund Offen Statiker Termin Freitag Bauleitung informiert.',
            "acts": ('Grundputz aufgetragen', 'Unterputz aufgetragen'),
            "prob_must": ('haarriss', 'untergrund'),
            "open_must": ('freitag', 'offen'),
            "cust_must": ('informiert',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 2,
        },
        {
            "raw": 'Leibungsprofile gesetzt Nieheim Problem Laibung zu schmal Offen Nacharbeit Fenster 12 Donnerstag.',
            "acts": ('Leibungsprofile gesetzt',),
            "prob_must": ('schmal',),
            "prob_not": ('gesetzt',),
            "open_must": ('donnerstag', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Putz filziert Kratzputz Problem Struktur ungleichmäßig Offen Nacharbeit Südseite morgen.',
            "acts": ('Putz filziert',),
            "prob_must": ('ungleichmäßig',),
            "prob_not": ('filziert',),
            "open_must": ('morgen', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Stuckarbeiten Steinheim Gesims stuckiert Problem Profilbruch Offen Ersatzlieferung Mittwoch Kunde einverstanden.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "prob_must": ('bruch',),
            "open_must": ('mittwoch', 'offen'),
            "cust_must": ('einverstanden',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Schimmel beseitigt Problem Wiederbefall möglich Offen Feuchtemessung nächste Woche Auftraggeber informiert.',
            "acts": ('Schimmel beseitigt',),
            "prob_must": ('wiederbefall',),
            "open_must": ('woche', 'offen'),
            "cust_must": ('informiert',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'WDVS gedübelt Borgentreich Problem Dübelanzahl zu gering nach Prüfung Offen Nachdübeln Freitag.',
            "acts": ('WDVS gedübelt',),
            "prob_must": ('gering',),
            "prob_not": ('gedübelt',),
            "open_must": ('freitag', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Oberputz aufgetragen Putz geglättet Problem Oberfläche rau Offen Nachglätten Willebadessen Montag.',
            "acts": ('Oberputz aufgetragen', 'Putz geglättet'),
            "prob_must": ('rau',),
            "prob_not": ('geglättet',),
            "open_must": ('montag', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 2,
        },
        {
            "raw": 'APU-Leisten montiert Problem Anschluss undicht Offen Dichtlippe nachrüsten morgen Bauherr kurz informiert.',
            "acts": ('APU-Leisten montiert',),
            "prob_must": ('undicht',),
            "open_must": ('morgen', 'offen'),
            "cust_must": ('informiert',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Innenputz Kalkputz Bad Karlshafen Problem Staubentwicklung zu hoch Offen Rest Räume Dienstag Lüftung organisiert.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Kalkputz',),
            "prob_must": ('staub',),
            "prob_not": ('kalkputz',),
            "open_must": ('dienstag', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Tropfkantenprofile gesetzt Problem Profil verzogen Offen Austausch Ecke West Donnerstag.',
            "acts": ('Tropfkantenprofile gesetzt',),
            "prob_must": ('verzogen',),
            "prob_not": ('gesetzt',),
            "open_must": ('donnerstag', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Altputz entfernt Nieheim Problem Asbestverdacht Offen Gutachten abwarten Kunde informiert kein weiterer Abriss.',
            "acts": ('Altputz entfernt',),
            "prob_must": ('asbest',),
            "open_must": ('abwarten', 'offen'),
            "cust_must": ('informiert',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'WDVS Dämmung geklebt Problem Plattenverband falsch Offen Korrektur Block C Samstag Bauleitung angerufen.',
            "acts": ('WDVS Dämmung geklebt',),
            "prob_must": ('verband', 'falsch'),
            "open_must": ('samstag', 'offen'),
            "cust_must": ('angerufen',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Reibputz aufgetragen Steinheim Offen Kratzputz Schicht nächste Woche Bauherr wünscht feinere Struktur besprochen.',
            "acts": ('Reibputz aufgetragen', 'Kratzputz aufgetragen'),
            "open_must": ('woche', 'offen'),
            "cust_must": ('besprochen', 'wünscht'),
            "cust_not": ('reibputz',),
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Eckschutzprofile gesetzt Sockelprofil montiert Problem Höhenversatz Offen Ausgleich morgen Kunde einverstanden.',
            "acts": ('Eckschutzprofile gesetzt',),
            "prob_must": ('versatz',),
            "open_must": ('morgen', 'offen'),
            "cust_must": ('einverstanden',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'Fassadenarmierung Borgentreich Problem Mörtel zu dünn Offen zweite Lage Freitag.',
            "acts": (),
            "prob_must": ('dünn',),
            "prob_not": ('armierung',),
            "open_must": ('freitag', 'offen'),
            "min_act": 0,
        },
        {
            "raw": 'Heute nur Besichtigung mit Bauherr Problem Zugang gesperrt Offen Start Putzarbeiten Montag Termin fix.',
            "acts": (),
            "prob_must": ('gesperrt',),
            "open_must": ('montag', 'offen'),
            "cust_must": ('bauherr', 'termin'),
            "min_act": 0,
        },
        {
            "raw": 'Putzmaschine 6 std Willebadessen Innenputz Problem Schlauch undicht Offen Rest 40 qm Dienstag Mechaniker bestellt.',
            "acts": ('Innenputz aufgetragen',),
            "mach": ('Putzmaschine',),
            "prob_must": ('undicht',),
            "prob_not": ('innenputz',),
            "open_must": ('dienstag', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Sanierputz aufgebracht Schimmel beseitigt Problem Geruch im Keller Offen Lüftung prüfen Bad Karlshafen Donnerstag.',
            "acts": ('Sanierputz aufgebracht', 'Schimmel beseitigt'),
            "mats": ('Sanierputz',),
            "prob_must": ('geruch',),
            "prob_not": ('sanierputz',),
            "open_must": ('donnerstag', 'offen'),
            "problem": True,
            "open_": True,
            "min_act": 2,
        },
        {
            "raw": 'WDVS Dämmung geklebt mit EPS und Klebe- und Armierungsmörtel WDVS gedübelt Tellerdübel Armierungsgewebe eingebettet Putzmaschine 5 std.',
            "acts": ('WDVS Dämmung geklebt', 'WDVS gedübelt', 'Armierung ausgeführt'),
            "mats": ('EPS Dämmplatten', 'Klebe- und Armierungsmörtel', 'Tellerdübel', 'Armierungsgewebe'),
            "mach": ('Putzmaschine',),
            "forbid_sugs": ('Tellerdübel benutzt?',),
            "min_act": 3,
        },
        {
            "raw": 'Neubau Steinheim Grundputz aufgetragen Innenputz Gipsputz 95 Quadratmeter Sockelputz gemacht Feinputz nachgearbeitet.',
            "acts": ('Grundputz aufgetragen', 'Innenputz aufgetragen', 'Sockelputz aufgetragen'),
            "mats": ('Gipsputz', 'Feinputz'),
            "min_act": 3,
        },
        {
            "raw": 'An der Fassade WDVS Platten angeklebt Gewebe reingemacht Reibputz drauf Tropfkantenprofil gesetzt Eckschutzschiene gesetzt.',
            "acts": ('WDVS ausgeführt', 'Reibputz aufgetragen', 'Armierung ausgeführt', 'Tropfkantenprofile gesetzt', 'Eckschutzprofile gesetzt'),
            "min_act": 5,
        },
        {
            "raw": 'Schimmel beseitigt Sanierputz aufgebracht Unterputz aufgetragen Oberputz aufgetragen Haftgrund verwendet.',
            "acts": ('Sanierputz aufgebracht', 'Schimmel beseitigt', 'Oberputz aufgetragen', 'Unterputz aufgetragen'),
            "mats": ('Sanierputz',),
            "forbid_sugs": ('Schimmelentferner benutzt?', 'Haftgrund benutzt?'),
            "min_act": 4,
        },
        {
            "raw": 'Borgentreich Hotel-Fassade Kalkzementputz aufgetragen Kratzputz Reibputz nachgearbeitet Silikonharzputz verarbeitet.',
            "acts": ('Außenputz aufgetragen', 'Kratzputz aufgetragen', 'Reibputz aufgetragen'),
            "mats": ('Kalkzementputz', 'Silikonharzputz'),
            "min_act": 3,
        },
        {
            "raw": 'Holzfaserplatten geklebt WDVS Dämmung geklebt Mineralwolle ergänzt.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('Holzfaserplatten',),
            "min_act": 1,
        },
        {
            "raw": 'PU-Stuckprofil montiert Stuckkleber verarbeitet Gesims angebracht.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "mats": ('PU-Stuckprofil',),
            "forbid_sugs": ('Montagekleber benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Gips-Stuckprofil stuckiert Feinspachtel nachgearbeitet.',
            "acts": ('Stuckarbeiten durchgeführt',),
            "forbid_sugs": ('Feinspachtel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Lehmputz aufgetragen Innenputz Wohnbereich 45 Quadratmeter.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Lehmputz',),
            "min_act": 1,
        },
        {
            "raw": 'Kalkputz und Kalkfeinputz verarbeitet Putz geglättet.',
            "acts": ('Innenputz aufgetragen', 'Putz geglättet', 'Kalkfeinputz verarbeitet'),
            "mats": ('Kalkputz',),
            "min_act": 3,
        },
        {
            "raw": 'Armierungsgewebe 200g eingebettet. Armierungsmörtel verarbeitet.',
            "acts": ('Armierung ausgeführt',),
            "mats": ('Armierungsgewebe', 'Armierungsmörtel'),
            "forbid_sugs": ('Armierungsmörtel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'APU 6mm mit Gewebe montiert Anputzleiste Fensterbank.',
            "acts": ('APU-Leisten montiert',),
            "mats": ('APU-Leiste',),
            "min_act": 1,
        },
        {
            "raw": 'Eckschutzschiene Alu gesetzt PVC-Eckprofil Ersatz.',
            "acts": ('Eckschutzprofile gesetzt',),
            "mats": ('Eckschutzschiene',),
            "min_act": 1,
        },
        {
            "raw": 'Sockelprofil mit Tropfkante montiert Sockeldämmung eingebaut.',
            "acts": ('Sockelprofile montiert',),
            "forbid_sugs": ('Sockeldämmung benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Tropfkantenprofil PVC gesetzt Tropfkante Alu Fensterbrüstung.',
            "acts": ('Tropfkantenprofile gesetzt',),
            "mats": ('Tropfkantenprofil',),
            "min_act": 1,
        },
        {
            "raw": 'Willebadessen WDVS Komplett EPS geklebt gedübelt Armierung Reibputz Sockelprofil APU-Leisten Eckschutz Tropfkante.',
            "acts": ('WDVS gedübelt', 'Reibputz aufgetragen', 'Armierung ausgeführt'),
            "mats": ('EPS Dämmplatten',),
            "min_act": 3,
        },
        {
            "raw": 'Altputz entfernt Grundierung Unterputz Oberputz Putz geglättet Bad Karlshafen Sanierung.',
            "acts": ('Altputz entfernt', 'Putz geglättet'),
            "min_act": 2,
        },
        {
            "raw": 'Mineralwolle WDVS geklebt Schraubdübel Armierungsgewebe Reibputz Kratzputz Putz filziert.',
            "acts": ('Kratzputz aufgetragen', 'Putz filziert'),
            "mats": ('Mineralwolle',),
            "min_act": 2,
        },
        {
            "raw": 'Stuckarbeiten Nieheim PU-Profil Gesims Rosette Feinspachtel glatt.',
            "acts": (),
            "forbid_sugs": ('Feinspachtel benutzt?',),
            "min_act": 0,
        },
        {
            "raw": 'Grundputz Innenputz Gipsputz Sockelputz Leibungsprofile in einem Durchgang.',
            "acts": ('Grundputz aufgetragen',),
            "mats": ('Gipsputz',),
            "min_act": 1,
        },
        {
            "raw": 'Fassade Steinheim Haftgrund Silikatputz Kratzputz Reibputz filziert.',
            "acts": ('Kratzputz aufgetragen',),
            "mats": ('Silikatputz',),
            "min_act": 1,
        },
        {
            "raw": 'WDVS Dämmung Klebe- und Armierungsmörtel Tellerdübel Armierungsgewebe Sockelprofil Noppenbahn.',
            "acts": ('WDVS gedübelt',),
            "mats": ('Klebe- und Armierungsmörtel', 'Tellerdübel', 'Armierungsgewebe'),
            "forbid_sugs": ('Noppenbahn benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Borgentreich Schimmel Sanierputz Unterputz Oberputz Kalkfeinputz geglättet.',
            "acts": ('Sanierputz aufgebracht',),
            "mats": ('Sanierputz',),
            "min_act": 1,
        },
        {
            "raw": 'Leibungsprofil APU-Leiste Eckschutz Tropfkante Fensterkette komplett.',
            "acts": (),
            "min_act": 0,
        },
        {
            "raw": 'WDVS Willebadessen Holzfaserplatten Kleber Dübel Gewebe Reibputz Außenputz.',
            "acts": (),
            "mats": ('Holzfaserplatten',),
            "min_act": 0,
        },
        {
            "raw": 'Heute Nieheim und Steinheim zuerst Altputz runter Wand geschliffen Grundierung drauf Unterputz aufgetragen danach WDVS Dämmung geklebt Armierungsgewebe eingebettet Problem Starkregen mussten abbrechen Offen Oberputz Decke morgen Bauherr war einverstanden und zufrieden.',
            "acts": ('Altputz entfernt', 'Unterputz aufgetragen', 'WDVS Dämmung geklebt', 'Wand geschliffen', 'Armierung ausgeführt', 'Grundierung aufgetragen'),
            "prob_must": ('regen',),
            "open_must": ('oberputz', 'morgen'),
            "cust_must": ('zufrieden',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 6,
        },
        {
            "raw": 'Früh um halb sechs gestartet mit Sockelprofil montiert APU-Leiste montiert Leibungsprofil gesetzt Eckschutz gesetzt danach Innenputz mit Gipsputz aufgetragen Oberputz glatt Putz geglättet zwischendurch Bauleitung kurz informiert Termin abgestimmt leider Problem Putzmaschine defekt mussten stoppen dementsprechend machen wir morgen früh den Rest fertig Offen Fertigstellung nächste Woche.',
            "acts": ('Oberputz aufgetragen', 'Innenputz aufgetragen', 'Putz geglättet', 'Sockelprofile montiert', 'APU-Leisten montiert', 'Leibungsprofile gesetzt', 'Eckschutzprofile gesetzt'),
            "prob_must": ('defekt',),
            "open_must": ('woche',),
            "cust_must": ('informiert',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 7,
        },
        {
            "raw": 'Also heute vom Tag her erst den alten Putz abgetragen dann die Wand geschliffen danach grundiert Unterputz aufgetragen während der Unterputz trocknete WDVS gedübelt Tellerdübel gesetzt Armierungsgewebe eingebettet Reibputz aufgetragen nach dem Kundengespräch mit der Bauherrin Putz filziert Außenputz strukturiert Problem hohe Feuchte Offen Rest Decke Montag und Feierabend.',
            "acts": ('Altputz entfernt', 'Unterputz aufgetragen', 'Außenputz aufgetragen', 'WDVS gedübelt', 'Reibputz aufgetragen', 'Putz filziert', 'Wand geschliffen', 'Armierung ausgeführt', 'Grundierung aufgetragen'),
            "prob_must": ('feuchte',),
            "open_must": ('montag',),
            "cust_must": ('kundengespräch',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 9,
        },
        {
            "raw": 'Ja also vom Tag her WDVS Dämmung geklebt und also Außenputz Kratzputz aufgetragen Putz filziert und Feierabend.',
            "acts": ('Außenputz aufgetragen', 'WDVS Dämmung geklebt', 'Kratzputz aufgetragen', 'Putz filziert'),
            "min_act": 4,
        },
        {
            "raw": 'Morgens Borgentreich Schimmel weg gemacht Sanierputz drauf Unterputz nachgearbeitet mittags Oberputz aufgetragen nachmittags Putz geglättet Bauherr zufrieden.',
            "acts": ('Sanierputz aufgebracht', 'Schimmel beseitigt', 'Oberputz aufgetragen', 'Unterputz aufgetragen', 'Putz geglättet'),
            "cust_must": ('zufrieden',),
            "customer": True,
            "min_act": 5,
        },
        {
            "raw": 'Komplettsanierung Nieheim Treppenhaus: Altputz entfernt Grundputz aufgetragen Innenputz Kalkputz 110 Quadratmeter Sockelputz gemacht Leibungsprofile gesetzt Putzmaschine 7 std Kunde informiert.',
            "acts": ('Altputz entfernt', 'Grundputz aufgetragen', 'Innenputz aufgetragen', 'Sockelputz aufgetragen', 'Leibungsprofile gesetzt'),
            "mats": ('Kalkputz',),
            "mach": ('Putzmaschine',),
            "customer": True,
            "min_act": 5,
        },
        {
            "raw": 'WDVS Komplett Steinheim: Dämmung geklebt gedübelt Armierung Reibputz Sockelprofil montiert APU-Leisten montiert Tropfkanten gesetzt Eckschutz gesetzt Problem Lieferant zu spät Offen letzte Ecke Freitag.',
            "acts": ('WDVS Dämmung geklebt', 'WDVS gedübelt', 'Reibputz aufgetragen', 'Sockelprofile montiert', 'APU-Leisten montiert', 'Tropfkantenprofile gesetzt', 'Eckschutzprofile gesetzt', 'Armierung ausgeführt'),
            "prob_must": ('liefer', 'spät'),
            "open_must": ('freitag',),
            "problem": True,
            "open_": True,
            "min_act": 8,
        },
        {
            "raw": 'Innen und außen: Innenputz Gipsputz aufgetragen und am Ende Außenputz Silikatputz Kratzputz Putz filziert.',
            "acts": ('Innenputz aufgetragen', 'Außenputz aufgetragen', 'Kratzputz aufgetragen', 'Putz filziert'),
            "mats": ('Gipsputz', 'Silikatputz'),
            "min_act": 4,
        },
        {
            "raw": 'Megatag Willebadessen und Bad Karlshafen: Morgens WDVS kleben mittags dübeln nachmittags Armierung Reibputz Sockelprofil APU-Leisten Problem Hitze Offen Nordgiebel Donnerstag Bauleitung informiert.',
            "acts": ('WDVS gedübelt', 'Reibputz aufgetragen'),
            "prob_must": ('hitze',),
            "open_must": ('donnerstag',),
            "cust_must": ('informiert',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 2,
        },
        {
            "raw": 'Vollständiger Tagesbericht Borgentreich: Altputz ab Wand geschliffen grundiert Unterputz 80 qm Oberputz 40 qm geglättet Stuck Gesims Kundengespräch Farbton abgestimmt Problem Staub Offen Rest Flur Montag.',
            "acts": ('Altputz entfernt', 'Unterputz aufgetragen', 'Grundierung aufgetragen'),
            "prob_must": ('staub',),
            "open_must": ('montag',),
            "cust_must": ('abgestimmt',),
            "sum_qty": ('80',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 3,
        },
        {
            "raw": 'Also Nieheim Steinheim Willebadessen heute nur Besprechung und Materialcheck kein Putz wegen Frost Problem Wetter Offen Start Montag Bauherr Termin fix.',
            "acts": (),
            "prob_must": ('frost', 'wetter'),
            "open_must": ('montag',),
            "cust_must": ('termin', 'bauherr'),
            "min_act": 0,
        },
        {
            "raw": 'Riesen WDVS-Tag Bad Karlshafen: EPS 160 qm geklebt gedübelt Gewebe Reibputz Kratzputz filziert Sockelprofil Tropfkante Eckschutz Leibungsprofile 18 Fenster Putzmaschine 9 std Bauherr zufrieden Problem Materialrest knapp Offen letzte 20 qm Freitag.',
            "acts": ('WDVS gedübelt',),
            "mach": ('Putzmaschine',),
            "prob_must": ('knapp',),
            "open_must": ('freitag',),
            "cust_must": ('zufrieden',),
            "sum_qty": ('20',),
            "problem": True,
            "open_": True,
            "customer": True,
            "min_act": 1,
        },
        {
            "raw": 'innenputz gipsputz drauf 40 qm',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "sum_qty": ('40',),
            "min_act": 1,
        },
        {
            "raw": 'wdvs kleben fertig',
            "acts": ('WDVS Dämmung geklebt',),
            "min_act": 1,
        },
        {
            "raw": 'putz glätten feinputz',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "min_act": 1,
        },
        {
            "raw": 'eckschutz gesetzt',
            "acts": ('Eckschutzprofile gesetzt',),
            "min_act": 1,
        },
        {
            "raw": 'hamma wdvs gedübelt tellerdübel',
            "acts": ('WDVS gedübelt',),
            "mats": ('Tellerdübel',),
            "forbid_sugs": ('Tellerdübel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'putz filziert mit filzbrett',
            "acts": ('Putz filziert',),
            "forbid_sugs": ('Filzbrett benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'problem regen offen morgen kein putz',
            "acts": (),
            "prob_must": ('regen',),
            "open_must": ('morgen',),
            "min_act": 0,
        },
        {
            "raw": 'bauherr kurz da',
            "acts": (),
            "cust_must": ('bauherr',),
            "min_act": 0,
        },
        {
            "raw": 'stuck gemacht gesims',
            "acts": ('Stuckarbeiten durchgeführt',),
            "min_act": 1,
        },
        {
            "raw": 'reibputz drauf armierung',
            "acts": ('Reibputz aufgetragen', 'Armierung ausgeführt'),
            "min_act": 2,
        },
        {
            "raw": 'heute nur bauleitung informiert termin',
            "acts": (),
            "cust_must": ('informiert', 'termin'),
            "min_act": 0,
        },
        {
            "raw": 'oberputz glatt putz geglättet',
            "acts": ('Oberputz aufgetragen', 'Putz geglättet'),
            "min_act": 2,
        },
        {
            "raw": '50qm oberputz drauf',
            "acts": ('Oberputz aufgetragen',),
            "sum_qty": ('50',),
            "min_act": 1,
        },
        {
            "raw": 'unterputz 70 qm fertig',
            "acts": ('Unterputz aufgetragen',),
            "sum_qty": ('70',),
            "min_act": 1,
        },
        {
            "raw": 'wdvs 130qm geklebt',
            "acts": ('WDVS Dämmung geklebt',),
            "min_act": 1,
        },
        {
            "raw": 'kratzputz 90m² filziert',
            "acts": ('Putz filziert',),
            "min_act": 1,
        },
        {
            "raw": 'problem wind offen freitag',
            "acts": (),
            "prob_must": ('wind',),
            "open_must": ('freitag',),
            "min_act": 0,
        },
        {
            "raw": 'kunde will feinere struktur',
            "acts": (),
            "cust_must": ('struktur',),
            "min_act": 0,
        },
        {
            "raw": '30 Quadratmeter Innenputz Gipsputz aufgetragen Nieheim.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "sugs": ('Putzmaschine benutzt?',),
            "sum_qty": ('30',),
            "min_act": 1,
        },
        {
            "raw": '30 qm² WDVS Dämmung geklebt EPS Steinheim Fassade.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "sugs": ('Zahntraufel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Putz geglättet 30 m² Feinputz Decke Borgentreich.',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "sugs": ('Glättkelle benutzt?',),
            "forbid_sugs": ('Feinputz benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'WDVS gedübelt 30 Quadratmeter Tellerdübel Willebadessen.',
            "acts": ('WDVS gedübelt',),
            "mats": ('Tellerdübel',),
            "forbid_sugs": ('Tellerdübel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": '35 Meter APU-Leiste montiert Eckschutzschiene Bad Karlshafen.',
            "acts": ('APU-Leisten montiert',),
            "sugs": ('Klebeputz benutzt?',),
            "min_act": 1,
        },
        {
            "raw": '35 qm² Außenputz Kratzputz Reibputz Putz filziert Nieheim.',
            "acts": ('Außenputz aufgetragen', 'Reibputz aufgetragen', 'Kratzputz aufgetragen', 'Putz filziert'),
            "sugs": ('Filzbrett benutzt?',),
            "sum_qty": ('35',),
            "min_act": 4,
        },
        {
            "raw": 'Oberputz 35qm² aufgetragen Steinheim Wohnzimmer.',
            "acts": ('Oberputz aufgetragen',),
            "sum_qty": ('35',),
            "min_act": 1,
        },
        {
            "raw": 'Unterputz 35 Quadratmeter Borgentreich Treppenhaus.',
            "acts": ('Unterputz aufgetragen',),
            "sum_qty": ('35',),
            "min_act": 1,
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 40 Fenster Willebadessen Problem Material fehlt Offen Rest Donnerstag.',
            "acts": ('Leibungsprofile gesetzt',),
            "mats": ('Leibungsprofil',),
            "sugs": ('Klebeputz benutzt?',),
            "prob_must": ('material',),
            "open_must": ('donnerstag',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Reibputz 40 m² WDVS Bad Karlshafen Armierung fertig.',
            "acts": ('Armierung ausgeführt',),
            "min_act": 1,
        },
        {
            "raw": 'Innenputz Kalkputz 40 qm² Nieheim Altbau.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Kalkputz',),
            "sugs": ('Putzmaschine benutzt?',),
            "sum_qty": ('40',),
            "min_act": 1,
        },
        {
            "raw": 'Sockelprofil 40 Millimeter montiert Tropfkante Steinheim.',
            "acts": ('Sockelprofile montiert',),
            "mats": ('Sockelprofil',),
            "sugs": ('Sockeldämmung benutzt?',),
            "min_act": 1,
        },
        {
            "raw": '45 Quadratmeter Innenputz Gipsputz aufgetragen Borgentreich.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "sugs": ('Putzmaschine benutzt?',),
            "sum_qty": ('45',),
            "min_act": 1,
        },
        {
            "raw": '45 qm² WDVS Dämmung geklebt EPS Willebadessen Fassade.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "sugs": ('Zahntraufel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Putz geglättet 45 m² Feinputz Decke Bad Karlshafen.',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "sugs": ('Glättkelle benutzt?',),
            "forbid_sugs": ('Feinputz benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'WDVS gedübelt 45 Quadratmeter Tellerdübel Nieheim.',
            "acts": ('WDVS gedübelt',),
            "mats": ('Tellerdübel',),
            "forbid_sugs": ('Tellerdübel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": '50 Meter APU-Leiste montiert Eckschutzschiene Steinheim.',
            "acts": ('APU-Leisten montiert',),
            "sugs": ('Klebeputz benutzt?',),
            "min_act": 1,
        },
        {
            "raw": '50 qm² Außenputz Kratzputz Reibputz Putz filziert Borgentreich.',
            "acts": ('Außenputz aufgetragen', 'Reibputz aufgetragen', 'Kratzputz aufgetragen', 'Putz filziert'),
            "sugs": ('Filzbrett benutzt?',),
            "sum_qty": ('50',),
            "min_act": 4,
        },
        {
            "raw": 'Oberputz 50qm² aufgetragen Willebadessen Wohnzimmer.',
            "acts": ('Oberputz aufgetragen',),
            "sum_qty": ('50',),
            "min_act": 1,
        },
        {
            "raw": 'Unterputz 50 Quadratmeter Bad Karlshafen Treppenhaus.',
            "acts": ('Unterputz aufgetragen',),
            "sum_qty": ('50',),
            "min_act": 1,
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 55 Fenster Nieheim Problem Material fehlt Offen Rest Donnerstag.',
            "acts": ('Leibungsprofile gesetzt',),
            "mats": ('Leibungsprofil',),
            "sugs": ('Klebeputz benutzt?',),
            "prob_must": ('material',),
            "open_must": ('donnerstag',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Reibputz 55 m² WDVS Steinheim Armierung fertig.',
            "acts": ('Armierung ausgeführt',),
            "min_act": 1,
        },
        {
            "raw": 'Innenputz Kalkputz 55 qm² Borgentreich Altbau.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Kalkputz',),
            "sugs": ('Putzmaschine benutzt?',),
            "sum_qty": ('55',),
            "min_act": 1,
        },
        {
            "raw": 'Sockelprofil 55 Millimeter montiert Tropfkante Willebadessen.',
            "acts": ('Sockelprofile montiert',),
            "mats": ('Sockelprofil',),
            "sugs": ('Sockeldämmung benutzt?',),
            "min_act": 1,
        },
        {
            "raw": '60 Quadratmeter Innenputz Gipsputz aufgetragen Bad Karlshafen.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "sugs": ('Putzmaschine benutzt?',),
            "sum_qty": ('60',),
            "min_act": 1,
        },
        {
            "raw": '60 qm² WDVS Dämmung geklebt EPS Nieheim Fassade.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "sugs": ('Zahntraufel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Putz geglättet 60 m² Feinputz Decke Steinheim.',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "sugs": ('Glättkelle benutzt?',),
            "forbid_sugs": ('Feinputz benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'WDVS gedübelt 60 Quadratmeter Tellerdübel Borgentreich.',
            "acts": ('WDVS gedübelt',),
            "mats": ('Tellerdübel',),
            "forbid_sugs": ('Tellerdübel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": '65 Meter APU-Leiste montiert Eckschutzschiene Willebadessen.',
            "acts": ('APU-Leisten montiert',),
            "sugs": ('Klebeputz benutzt?',),
            "min_act": 1,
        },
        {
            "raw": '65 qm² Außenputz Kratzputz Reibputz Putz filziert Bad Karlshafen.',
            "acts": ('Außenputz aufgetragen', 'Reibputz aufgetragen', 'Kratzputz aufgetragen', 'Putz filziert'),
            "sugs": ('Filzbrett benutzt?',),
            "sum_qty": ('65',),
            "min_act": 4,
        },
        {
            "raw": 'Oberputz 65qm² aufgetragen Nieheim Wohnzimmer.',
            "acts": ('Oberputz aufgetragen',),
            "sum_qty": ('65',),
            "min_act": 1,
        },
        {
            "raw": 'Unterputz 65 Quadratmeter Steinheim Treppenhaus.',
            "acts": ('Unterputz aufgetragen',),
            "sum_qty": ('65',),
            "min_act": 1,
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 70 Fenster Borgentreich Problem Material fehlt Offen Rest Donnerstag.',
            "acts": ('Leibungsprofile gesetzt',),
            "mats": ('Leibungsprofil',),
            "sugs": ('Klebeputz benutzt?',),
            "prob_must": ('material',),
            "open_must": ('donnerstag',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Reibputz 70 m² WDVS Willebadessen Armierung fertig.',
            "acts": ('Armierung ausgeführt',),
            "min_act": 1,
        },
        {
            "raw": 'Innenputz Kalkputz 70 qm² Bad Karlshafen Altbau.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Kalkputz',),
            "sugs": ('Putzmaschine benutzt?',),
            "sum_qty": ('70',),
            "min_act": 1,
        },
        {
            "raw": 'Sockelprofil 70 Millimeter montiert Tropfkante Nieheim.',
            "acts": ('Sockelprofile montiert',),
            "mats": ('Sockelprofil',),
            "sugs": ('Sockeldämmung benutzt?',),
            "min_act": 1,
        },
        {
            "raw": '75 Quadratmeter Innenputz Gipsputz aufgetragen Steinheim.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "sugs": ('Putzmaschine benutzt?',),
            "sum_qty": ('75',),
            "min_act": 1,
        },
        {
            "raw": '75 qm² WDVS Dämmung geklebt EPS Borgentreich Fassade.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "sugs": ('Zahntraufel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Putz geglättet 75 m² Feinputz Decke Willebadessen.',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "sugs": ('Glättkelle benutzt?',),
            "forbid_sugs": ('Feinputz benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'WDVS gedübelt 75 Quadratmeter Tellerdübel Bad Karlshafen.',
            "acts": ('WDVS gedübelt',),
            "mats": ('Tellerdübel',),
            "forbid_sugs": ('Tellerdübel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": '80 Meter APU-Leiste montiert Eckschutzschiene Nieheim.',
            "acts": ('APU-Leisten montiert',),
            "sugs": ('Klebeputz benutzt?',),
            "min_act": 1,
        },
        {
            "raw": '80 qm² Außenputz Kratzputz Reibputz Putz filziert Steinheim.',
            "acts": ('Außenputz aufgetragen', 'Reibputz aufgetragen', 'Kratzputz aufgetragen', 'Putz filziert'),
            "sugs": ('Filzbrett benutzt?',),
            "sum_qty": ('80',),
            "min_act": 4,
        },
        {
            "raw": 'Oberputz 80qm² aufgetragen Borgentreich Wohnzimmer.',
            "acts": ('Oberputz aufgetragen',),
            "sum_qty": ('80',),
            "min_act": 1,
        },
        {
            "raw": 'Unterputz 80 Quadratmeter Willebadessen Treppenhaus.',
            "acts": ('Unterputz aufgetragen',),
            "sum_qty": ('80',),
            "min_act": 1,
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 85 Fenster Bad Karlshafen Problem Material fehlt Offen Rest Donnerstag.',
            "acts": ('Leibungsprofile gesetzt',),
            "mats": ('Leibungsprofil',),
            "sugs": ('Klebeputz benutzt?',),
            "prob_must": ('material',),
            "open_must": ('donnerstag',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Reibputz 85 m² WDVS Nieheim Armierung fertig.',
            "acts": ('Armierung ausgeführt',),
            "min_act": 1,
        },
        {
            "raw": 'Innenputz Kalkputz 85 qm² Steinheim Altbau.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Kalkputz',),
            "sugs": ('Putzmaschine benutzt?',),
            "sum_qty": ('85',),
            "min_act": 1,
        },
        {
            "raw": 'Sockelprofil 85 Millimeter montiert Tropfkante Borgentreich.',
            "acts": ('Sockelprofile montiert',),
            "mats": ('Sockelprofil',),
            "sugs": ('Sockeldämmung benutzt?',),
            "min_act": 1,
        },
        {
            "raw": '90 Quadratmeter Innenputz Gipsputz aufgetragen Willebadessen.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "sugs": ('Putzmaschine benutzt?',),
            "sum_qty": ('90',),
            "min_act": 1,
        },
        {
            "raw": '90 qm² WDVS Dämmung geklebt EPS Bad Karlshafen Fassade.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "sugs": ('Zahntraufel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Putz geglättet 90 m² Feinputz Decke Nieheim.',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "sugs": ('Glättkelle benutzt?',),
            "forbid_sugs": ('Feinputz benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'WDVS gedübelt 90 Quadratmeter Tellerdübel Steinheim.',
            "acts": ('WDVS gedübelt',),
            "mats": ('Tellerdübel',),
            "forbid_sugs": ('Tellerdübel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": '95 Meter APU-Leiste montiert Eckschutzschiene Borgentreich.',
            "acts": ('APU-Leisten montiert',),
            "sugs": ('Klebeputz benutzt?',),
            "min_act": 1,
        },
        {
            "raw": '95 qm² Außenputz Kratzputz Reibputz Putz filziert Willebadessen.',
            "acts": ('Außenputz aufgetragen', 'Reibputz aufgetragen', 'Kratzputz aufgetragen', 'Putz filziert'),
            "sugs": ('Filzbrett benutzt?',),
            "sum_qty": ('95',),
            "min_act": 4,
        },
        {
            "raw": 'Oberputz 95qm² aufgetragen Bad Karlshafen Wohnzimmer.',
            "acts": ('Oberputz aufgetragen',),
            "sum_qty": ('95',),
            "min_act": 1,
        },
        {
            "raw": 'Unterputz 95 Quadratmeter Nieheim Treppenhaus.',
            "acts": ('Unterputz aufgetragen',),
            "sum_qty": ('95',),
            "min_act": 1,
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 100 Fenster Steinheim Problem Material fehlt Offen Rest Donnerstag.',
            "acts": ('Leibungsprofile gesetzt',),
            "mats": ('Leibungsprofil',),
            "sugs": ('Klebeputz benutzt?',),
            "prob_must": ('material',),
            "open_must": ('donnerstag',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Reibputz 100 m² WDVS Borgentreich Armierung fertig.',
            "acts": ('Armierung ausgeführt',),
            "min_act": 1,
        },
        {
            "raw": 'Innenputz Kalkputz 100 qm² Willebadessen Altbau.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Kalkputz',),
            "sugs": ('Putzmaschine benutzt?',),
            "sum_qty": ('100',),
            "min_act": 1,
        },
        {
            "raw": 'Sockelprofil 100 Millimeter montiert Tropfkante Bad Karlshafen.',
            "acts": ('Sockelprofile montiert',),
            "mats": ('Sockelprofil',),
            "sugs": ('Sockeldämmung benutzt?',),
            "min_act": 1,
        },
        {
            "raw": '105 Quadratmeter Innenputz Gipsputz aufgetragen Nieheim.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Gipsputz',),
            "sugs": ('Putzmaschine benutzt?',),
            "sum_qty": ('105',),
            "min_act": 1,
        },
        {
            "raw": '105 qm² WDVS Dämmung geklebt EPS Steinheim Fassade.',
            "acts": ('WDVS Dämmung geklebt',),
            "mats": ('EPS Dämmplatten',),
            "sugs": ('Zahntraufel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'Putz geglättet 105 m² Feinputz Decke Borgentreich.',
            "acts": ('Putz geglättet',),
            "mats": ('Feinputz',),
            "sugs": ('Glättkelle benutzt?',),
            "forbid_sugs": ('Feinputz benutzt?',),
            "min_act": 1,
        },
        {
            "raw": 'WDVS gedübelt 105 Quadratmeter Tellerdübel Willebadessen.',
            "acts": ('WDVS gedübelt',),
            "mats": ('Tellerdübel',),
            "forbid_sugs": ('Tellerdübel benutzt?',),
            "min_act": 1,
        },
        {
            "raw": '110 Meter APU-Leiste montiert Eckschutzschiene Bad Karlshafen.',
            "acts": ('APU-Leisten montiert',),
            "sugs": ('Klebeputz benutzt?',),
            "min_act": 1,
        },
        {
            "raw": '110 qm² Außenputz Kratzputz Reibputz Putz filziert Nieheim.',
            "acts": ('Außenputz aufgetragen', 'Reibputz aufgetragen', 'Kratzputz aufgetragen', 'Putz filziert'),
            "sugs": ('Filzbrett benutzt?',),
            "sum_qty": ('110',),
            "min_act": 4,
        },
        {
            "raw": 'Oberputz 110qm² aufgetragen Steinheim Wohnzimmer.',
            "acts": ('Oberputz aufgetragen',),
            "sum_qty": ('110',),
            "min_act": 1,
        },
        {
            "raw": 'Unterputz 110 Quadratmeter Borgentreich Treppenhaus.',
            "acts": ('Unterputz aufgetragen',),
            "sum_qty": ('110',),
            "min_act": 1,
        },
        {
            "raw": 'Leibungsprofil PVC gesetzt 115 Fenster Willebadessen Problem Material fehlt Offen Rest Donnerstag.',
            "acts": ('Leibungsprofile gesetzt',),
            "mats": ('Leibungsprofil',),
            "sugs": ('Klebeputz benutzt?',),
            "prob_must": ('material',),
            "open_must": ('donnerstag',),
            "problem": True,
            "open_": True,
            "min_act": 1,
        },
        {
            "raw": 'Reibputz 115 m² WDVS Bad Karlshafen Armierung fertig.',
            "acts": ('Armierung ausgeführt',),
            "min_act": 1,
        },
        {
            "raw": 'Innenputz Kalkputz 115 qm² Nieheim Altbau.',
            "acts": ('Innenputz aufgetragen',),
            "mats": ('Kalkputz',),
            "sugs": ('Putzmaschine benutzt?',),
            "sum_qty": ('115',),
            "min_act": 1,
        },
    ]
