from __future__ import annotations

TRADE_PROFILES: dict[str, dict[str, object]] = {
    "galabau": {
        "keywords": [
            "pflaster",
            "splitt",
            "schotter",
            "randstein",
            "pflanzkübel",
            "substrat",
            "garten",
            "terrasse",
        ],
        "materials": ["Pflastersteine", "Splitt", "Schotter", "Pflanzsubstrat", "Randsteine"],
        "phrases": [
            "Pflaster verlegt",
            "Schotter eingebaut",
            "Pflanzkübel vorbereitet",
            "Pflanzsubstrat eingebracht",
            "Pflanzkübel mit Pflanzsubstrat verfüllt",
        ],
        "colloquial": ["pflaster gemacht", "erde reingemacht", "schotter rein"],
        "synonyms": ["landschaftsbau", "gartenbau", "außenanlage"],
        "normalization": {
            "pflaster gemacht": "Pflaster verlegt",
            "pflaster gelegt": "Pflaster verlegt",
            "verlegung von pflaster": "Pflaster verlegt",
            "erde reingemacht": "Pflanzsubstrat eingebracht",
            "schotter rein": "Schotter eingebaut",
            "pflanzkübel fertig gemacht": "Pflanzkübel vorbereitet",
            "pflanzkuebel fertig gemacht": "Pflanzkübel vorbereitet",
        },
    },
    "trockenbau": {
        "keywords": ["rigips", "trockenbau", "ständerwerk", "wand", "spachtel"],
        "materials": ["Gipskartonplatten", "Schnellbauschrauben", "Spachtelmasse", "Profile"],
        "phrases": [
            "Gipskartonplatten montiert",
            "Trockenbauwand geschlossen",
            "Verspachtelungsarbeiten durchgeführt",
        ],
        "colloquial": ["rigips dran gemacht", "wand zugemacht", "zugespachtelt"],
        "synonyms": ["gipskarton", "innenausbau"],
        "normalization": {
            "rigips": "Gipskartonplatten",
            "rigips dran gemacht": "Gipskartonplatten montiert",
            "wand zugemacht": "Trockenbauwand geschlossen",
            "zugespachtelt": "Verspachtelungsarbeiten durchgeführt",
        },
    },
    "shk": {
        "keywords": ["rohr", "heizung", "wasser", "anschluss", "sanitär", "sanitaer"],
        "materials": ["Rohrleitungen", "Fittings", "Befestigungsmaterial", "Heizungsanlage"],
        "phrases": [
            "Rohrleitungen installiert",
            "Heizungsanlage montiert",
            "Trinkwasseranschlüsse hergestellt",
            "Heizungsanschlüsse hergestellt",
            "Montage der Wasserleitungen",
        ],
        "colloquial": ["rohre gelegt", "heizung eingebaut", "wasser angeschlossen"],
        "synonyms": ["sanitär", "heizung", "klima"],
        "normalization": {
            "rohre gelegt": "Rohrleitungen installiert",
            "heizung eingebaut": "Heizungsanlage montiert",
            "heizung angeschlossen": "Heizungsanschlüsse hergestellt",
            "wasser angeschlossen": "Montage der Wasserleitungen",
            "wasserleitung montiert": "Montage der Wasserleitungen",
        },
    },
    "fliesenleger": {
        "keywords": ["fliese", "fliese", "fuge", "kleber", "spiegel"],
        "materials": ["Fliesen", "Fliesenkleber", "Fugenmörtel", "Abdichtung"],
        "phrases": [
            "Fliesen verlegt",
            "Fliesenkleber aufgetragen",
            "Verfugungsarbeiten durchgeführt",
        ],
        "colloquial": ["fliesen gelegt", "fliesen gemacht", "kleber gezogen", "verfugt"],
        "synonyms": ["plattenleger", "keramikarbeiten"],
        "normalization": {
            "fliesen gelegt": "Fliesen verlegt",
            "fliesen gemacht": "Fliesenarbeiten durchgeführt",
            "kleber gezogen": "Fliesenkleber aufgetragen",
            "verfugt": "Verfugungsarbeiten durchgeführt",
            "silikon gezogen": "Herstellung von Silikonfugen",
        },
    },
    "hochbau": {
        "keywords": ["mauer", "beton", "bewehrung", "sturz", "decke"],
        "materials": ["Mauersteine", "Mörtel", "Beton", "Bewehrungsstahl"],
        "phrases": ["Mauerwerk erstellt", "Betonarbeiten durchgeführt"],
        "colloquial": ["mauer gebaut", "beton gemacht"],
        "synonyms": ["rohbau"],
        "normalization": {
            "mauer gebaut": "Mauerwerk erstellt",
            "beton gemacht": "Betonarbeiten durchgeführt",
        },
    },
    "tiefbau": {
        "keywords": ["graben", "kanal", "verdichtung", "leitungstrasse", "aushub"],
        "materials": ["Kies", "Schotter", "Rohrleitungen", "Asphalt"],
        "phrases": ["Leitungstrasse hergestellt", "Graben ausgehoben", "Verdichtungsarbeiten durchgeführt"],
        "colloquial": ["graben gezogen", "boden verdichtet"],
        "synonyms": ["erdarbeiten"],
        "normalization": {
            "graben gezogen": "Graben ausgehoben",
            "boden verdichtet": "Verdichtungsarbeiten durchgeführt",
        },
    },
    "sanierung": {
        "keywords": ["schimmel", "altputz", "sanierputz", "entfeuchtung", "riss"],
        "materials": ["Sanierputz", "Grundierung", "Schutzmittel", "Entfeuchtungsputz"],
        "phrases": [
            "Altputz entfernt",
            "Schimmelbeseitigung durchgeführt",
            "Sanierputz aufgetragen",
            "Aufbringung von Sanierputz",
        ],
        "colloquial": ["schimmel weg gemacht", "putz runter", "sanierputz drauf gemacht"],
        "synonyms": ["instandsetzung", "altbausanierung"],
        "normalization": {
            "schimmel entfernt": "Schimmelbeseitigung durchgeführt",
            "schimmel weg gemacht": "Schimmelbefall behandelt",
            "putz runter": "Altputz entfernt",
            "alten putz runtergemacht": "Altputz entfernt",
            "den alten putz runtergemacht": "Altputz entfernt",
            "sanierputz drauf gemacht": "Aufbringung von Sanierputz",
            "sanierputz aufgebracht": "Aufbringung von Sanierputz",
            "sanierputz aufgetragen": "Aufbringung von Sanierputz",
        },
    },
    "elektro": {
        "keywords": ["kabel", "leitung", "dose", "schalter", "leuchte", "verteiler"],
        "materials": ["Elektroleitungen", "Installationsmaterial", "Installationsdosen", "Leuchten"],
        "phrases": ["Leitungen verlegt", "Installationsdosen gesetzt", "Leuchte angeschlossen"],
        "colloquial": ["kabel gezogen", "dosen gesetzt", "lampe angeschlossen"],
        "synonyms": ["elektroinstallation"],
        "normalization": {
            "kabel gezogen": "Leitungen verlegt",
            "dosen gesetzt": "Installationsdosen gesetzt",
            "lampe angeschlossen": "Leuchte angeschlossen",
        },
    },
    "dachdecker": {
        "keywords": ["dach", "ziegel", "abdichtung", "attika", "rinne", "dachbahn"],
        "materials": ["Dachziegel", "Unterspannbahn", "Abdichtungsbahn", "Befestigungsmaterial"],
        "phrases": ["Dachfläche eingedeckt", "Abdichtungsarbeiten durchgeführt"],
        "colloquial": ["dach zugemacht", "dach dicht gemacht"],
        "synonyms": ["dacharbeiten", "abdichtung"],
        "normalization": {
            "dach zugemacht": "Dachfläche eingedeckt",
            "dach dicht gemacht": "Abdichtungsarbeiten durchgeführt",
        },
    },
    "maler": {
        "keywords": ["farbe", "spachtel", "anstrich", "putz", "grundierung", "rolle"],
        "materials": ["Farbe", "Grundierung", "Spachtelmasse", "Abdeckmaterial"],
        "phrases": ["Anstricharbeiten durchgeführt", "Spachtelarbeiten durchgeführt"],
        "colloquial": ["gestrichen", "farbe drauf gemacht"],
        "synonyms": ["malerarbeiten", "lackierung"],
        "normalization": {
            "farbe drauf gemacht": "Anstricharbeiten durchgeführt",
            "gestrichen": "Anstricharbeiten durchgeführt",
        },
    },
}
